### ISSUE TITLE
[Feature] Notebook centric workspace 

### ISSUE THREAD

**Issue by Jeffwan** [ray-project/kuberay#103]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Data scientist spend most of their time on notebooks for fast prototype, results visualization etc.  Notebook-centric development becomes fundamental to data science. 

We expect a managed experiences for DS to create or destroy their workspace, run arbitrary experiments without worrying about breaking the environments.

### Use case

Provides a workspace with notebook with deep integration with Ray.  The integration with existing Ray feature would be highly preferred. 

1. Debugging tools
2. Ray Dashboards
3. Tenosorboards etc

We can also add some more features like 
1. Jupyter Notebooks in one click and scale on demand
2. Pre-configured and extensible data scientist and Machine Learning environments
3. Real-time GPU monitoring for resource and performance optimization
4. Explore heterogeneous support to offload resource intensive jobs to GPU cluster.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by Jeffwan** [comment]
I feel some advanced production integration can be build here. I feel it's better to build notebook as the UI entrypoint of the system. 

1. Build notebook extension to launch and manage Ray clusters
2. Submit code to remote instead of local kernel make this more attractive. 
3. Built-in monitoring solution for those ray clusters.

**Comment by Jeffwan** [comment]
I am think to build a notebook solution on kubernetes with deep ray integration. 

1. Notebook controller will provide a `Notebook` [Customer Resource Definition (CRD)](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#customresourcedefinitions).
User can specify the `Pod Template` and some customized fields to create a notebook. 

```yaml
apiVersion: kuberay.ray.io/v1alpha1
kind: Notebook
metadata:
  name: notebook-sample
spec:
  template:
    spec: # Your PodSpec here
      containers:
      - image: kuberay/ray-notebook-image:1.9.2
        name: notebook-sample
        resources:
          limits:
            cpu: "0.5"
            memory: 1.0Gi
          requests:
            cpu: "0.5"
            memory: 1.0Gi
        volumeMounts:
#        - mountPath: /home/jovyan
#          name: workspace-notebook-sample
        - mountPath: /dev/shm
          name: dshm
      serviceAccountName: default
      volumes:
#      - name: workspace-notebook-sample
#        persistentVolumeClaim:
#          claimName: workspace-notebook-sample
      - emptyDir:
          medium: Memory
        name: dshm
```

2.  Ray cluster and Ray Notebook Image could be same. notebook image just uses a different entrypoint. In this case, it help make sure development in client side and production workloads use exact same environment. 

3.  The downside of the notebook is the resources. We should explore a way to submit tasks to the remote kernel which could be a spawned ray cluster.
