### ISSUE TITLE
[Helm] ray-cluster chart fails to parse envFrom field in additionalWorkerGroups

### ISSUE THREAD

**Issue by dirtyValera** [ray-project/kuberay#1038]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

Others

### What happened + What you expected to happen

Setting `envFrom` to anything but empty array in `additionalWorkerGroups` results in 

```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(RayCluster.spec.workerGroupSpecs[0].template.spec.containers[0].envFrom): invalid type
for io.ray.v1alpha1.RayCluster.spec.workerGroupSpecs.template.spec.containers.envFrom: got "map", expected "array"
```

### Reproduction script

In `helm-chart/ray-cluster/values.yaml` set:

```
additionalWorkerGroups:
    ...
    envFrom:
      - secretRef:
          name: ray-mysql-secret
      - secretRef:
          name: ray-aws-creds-secret
    ...
```

Run helm, see:

```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(RayCluster.spec.workerGroupSpecs[0].template.spec.containers[0].envFrom): invalid type
for io.ray.v1alpha1.RayCluster.spec.workerGroupSpecs.template.spec.containers.envFrom: got "map", expected "array"
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!
