### ISSUE TITLE
[Bug] Raylet missing on worker group

### ISSUE THREAD

**Issue by shinysingh** [ray-project/kuberay#1063]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

I created a worker pool in my ray cluster, where I run a python script that starts remote tasks. However I’m having trouble submitting any ray tasks there due to the following error. The raylet doesn’t seem to exist. Any idea why this could be?
`
"This node has an IP address of 10.17.4.16, and Ray expects this IP address to be either the GCS address or one of the Raylet addresses. Connected to GCS at ray-autoscaler-head-svc.ray.svc.cluster.local and found raylets at 10.17.1.30, 10.17.7.7, 10.17.0.3 but none of these match this node's IP 10.17.4.16. Are any of these actually a different IP address for the same node?You might need to provide --node-ip-address to specify the IP address that the head should use when sending to this node.
`

### Reproduction script

Python test.py
```
import ray

@ray.remote(num_cpus=1)
def run_process():
	print("Process code goes here")

def main():
	ray.get(run_process.remote())
if __name__ == '__main__':

	main()
```
Build a docker image using the dockerfile below:
```
FROM python:3.8-buster

RUN pip3 install --upgrade "ray[default]"
WORKDIR /app

COPY test.py /app
```

RayCluster YAML:
```
apiVersion: ray.io/v1alpha1
kind: RayCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: ray_autoscaler
spec:
  rayVersion: '2.3.0'
  enableInTreeAutoscaling: true
  autoscalerOptions:
    upscalingMode: Default
    idleTimeoutSeconds: 60
    imagePullPolicy: Always
    securityContext: {}
    env: []
    envFrom: []
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "500m"
        memory: "512Mi"
  # Ray head pod template
  headGroupSpec:
    serviceType: ClusterIP # optional
    rayStartParams:
      dashboard-host: '0.0.0.0'
      block: 'true'
      num-cpus: '0'
    template:
      spec:
        containers:
        # The Ray head container
        - name: ray-head
          image: test-image
          imagePullPolicy: Always
          ports:
          - containerPort: 6379
            name: gcs
          - containerPort: 8265
            name: dashboard
          - containerPort: 10001
            name: client
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","ray stop"]
          resources:
            limits:
              cpu: "14"
              memory: "50G"
            requests:
              cpu: "14"
              memory: "50G"

  workerGroupSpecs:
  # the pod replicas in this group typed worker
  - replicas: 1
    minReplicas: 0
    maxReplicas: 10
    groupName: cpu-group
    rayStartParams:
      block: 'true'
    #pod template
    template:
      spec:
        initContainers:
        # the env var $RAY_IP is set by the operator if missing, with the value of the head service name
        - name: init
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup $RAY_IP.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for K8s Service $RAY_IP; sleep 2; done"]
        containers:
        - name: ray-worker-cpu
          image: test-image
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","ray stop"]
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "14"
              memory: "50G"
            requests:
              cpu: "14"
              memory: "50G"
  - replicas: 1
    minReplicas: 1
    maxReplicas: 1
    groupName: job-scheduler-group
    rayStartParams:
      block: 'true'
      num-cpus: '0'
      num-gpus: '0'
      resources: '"{\"Custom2\": 5}"'
    #pod template
    template:
      spec:
        initContainers:
        # the env var $RAY_IP is set by the operator if missing, with the value of the head service name
        - name: init
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup $RAY_IP.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for K8s Service $RAY_IP; sleep 2; done"]
        containers:
        - name: ray-job-scheduler
          image: test-image
          command: ["sh", "-c"]
          args:
            - |-
              python3 test.py
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","ray stop"]
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "14"
              memory: "50Gi"
            requests:
              cpu: "14"
              memory: "50G"
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Yicheng-Lu-llll** [comment]
Based on my understanding, the reason for the issue is that `python3 test.py` is executed before the `ray start` command. To run a command after `ray start`, you can refer to the [Ray Kubernetes documentation](https://github.com/ray-project/kuberay/blob/master/docs/guidance/pod-command.md) for guidance.


btw, you can use `ray job submit`:
```

ray job submit --address http://localhost:8265 -- python -c '''
import ray

@ray.remote(num_cpus=1)
def run_process():
    print("Process code goes here")

def main():
    ray.get(run_process.remote())

if __name__ == "__main__":
    main()

'''

```

**Comment by shinysingh** [comment]
I also tried submitting a job via the python JobSubmission SDK directly in the head container:
runner.py:
```
import os
from ray.dashboard.modules.job.sdk import JobSubmissionClient

WORKING_DIR = os.getenv("WORKING_DIR", default="/app")
client = JobSubmissionClient("http://127.0.0.1:8265")
client.submit_job(
            # Entrypoint shell command to execute
            entrypoint=f"python3 test.py",
            # Working dir
            runtime_env={
                "working_dir": WORKING_DIR,
            }
        )
```
And using it in the yaml:
```
...
    template:
      spec:
        containers:
        # The Ray head container
        - name: ray-head
          image: test-image
          command: ["sh", "-c"]
          args:
            - |-
              python3 runner.py
...
```

I got the following errors:
``` 
ERROR:ray._private.gcs_utils:Failed to connect to GCS. Please check `gcs_server.out` for more details.
WARNING:ray._private.utils:Unable to connect to GCS at 10.17.1.12:6379. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.
...

File "/usr/local/lib/python3.8/dist-packages/ray/dashboard/modules/job/sdk.py", line 96, in __init__
    api_server_url = get_address_for_submission_client(address)
  File "/usr/local/lib/python3.8/dist-packages/ray/dashboard/utils.py", line 653, in get_address_for_submission_client
    address = ray_address_to_api_server_url(address)
  File "/usr/local/lib/python3.8/dist-packages/ray/dashboard/utils.py", line 605, in ray_address_to_api_server_url
    api_server_url = ray._private.utils.internal_kv_get_with_retry(
  File "/usr/local/lib/python3.8/dist-packages/ray/_private/utils.py", line 1432, in internal_kv_get_with_retry
    raise ConnectionError(
ConnectionError: Could not read 'dashboard' from GCS. Did GCS start successfully?
```
