### ISSUE TITLE
[Bug] Issue where serviceReplica does not run during rayservice deployment

### ISSUE THREAD

**Issue by park12sj** [ray-project/kuberay#1086]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

Others

### What happened + What you expected to happen

- I'd like to know how I can debug the contents below.
  - `kubectl describe rayservice rayservice-model-serving`
    ```
     
    Type    Reason                       Age                   From                   Message
      ----    ------                       ----                  ----                   -------
      Normal  WaitForDashboard             11m (x2 over 11m)     rayservice-controller  Service "rvice-model-serving-raycluster-x68gw-dashboard-svc" not found
      Normal  WaitForServeDeploymentReady  10m (x13 over 11m)    rayservice-controller  Put "http://rvice-model-serving-raycluster-x68gw-dashboard-svc.rayserve.svc.cluster.local:52365/api/serve/deployments/": dial tcp 172.18.42.126:52365: connect: connection refused
      Normal  ServiceNotReady              10m (x5 over 10m)     rayservice-controller  The service is not ready yet. Controller will perform a round of actions in 2s.
      Normal  SubmittedServeDeployment     6m8s (x137 over 10m)  rayservice-controller  Controller sent API request to update Serve deployments on cluster rayservice-model-serving-raycluster-x68gw
      Normal  SubmittedServeDeployment     67s (x74 over 3m37s)  rayservice-controller  Controller sent API request to update Serve deployments on cluster rayservice-model-serving-raycluster-74fzl
    ```
  - ServeController and HTTP ProxyActor are runned, but Serve Replica is not runned.
    ```
    ray           8      1  0 04:08 ?        00:00:02 /home/ray/anaconda3/bin/python /home/ray/anaconda3/bin/ray start --head --dashboard-agent-listen-port=52365 --memory=2147483648 --block -
    ray          15      8  3 04:08 ?        00:00:13 /home/ray/anaconda3/lib/python3.7/site-packages/ray/core/src/ray/gcs/gcs_server --log_dir=/tmp/ray/session_2023-05-12_04-08-45_347946_8/l
    ray          42      8  0 04:08 ?        00:00:01 /home/ray/anaconda3/bin/python -u /home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py --logs-dir=/tmp/ray/
    ray          59      8  0 04:08 ?        00:00:02 /home/ray/anaconda3/bin/python -m ray.util.client.server --address=172.31.249.226:6379 --host=0.0.0.0 --port=10001 --mode=proxy --metrics
    ray          76      8  1 04:08 ?        00:00:03 /home/ray/anaconda3/bin/python /home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/dashboard.py --host=0.0.0.0 --port=8265 --po
    ray         145      8  1 04:08 ?        00:00:05 /home/ray/anaconda3/lib/python3.7/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=/tmp/ray/session_2023-05-12_04-08-45_
    ray         162      8  0 04:08 ?        00:00:03 /home/ray/anaconda3/bin/python -u /home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/log_monitor.py --logs-dir=/tmp/ray/session
    ray         235    145  3 04:08 ?        00:00:13 /home/ray/anaconda3/bin/python -u /home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/agent.py --node-ip-address=172.31.249.226
    ray         290    145  3 04:08 ?        00:00:11 ray::ServeController.listen_for_change
    ray         333    145  1 04:08 ?        00:00:03 ray::HTTPProxyActor
    ray         409      0  0 04:14 pts/0    00:00:00 bash
    ```
  - I can access the dashboard
  ![image](https://github.com/ray-project/kuberay/assets/28818972/b6607e06-45f8-46c0-b2a2-eebb88ab3dcd)

- One of the reasons I suspect is the code below
  ```
      def _load_model(self) -> str:
          working_dir = "/workspace/model"
          svr_path = os.paht.join(working_dir, "LinearSVR_clip2.joblib")
          clip_path = os.paht.join(working_dir, "scoring_clip.pt")
  ```
  - The two files below are those contained in runtimeEnv's working_dir.
  - If the serve code is wrong to refer to the file in the workin_dir, please correct it.
  - Also, even if the issue is correct, please give me a way to debug it (ex) How to view the log)

### Reproduction script

rayservice.yaml
```
# Make sure to increase resource requests and limits before using this example in production.
# For examples with more realistic resource configuration, see
# ray-cluster.complete.large.yaml and
# ray-cluster.autoscaler.large.yaml.
apiVersion: ray.io/v1alpha1
kind: RayService
metadata:
  name: rayservice-model-serving
spec:
  serviceUnhealthySecondThreshold: 300 # Config for the health check threshold for service. Default value is 60.
  deploymentUnhealthySecondThreshold: 300 # Config for the health check threshold for deployments. Default value is 60.
  serveConfig:
    importPath: model:model

    runtimeEnv: |
      working_dir: "FILE:///workspace/model.zip"
    deployments:
      - name: Model
        numReplicas: 1
  rayClusterConfig:
    rayVersion: '2.4.0' # should match the Ray version in the image of the containers
    ######################headGroupSpecs#################################
    # Ray head pod template.
    headGroupSpec:
      serviceType: LoadBalancer # optional
      # the following params are used to complete the ray start: ray start --head --block --redis-port=6379 ...
      rayStartParams:
        port: '6379' # should match container port named gcs-server
        dashboard-host: '0.0.0.0'
        num-cpus: '2' # can be auto-completed from the limits
        block: 'true'
      #pod template
      template:
        spec:
          containers:
            - name: ray-head
              image: {private image}
              resources:
                limits:
                  cpu: 2
                  memory: 2Gi
                requests:
                  cpu: 2
                  memory: 2Gi
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265 # Ray dashboard
                  name: dashboard
                - containerPort: 10001
                  name: client
                - containerPort: 8000
                  name: serve
    workerGroupSpecs:
      # the pod replicas in this group typed worker
      - replicas: 2
        minReplicas: 2
        maxReplicas: 2
        # logical group name, for this called small-group, also can be functional
        groupName: small-group
        rayStartParams:
          block: 'true'
        #pod template
        template:
          spec:
            initContainers:
              # the env var $FQ_RAY_IP is set by the operator if missing, with the value of the head service name
              - name: init
                image: busybox:1.28
                command: ['sh', '-c', "until nslookup $RAY_IP.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for K8s Service $RAY_IP; sleep 2; done"]
            containers:
              - name: ray-worker # must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc'
                image: {private image}
                lifecycle:
                  preStop:
                    exec:
                      command: ["/bin/sh","-c","ray stop"]
                resources:
                  limits:
                    cpu: "1"
                    memory: "1Gi"
                  requests:
                    cpu: "500m"
                    memory: "1Gi"
    headServiceAnnotations: {}
      # annotations passed on for the Head Service
      # service_key: "service_value"

```

```
import pickle
import os
import clip
import joblib
import torch
from ray import serve


@serve.deployment
class Model:
    def __init__(self):
        self._get_device()
        self.model = self._load_model()
        torch.set_num_threads(8)

    def _get_device(self):
        self.device = torch.device(
            "cuda:" + str(current_gpu_id)
            if torch.cuda.is_available() and current_gpu_id is not None
            else "cpu"
        )

    def _load_model(self) -> str:
        working_dir = os.getcwd()
        svr_path = os.paht.join(working_dir, "LinearSVR_clip2.joblib")
        clip_path = os.paht.join(working_dir, "scoring_clip.pt")

        model, _ = clip.load(clip_path, device=self.device)
        self.svr = joblib.load(svr_path)

        return model.visual

    async def __call__(self, input_data):
        input_data = await input_data.body()
        try:
            with torch.no_grad():
                input_tensor = pickle.loads(input_data)
                clip_output = self.model(input_tensor)
                logit = self.svr.predict(clip_output)
                if self.device != "cpu":
                    torch.cuda.empty_cache()
                del input_tensor
                output = logit.item()
                return pickle.dumps(output)
        except Exception as e:
            raise Exception("invalid input tensor", e)


model = Model.bind()

```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by park12sj** [comment]
I changed working_dir as below
```
runtimeEnv: |
      working_dir: "FILE:///workspace/model.zip"
```

However, the following error occurs.
`FileNotFoundError: [Errno 2] No such file or directory: '/workspace/model.zip'`

The container I designated as the image of the header pod has a model.zip.
The controller actor runs on the header pod, but why does the filenotfound error occur for the file that exists on the pod?
Where does the controller read the file when working_dir is specified as FILE uri?
```
(base) ray@0a2664806734:/workspace$ ls
model  model.zip  python
```

**Comment by kevin85421** [comment]
There are some bugs in your Ray Serve script. For example, 

(1) `os.paht` -> `os.path` (?)
(2) `model = Model.bind()` -> `serve.run(Model.bind())` (https://docs.ray.io/en/latest/serve/index.html#quickstart)

You can install a RayCluster and test the Ray Serve script in the cluster.

**Comment by park12sj** [comment]
@kevin85421 

Thank you for your answer. I found number one and fixed it.

This is a question about question number two. The sample code in the rayservice guide also only has a bind, so should serve.run go into the code level?
https://github.com/ray-project/test_dag/blob/master/fruit.py

Also, is there any place where runtime error log is left for code bug like number 1?
I was expecting it to remain in the log of the controller actor or head pod, but I couldn't find it

**Comment by park12sj** [comment]
No. 2 doesn't solve it either. I don't think it's a code problem because it's running well in local, is there a problem with my rayservice settings?
```
(py38) [root@personal-sangjune-0]/workspace/storage/cephrbd/git/pai# /opt/conda/envs/py38/bin/python /workspace/storage/cephrbd/git/pai/ml/ml/serving/model/rayserve/sample/model/scr_v
3_model.py
(py38) [root@personal-sangjune-0]/workspace/storage/cephrbd/git/pai# serve run ml.serving.model.rayserve.sample.model.scr_v3_model:scr_model
2023-05-13 13:39:59,332 INFO scripts.py:380 -- Deploying from import path: "ml.serving.model.rayserve.sample.model.scr_v3_model:scr_model".
2023-05-13 13:40:05,501 INFO worker.py:1616 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265 
(ServeController pid=85643) INFO 2023-05-13 13:40:08,937 controller 85643 deployment_state.py:1168 - Deploying new version of deployment ScrModel.
(HTTPProxyActor pid=85767) INFO:     Started server process [85767]
(ServeController pid=85643) INFO 2023-05-13 13:40:09,016 controller 85643 deployment_state.py:1386 - Adding 1 replica to deployment ScrModel.
(ServeReplica:ScrModel pid=85922) /opt/conda/envs/py38/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator LinearSVR from version 1.1.3 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
(ServeReplica:ScrModel pid=85922) https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
(ServeReplica:ScrModel pid=85922)   warnings.warn(
2023-05-13 13:40:22,005 SUCC scripts.py:398 -- Deployed Serve app successfully.
(ServeReplica:ScrModel pid=85922) INFO 2023-05-13 13:40:52,437 ScrModel ScrModel#bRBSEm olpzdUVkgp // replica.py:527 - __CALL__ OK 666.8ms
(ServeReplica:ScrModel pid=85922) INFO 2023-05-13 13:40:52,900 ScrModel ScrModel#bRBSEm TIKClUPCVL // replica.py:527 - __CALL__ OK 456.7ms
(ServeReplica:ScrModel pid=85922) INFO 2023-05-13 13:40:53,345 ScrModel ScrModel#bRBSEm hIYnrGjDCo // replica.py:527 - __CALL__ OK 435.4ms
(ServeReplica:ScrModel pid=85922) INFO 2023-05-13 13:40:53,764 ScrModel ScrModel#bRBSEm machxBasWs // replica.py:527 - __CALL__ OK 417.4ms
(ServeReplica:ScrModel pid=85922) INFO 2023-05-13 13:40:54,190 ScrModel ScrModel#bRBSEm nyHfRlyJTl // replica.py:527 - __CALL__ OK 424.5ms
(ServeReplica:ScrModel pid=85922) INFO 2023-05-13 13:40:54,596 ScrModel ScrModel#bRBSEm fBvLcbnlnS // replica.py:527 - __CALL__ OK 406.0ms
(ServeReplica:ScrModel pid=85922) INFO 2023-05-13 13:40:55,007 ScrModel ScrModel#bRBSEm ogyjNJOiyC // replica.py:527 - __CALL__ OK 410.2ms
(ServeReplica:ScrModel pid=85922) INFO 2023-05-13 13:40:55,412 ScrModel ScrModel#bRBSEm HopPMXbCJK // replica.py:527 - __CALL__ OK 404.6ms
(ServeReplica:ScrModel pid=85922) INFO 2023-05-13 13:40:55,852 ScrModel ScrModel#bRBSEm sNrkRpsxPW // replica.py:527 - __CALL__ OK 439.4ms
(ServeReplica:ScrModel pid=85922) INFO 2023-05-13 13:40:56,348 ScrModel ScrModel#bRBSEm gaoRazJueB // replica.py:527 - __CALL__ OK 495.4ms
(ServeReplica:ScrModel pid=85922) INFO 2023-05-13 13:40:56,827 ScrModel ScrModel#bRBSEm zgWaljWmOq // replica.py:527 - __CALL__ OK 478.2ms
(ServeReplica:ScrModel pid=85922) INFO 2023-05-13 13:40:57,304 ScrModel ScrModel#bRBSEm FXAqYzEjTv // replica.py:527 - __CALL__ OK 476.9ms
(ServeReplica:ScrModel pid=85922) INFO 2023-05-13 13:40:57,754 ScrModel ScrModel#bRBSEm xDiyEdELbk // replica.py:527 - __CALL__ OK 449.6ms
(ServeReplica:ScrModel pid=85922) INFO 2023-05-13 13:40:58,181 ScrModel ScrModel#bRBSEm cCJyUfMNDN // replica.py:527 - __CALL__ OK 426.1ms
(ServeReplica:ScrModel pid=85922) INFO 2023-05-13 13:40:58,609 ScrModel ScrModel#bRBSEm FknGmfpcgD // replica.py:527 - __CALL__ OK 428.2ms
(ServeReplica:ScrModel pid=85922) INFO 2023-05-13 13:40:59,051 ScrModel ScrModel#bRBSEm rVIHcyIRiF // replica.py:527 - __CALL__ OK 440.7ms
```

There is no additional information in the controller or head pod log, so debugging is difficult, so please let me know if there is a way to see the related log.

**Comment by akshay-anyscale** [comment]
you can check the runtime env logs. I suspect this is because the working directory is set to a local directory instead of a remote URI

**Comment by abhishekchopde** [comment]
@park12sj were you able to resolve the above issue? I am also facing the exact same issue when specified runtime_env as ‘FILE:///path/to/repo.zip’. My controller logs too look similar to yours and I am unable to find anything tangible.

**Comment by sihanwang41** [comment]
Hi 
Ray serve is only supporting remote file in current case. Could you help to file a gh issue for this feature support?

**Comment by park12sj** [comment]
@abhishekchopde

Hello, I read the comments late.
It's not the method suggested in the guide, but it did work as shown below
- Runtime env not specified
  ```
  serveConfig:
      importPath: simple_response.deployment_graph
      deployments:
        - name: SimpleModel
          numReplicas: 1
  ```
- Specify pythonpath
  - dockerfile
    ```
    COPY ./model /workspace/model
    ```
  - reyservice
    ```
    env:
      - name: PYTHONPATH
        value: "/workspace/model"
    ```
- Check the operation
  - head worker ps
    ```
    (base) ray@rayservice-model-serving-raycluster-52txc-head-7vlg8:/workspace$ ps -aux
    USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
    ray           1  0.0  0.0   5868  3544 ?        Ss   23:19   0:00 /bin/bash -lc -- ulimit -n 65536; ray start --head  --dashboard-host=0.0.0.0  --num-cpus=2  --port=6379  --metrics-export-port=8080  --dashboard-agent-listen-port=52365  --memory=2147483648
    ray           7  1.8  0.2 4047028 159212 ?      Sl   23:19   0:01 /home/ray/anaconda3/bin/python /home/ray/anaconda3/bin/ray start --head --dashboard-host=0.0.0.0 --num-cpus=2 --port=6379 --metrics-export-port=8080 --dashboard-agent-listen-port=52365 --me
    ray          38  2.5  0.1 3799968 110304 ?      Sl   23:19   0:01 /home/ray/anaconda3/lib/python3.7/site-packages/ray/core/src/ray/gcs/gcs_server --log_dir=/tmp/ray/session_2023-06-25_23-19-29_785355_7/logs --config_list=eyJvYmplY3Rfc3BpbGxpbmdfY29uZmlnIj
    ray         107  0.6  0.1 2748456 66068 ?       Sl   23:19   0:00 /home/ray/anaconda3/bin/python -u /home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py --logs-dir=/tmp/ray/session_2023-06-25_23-19-29_785355_7/logs --logging-
    ray         172  1.2  0.1 2674800 66304 ?       Sl   23:19   0:00 /home/ray/anaconda3/bin/python -m ray.util.client.server --address=172.16.81.29:6379 --host=0.0.0.0 --port=10001 --mode=proxy --metrics-agent-port=35317
    ray         237  1.3  0.1 3580952 92216 ?       Sl   23:19   0:01 /home/ray/anaconda3/bin/python /home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/dashboard.py --host=0.0.0.0 --port=8265 --port-retries=0 --temp-dir=/tmp/ray --log-dir=/tmp/ray/
    ray         390  1.1  0.0 2932252 27060 ?       Sl   23:19   0:00 /home/ray/anaconda3/lib/python3.7/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=/tmp/ray/session_2023-06-25_23-19-29_785355_7/sockets/raylet --store_socket_name=/tmp/ray
    ray         455  1.2  0.1 2526544 64092 ?       Sl   23:19   0:00 /home/ray/anaconda3/bin/python -u /home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/log_monitor.py --logs-dir=/tmp/ray/session_2023-06-25_23-19-29_785355_7/logs --gcs-address=172
    ray         548  5.9  0.3 6832452 175792 ?      Sl   23:19   0:04 /home/ray/anaconda3/bin/python -u /home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/agent.py --node-ip-address=172.16.81.29 --metrics-export-port=8080 --dashboard-agent-port=353
    ray         731  2.1  0.5 7188280 335996 ?      SNl  23:19   0:01 ray::IDLE
    ray         847  3.3  0.2 5857532 162736 ?      SNl  23:19   0:02 ray::ServeController
    ray         922  1.7  0.2 5341608 160904 ?      SNl  23:19   0:01 ray::HTTPProxyActor
    ray        1466  1.5  0.2 5562320 160312 ?      SNl  23:19   0:01 ray::ServeReplica:SimpleModel
    ray        1547  3.0  0.6 7591756 372832 ?      SNl  23:19   0:01 ray::ServeReplica:DAGDriver
    ray        1628  0.0  0.0   6136  3972 pts/0    Ss   23:20   0:00 bash
    ray        1648  0.0  0.0   7664  3200 pts/0    R+   23:20   0:00 ps -aux
    
    ```
  - curl request result
    ```
    kubectl port-forward service/rayservice-model-serving-serve-svc 8000
    user@AL02367321 kuberay % curl -X GET localhost:8000
    {"test":"success"}%  
    ```

Did you happen to have any other solution?
