### ISSUE TITLE
[Bug]  Has RayJob been tested with Ray workflow?

### ISSUE THREAD

**Issue by dizhouwu** [ray-project/kuberay#1091]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator, Others

### What happened + What you expected to happen

The bug:
I submitted a ray workflow script as a rayjob
Expected Behavior:
I see the workflow run successfully
What I observed:

```
Traceback (most recent call last):
  File "/opt/app-root/bin/sample_ray_workflow.py", line 18, in <module>
    print(f"run workflow: {workflow.run(dag)}")
  File "/opt/app-root/.conda/envs/env/lib/python3.10/site-packages/ray/workflow/api.py", line 161, in run
    run_async(dag, *args, workflow_id=workflow_id, metadata=metadata, **kwargs)
  File "/opt/app-root/.conda/envs/env/lib/python3.10/site-packages/ray/workflow/api.py", line 187, in run_async
    _ensure_workflow_initialized()
  File "/opt/app-root/.conda/envs/env/lib/python3.10/site-packages/ray/workflow/api.py", line 85, in _ensure_workflow_initialized
    init()
  File "/opt/app-root/.conda/envs/env/lib/python3.10/site-packages/ray/workflow/api.py", line 75, in init
    ray.init(storage="file:///tmp/ray/workflow_data")
  File "/opt/app-root/.conda/envs/env/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/opt/app-root/.conda/envs/env/lib/python3.10/site-packages/ray/_private/worker.py", line 1547, in init
    raise ValueError(
ValueError: When connecting to an existing cluster, storage must not be provided.
```

### Reproduction script
```
import ray
from ray import workflow

@ray.remote
def one() -> int:
    return 1

@ray.remote
def add(a: int, b: int) -> int:
    return a + b

dag = add.bind(100, one.bind())


if __name__ == '__main__':
    
    print(f"run workflow: {workflow.run(dag)}")
```
### Anything else
running on kuberay operator 0.5.0
rayjob/cluster config:
```
apiVersion: ray.io/v1alpha1
kind: RayJob
metadata:
  name: rayjob-sample
spec:
  entrypoint: python /opt/app-root/bin/sample_ray_workflow.py
  # runtimeEnv decoded to '{
  #    "pip": [
  #        "requests==2.26.0",
  #        "pendulum==2.1.2"
  #    ],
  #    "env_vars": {
  #        "counter_name": "test_counter"
  #    }
  #}'
  runtimeEnv: ewogICAgInBpcCI6IFsKICAgICAgICAicmVxdWVzdHM9PTIuMjYuMCIsCiAgICAgICAgInBlbmR1bHVtPT0yLjEuMiIKICAgIF0sCiAgICAiZW52X3ZhcnMiOiB7ImNvdW50ZXJfbmFtZSI6ICJ0ZXN0X2NvdW50ZXIifQp9Cg==
  rayClusterSpec:
    rayVersion: '2.4.0' # should match the Ray version in the image of the containers
    # Ray head pod template
    # If enableInTreeAutoscaling is true, the autoscaler sidecar will be added to the Ray head pod.
    # Ray autoscaler integration is supported only for Ray versions >= 1.11.0
    # Ray autoscaler integration is Beta with KubeRay >= 0.3.0 and Ray >= 2.0.0.
    # Ray head pod template
    headGroupSpec:
      serviceType: LoadBalancer # optional
      # the following params are used to complete the ray start: ray start --head --block --port=6379 ...
      rayStartParams:
        # Flag "no-monitor" will be automatically set when autoscaling is enabled.
        dashboard-host: '0.0.0.0'
        block: 'true'
        # num-cpus: '14' # can be auto-completed from the limits
        # Use `resources` to optionally specify custom resource annotations for the Ray node.
        # The value of `resources` is a string-integer mapping.
        # Currently, `resources` must be provided in the specific format demonstrated below:
        # resources: '"{\"Custom1\": 1, \"Custom2\": 5}"'
      #pod template
      template:
        spec:
          containers:
          # The Ray head container
          - name: ray-head
            image: <image>
            imagePullPolicy: Always
            # Optimal resource allocation will depend on your Kubernetes infrastructure and might
            # require some experimentation.
            # Setting requests=limits is recommended with Ray. K8s limits are used for Ray-internal
            # resource accounting. K8s requests are not used by Ray.
            resources:
              limits:
                cpu: 2
                memory: 30Gi
              requests:
                cpu: 2
                memory: 16Gi
            ports:
            - containerPort: 6379
              name: gcs
            - containerPort: 8265
              name: dashboard
            - containerPort: 10001
              name: client
            lifecycle:
              preStop:
                exec:
                  command: ["/bin/sh","-c","ray stop"]
    shutdownAfterJobFinishes: false
  ttlSecondsAfterFinished : 15

```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!
