### ISSUE TITLE
[Feature] Enable Serve through HTTP and gRPC

### ISSUE THREAD

**Issue by roelschr** [ray-project/kuberay#1107]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

It seems that with Ray it's possible to serve the same model with both HTTP and gRPC ingress simultaneously. Unfortunately, that seems to be impossible with Kuberay, given it can only attribute one port for serve (either 8000 or 9000).

### Use case

We have inference endpoints that are consumed both by the client (FE) and other backend services. Internal communication is ideally done via gRPC, thus I would like to serve the same inference pipeline via REST and gRPC.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by roelschr** [comment]
Unfortunately, I don't have any idea how this can be implemented nor enough experience to submit a PR.

**Comment by roelschr** [comment]
With gRPC being fully supported in Serve, this gets some relevance and would unblock the target state we would like to achieve with Ray + Kuberay as our standard Serving framework.

**Comment by kevin85421** [comment]
cc @akshay-anyscale is there any plan for this issue?

**Comment by kevin85421** [comment]
cc @akshay-anyscale @GeneDer. Do we have any plans regarding this issue? @richardsliu has also followed up with me.

**Comment by GeneDer** [comment]
Yes, I will investigate sometime today or tomorrow to see if there are additional work required to enable it on Kuberay

**Comment by GeneDer** [comment]
Just want to share some findings. This is already working as of Ray 2.7.0 released Serve gRPC support. See [this doc](https://docs.ray.io/en/releases-2.7.0/serve/advanced-guides/grpc-guide.html) for how to use it. The user would need to bring their own docker image with the python protobuf artifacts built from `.proto` files. Then they can just start the service like usual. The gRPC service can be reached by opening another port at 9000 (gRPC default on Ray Serve). This is an example yaml I have tested working
```
apiVersion: ray.io/v1alpha1
kind: RayService
metadata:
  name: rayservice-grpc
spec:
  serviceUnhealthySecondThreshold: 900 # Config for the health check threshold for Ray Serve applications. Default value is 900.
  deploymentUnhealthySecondThreshold: 300 # Config for the health check threshold for Ray dashboard agent. Default value is 300.
  serveConfigV2: |
    grpc_options:
      port: 9000
      grpc_servicer_functions:
        - user_defined_protos_pb2_grpc.add_UserDefinedServiceServicer_to_server
        - user_defined_protos_pb2_grpc.add_FruitServiceServicer_to_server
        - user_defined_protos_pb2_grpc.add_ImageClassificationServiceServicer_to_server
    
    applications:
      - name: app1
        route_prefix: /
        import_path: test_deployment_v2:h
        runtime_env: { }
  
      - name: app2
        route_prefix: /foo
        import_path: test_deployment_v2:h2
        runtime_env: { }
  
      - name: app3
        route_prefix: /bar
        import_path: test_deployment_v2:g
        runtime_env: { }
  
      - name: app4
        route_prefix: /baz
        import_path: test_deployment_v2:g2
        runtime_env: { }
  
      - name: app5
        route_prefix: /fastapi
        import_path: test_deployment_v2:app
        runtime_env: { }
  
      - name: app6
        route_prefix: /app6
        import_path: test_deployment_v2:g3
        runtime_env: { }
      
  rayClusterConfig:
    rayVersion: '2.7.0' # should match the Ray version in the image of the containers
    ######################headGroupSpecs#################################
    # Ray head pod template.
    headGroupSpec:
      # The `rayStartParams` are used to configure the `ray start` command.
      # See https://github.com/ray-project/kuberay/blob/master/docs/guidance/rayStartParams.md for the default settings of `rayStartParams` in KubeRay.
      # See https://docs.ray.io/en/latest/cluster/cli.html#ray-start for all available options in `rayStartParams`.
      rayStartParams:
        dashboard-host: '0.0.0.0'
        num-cpus: '10'
      #pod template
      template:
        spec:
          containers:
            - name: ray-head
              image: geneanyscale/gene-test-anyscale:10202023  # <---- Built my own image
              resources:
                limits:
                  cpu: 1
                  memory: 4Gi
                requests:
                  cpu: 1
                  memory: 4Gi
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265 # Ray dashboard
                  name: dashboard
                - containerPort: 10001
                  name: client
                - containerPort: 8000
                  name: serve
                - containerPort: 9000  # <---- Open port 9000 for gRPC
                  name: serve-grpc
    workerGroupSpecs:
      # the pod replicas in this group typed worker
      - replicas: 1
        minReplicas: 1
        maxReplicas: 5
        # logical group name, for this called small-group, also can be functional
        groupName: worker
        # The `rayStartParams` are used to configure the `ray start` command.
        # See https://github.com/ray-project/kuberay/blob/master/docs/guidance/rayStartParams.md for the default settings of `rayStartParams` in KubeRay.
        # See https://docs.ray.io/en/latest/cluster/cli.html#ray-start for all available options in `rayStartParams`.
        rayStartParams: {}
        #pod template
        template:
          spec:
            containers:
              - name: ray-worker # must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc'
                image: geneanyscale/gene-test-anyscale:10202023
                lifecycle:
                  preStop:
                    exec:
                      command: ["/bin/sh","-c","ray stop"]
                resources:
                  limits:
                    cpu: 1
                    memory: 4Gi
                  requests:
                    cpu: 1
                    memory: 4Gi

```
Ray dashboard, HTTP, and gRPC port are all reachable by running `kubectl port-forward --address 0.0.0.0 service/rayservice-grpc-head-svc 8265:8265 8000:8000 9000:9000` after the service is up :) 


The only related change is that we would need to add a health check on gRPC service to ensure it's healthy before setting the pod healthy. But right now there is no way to have gRPC service running without HTTP, so checking HTTP and gRPC is equivalent at the moment. Created this [issue](https://github.com/ray-project/kuberay/issues/1554) to allow checking gRPC health check.
