### ISSUE TITLE
[Bug] GKE CSI Fuse Mounts prevent worker pod creation

### ISSUE THREAD

**Issue by jrosti** [ray-project/kuberay#1130]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

If one defines GKE CSI Fuse mounts to worker Pods, the init container never succeeds and finally fails with:

```
Error: context deadline exceeded
  Warning  Failed     12s                  kubelet            Error: failed to reserve container name "wait-gcs-ready_search...7fb_0": name "wait-gcs-ready_search...7fb_0" is reserved for "df8...d3a"
```

GKE version: v1.26.3-gke.1000

Mount works in head node. 

I believe the root cause is that the   gke-gcsfuse-sidecar container is needed for mounting the CSI fuse volume. It never starts, because it waits "PodInitializing" state. Pod can't initialize because wait-gcs-ready gets a clone of worker's volumemounts, including the fuse mount and combination leads to deadlock. wait-gcs-ready eventually fails with CreateContainerError.

### Reproduction script

Applying following  resource reproduces the issue provided that CSI, bucket and serviceaccount is set up (instructions here: https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/cloud-storage-fuse-csi-driver) 
```
apiVersion: ray.io/v1alpha1
kind: RayCluster
metadata:
  name: fuserepro
spec:
  rayVersion: '2.4.0'
  headGroupSpec:
    serviceType: ClusterIP
    rayStartParams:
      dashboard-host: '0.0.0.0'
      block: 'true'
    template:
      metadata:
        labels: {}
      spec:
        containers:
        - name: ray-head
          image: rayproject/ray:2.4.0
          ports:
          - containerPort: 6379
            name: gcs
          - containerPort: 8265
            name: dashboard
          - containerPort: 10001
            name: client
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","ray stop"]
          volumeMounts:
            - mountPath: /tmp/ray
              name: ray-logs
          resources:
            limits:
              cpu: "2"
              memory: "4G"
            requests:
              cpu: "2"
              memory: "4G"
        volumes:
          - name: ray-logs
            emptyDir: {}
  workerGroupSpecs:
  - replicas: 1
    minReplicas: 1
    maxReplicas: 1
    groupName: cpu1
    rayStartParams:
      block: 'true'
    template:
      metadata:
        annotations:
          gke-gcsfuse/volumes: "true"
      spec:
        terminationGracePeriodSeconds: 60
        serviceAccountName: sa-for-bucket-access
        containers:
        - name: ray-worker
          image: rayproject/ray:2.4.0
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","ray stop"]
          volumeMounts:
            - name: model-storage
              mountPath: /fuse
              readOnly: false
            - mountPath: /tmp/ray
              name: ray-logs
          resources:
            limits:
              cpu: 1
              memory: "2G"
            requests:
              cpu: 1
              memory: "2G"
        initContainers:
        - name: init
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup $RAY_IP.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for K8s Service $RAY_IP; sleep 2; done"]
        volumes:
          - name: model-storage
            csi:
              driver: gcsfuse.csi.storage.gke.io
              readOnly: false
              volumeAttributes:
                bucketName: gcs-bucket
          - name: ray-logs
            emptyDir: {}
```

### Anything else

KubeRay justifies volume copying to initcontainer and wait-gcs-ready as follows. Not sure what would be clean solution to avoid referencing to certain volumes during initialize? 

```
		// This init container requires certain environment variables to establish a secure connection with the Ray head using TLS authentication.
		// Additionally, some of these environment variables may reference files stored in volumes, so we need to include both the `Env` and `VolumeMounts` fields here.
		// For more details, please refer to: https://docs.ray.io/en/latest/ray-core/configure.html#tls-authentication.
		Env:          podTemplate.Spec.Containers[rayContainerIndex].DeepCopy().Env,
		VolumeMounts: podTemplate.Spec.Containers[rayContainerIndex].DeepCopy().VolumeMounts
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!
