### ISSUE TITLE
[Bug] Incorrect reference to headservice in helm-chart templates

### ISSUE THREAD

**Issue by qaz-t** [ray-project/kuberay#1172]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

Others

### What happened + What you expected to happen

In helm-chart/ray-cluster/templates/raycluster-cluster.yaml, the headservice is defined as below
```
  headGroupSpec:
    {{- if .Values.head.headService }}
    headService: {{- toYaml .Values.head.headService | nindent 6 }}
    {{- end }}
```
while in ray-cluster's values.yaml, headService is defined in .Values.service.headService
```
service:
  # This is optional, and the default is ClusterIP.
  type: LoadBalancer
  # Optional, for the user to provide any additional fields to the service.
  # See https://pkg.go.dev/k8s.io/Kubernetes/pkg/api/v1#Service
  headService: {}
```

### Reproduction script

edit values.yaml as below
```
service:
  # This is optional, and the default is ClusterIP.
  type: LoadBalancer
  # Optional, for the user to provide any additional fields to the service.
  # See https://pkg.go.dev/k8s.io/Kubernetes/pkg/api/v1#Service
  headService:
    some_key: some_content
```
run helm template command to rendering the template
```
helm template --debug --dry-run test ray-cluster
```
there is nothing related to headservice

### Anything else

In which field should the headService be placed? Which file shall prevail, values.yaml or templates/raycluster-cluster.yaml

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
