### ISSUE TITLE
[Feature] Specify `RuntimeEnv` in `RayJob` via YAML instead of base64 encoded string

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/kuberay#1195]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Currently, the `RuntimeEnv` field of the `RayJob` spec takes in a base64-encoded string.  

E.g.

```
var testRayJob = &rayv1alpha1.RayJob{
	Spec: rayv1alpha1.RayJobSpec{
		RuntimeEnv: "eyJ0ZXN0IjoidGVzdCJ9", // {"test":"test"} in base64
		[...]
```

This is unreadable. We should allow specifying the `RuntimeEnv` as a JSON string `{"test": "test"}` or as a typed JSON/YAML.

```
  RuntimeEnv:
    WorkingDir: https://github.com/my-project.zip
    EnvVars:
       var: value
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!
