### ISSUE TITLE
[Bug] Unable to correctly specify multiple additional workers with unique groupnames in ray-cluster helm chart

### ISSUE THREAD

**Issue by alagden** [ray-project/kuberay#1215]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

Others

### What happened + What you expected to happen

When trying to specify some additionalWorkerGroups: in a a ray cluster helm chart i could not get the correct syntax to specify more than one, or indeed have a different group name other than "smallGroup" to mach the values.yaml.

Is there a way to specify different and multiple additional group names?

Attempting to run (with attached zip):
`helm install raycluster kuberay/ray-cluster --version 0.5.2 -f raycluster_autoscaling_multi_group.yaml -o yaml --dry-run`

> producedError: INSTALLATION FAILED: YAML parse error on ray-cluster/templates/raycluster-cluster.yaml: error converting YAML to JSON: yaml: line 74: could not find expected ':'

If i remove the 2nd entry and just have one additionalGroup called smallGroup, then it matches the values file entry and succeeds.

### Reproduction script

[raycluster_autoscaling_multi_group.yaml.zip](https://github.com/ray-project/kuberay/files/11923521/raycluster_autoscaling_multi_group.yaml.zip)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by thejamesmarq** [comment]
Just coming across this issue and noting that it still exists in chart version `0.6.0`

**Comment by dmumpuu** [comment]
> Just coming across this issue and noting that the bug still exists in chart versions `0.6.0` and `1.0.0`

Confirm. I have the same issue with `1.0.0` - I can't create an additional worker group with the name different from `smallGroup`

**Comment by piotrzaleckicr** [comment]
I was trying to rename smallGroup to defaultGroup and get the same error. chart version 1.0.0

**Comment by MortalHappiness** [comment]
Closed this issue because it has been fixed in some version between v0.5.2 and v1.2.2

Running `helm install raycluster kuberay/ray-cluster --version 1.2.2 -f raycluster_autoscaling_multi_group.yaml -o yaml --dry-run` with the following yaml does not raise error.

```yaml
image:
  repository: rayproject/ray
  tag: 2.5.0-gpu

common:
  containerEnv: []

head:
  rayVersion: 2.5.0
  enableInTreeAutoscaling: true
  autoscalerOptions:
    #upscalingMode: Default
    idleTimeoutSeconds: 120
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "500m"
      memory: "512Mi"
  nodeSelector:
    controller.nodeSelector.node.kubernetes.io/instance-type: "t3.xlarge"
  containerEnv: []

worker:
  containerEnv: []
  groupName: general
  replicas: 1
  minReplicas: 0
  maxReplicas: 4
  resources:
    limits:
      cpu: "1"
      memory: "2G"
    requests:
      cpu: "1"
      memory: "2G"
  nodeSelector:
    controller.nodeSelector.node.kubernetes.io/instance-type: "t3.xlarge"

additionalWorkerGroups:
  myGPUGroup:
    disabled: false
    containerEnv: []
    replicas: 0
    minReplicas: 0
    maxReplicas: 3
    resources:
      limits:
        cpu: 3
        memory: "14G"
      requests:
        cpu: 3
        memory: "14G"
    nodeSelector:
      controller.nodeSelector.node.kubernetes.io/instance-type: "g4dn.xlarge"

  anotherGPUGroup:
    disabled: false
    containerEnv: []
    replicas: 0
    minReplicas: 0
    maxReplicas: 3
    resources:
      limits:
        cpu: 14
        memory: "54G"
      requests:
        cpu: 14
        memory: "54G"
    nodeSelector:
      controller.nodeSelector.node.kubernetes.io/instance-type: "g4dn.4xlarge"
```
