### ISSUE TITLE
[Bug] [RayServices] HTTPProxyActor restarting while upscaling on AKS

### ISSUE THREAD

**Issue by Rowena2001** [ray-project/kuberay#1222]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

I'm trying to deploy a translator_app on Ray Serve found on the [Ray Serve Get Started page](https://docs.ray.io/en/master/serve/getting_started.html) on AKS with an [autoscaling configuration](https://docs.ray.io/en/master/serve/scaling-and-resource-allocation.html#). To test the autoscaling, I am using kubectl port-forward for the dashboard and service.

`kubectl port-forward --address 0.0.0.0 service/${RAYCLUSTER_NAME}-head-svc 8265:8265`
`kubectl port-forward service/translator-auto-serve-svc 8000`

When I run my multithreaded test queries on localhost:8000, the autoscaling seems to work as more replicas of the Translator deployment are created. However, I sometimes get the following error in the terminal used to port-forward the service (8000):

`E0706 18:17:21.029061  517628 portforward.go:409] an error occurred forwarding 8000 -> 8000: error forwarding port 8000 to pod 9e5b24a9ac50d16d3f56d6807544332db4f023e1399dda763e04abb74f05bd59, uid : failed to execute portforward in network namespace "/var/run/netns/cni-7669e81f-b24a-4f08-3b26-412f2e54fbff": failed to connect to localhost:8000 inside namespace "9e5b24a9ac50d16d3f56d6807544332db4f023e1399dda763e04abb74f05bd59", IPv4: dial tcp4 127.0.0.1:8000: connect: connection refused IPv6 dial tcp6: address localhost: no suitable address found`

As well as the following errors in the terminal used for running my querries:

`('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`
`HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError
('<urllib3.connection.HTTPConnection object at 0x7fba001fdba0>: Failed to establish a new connection: [Errno 111] Connection refused'))`

When monitoring my dashboard, it seems like the HTTPProxyActors restart multiple times when the Translator deployment is upscaling. I'm noticing that when the pods are newly created, there are no errors when running my queries. When I wait for the replicas to downscale, and re-run my queries, the problem emerges as the replicas scale up. The HTTPProxyActors restart up to 200+ times, then the head and worker pods terminate and are replaced by new ones. With the new pods, everything works fine until the deployment downscales back - then the cycle repeats when upscaling.

### Reproduction script

My Kuberay YAML config file is the following:
```
# File name: model_auto_config3.yaml
# This configuration file is used to deploy a Hugging Face model on a Ray cluster on AKS with autoscaling.

apiVersion: ray.io/v1alpha1
kind: RayService
metadata:
  name: translator-auto
spec:
  serviceUnhealthySecondThreshold: 300 # Config for the health check threshold for service. Default value is 60.
  deploymentUnhealthySecondThreshold: 300 # Config for the health check threshold for deployments. Default value is 6
  serveConfig:
    importPath: autoscale1.translator_app
    runtimeEnv: |
      {"working_dir": "https://github.com/Rowena2001/Final_Deployments/archive/refs/tags/1.2.zip", 
      "pip": ["ray[default]", "torch==1.13.1", "transformers==4.30.2", "accelerate==0.20.3"]}
    deployments:
      - name: Translator
        rayActorOptions:
          numCpus: 0.5
  rayClusterConfig:
    # The version of Ray you are using. Make sure all Ray containers are running this version of Ray.
    rayVersion: '2.5.0'
    # If enableInTreeAutoscaling is true, the autoscaler sidecar will be added to the Ray head pod.
    # Ray autoscaler integration is supported only for Ray versions >= 1.11.0
    # Ray autoscaler integration is Beta with KubeRay >= 0.3.0 and Ray >= 2.0.0.
    enableInTreeAutoscaling: true
    # autoscalerOptions is an OPTIONAL field specifying configuration overrides for the Ray autoscaler.
    # The example configuration shown below below represents the DEFAULT values.
    # (You may delete autoscalerOptions if the defaults are suitable.)
    autoscalerOptions:
      # upscalingMode is "Default" or "Aggressive."
      # Conservative: Upscaling is rate-limited; the number of pending worker pods is at most the size of the Ray cluster.
      # Default: Upscaling is not rate-limited.
      # Aggressive: An alias for Default; upscaling is not rate-limited.
      upscalingMode: Default
      # idleTimeoutSeconds is the number of seconds to wait before scaling down a worker pod which is not using Ray resources.
      idleTimeoutSeconds: 60
      # image optionally overrides the autoscaler's container image.
      # If instance.spec.rayVersion is at least "2.0.0", the autoscaler will default to the same image as
      # the ray container. For older Ray versions, the autoscaler will default to using the Ray 2.0.0 image.
      ## image: "my-repo/my-custom-autoscaler-image:tag"
      # imagePullPolicy optionally overrides the autoscaler container's default image pull policy (IfNotPresent).
      imagePullPolicy: IfNotPresent
      # Optionally specify the autoscaler container's securityContext.
      securityContext: {}
      env: []
      envFrom: []
      # resources specifies optional resource request and limit overrides for the autoscaler container.
      # The default autoscaler resource limits and requests should be sufficient for production use-cases.
      # However, for large Ray clusters, we recommend monitoring container resource usage to determine if overriding the defaults is required.
      resources:
        limits:
          cpu: "900m"
          memory: "1000Mi"
        requests:
          cpu: "900m"
          memory: "1000Mi"
    # Ray head pod template
    headGroupSpec:
      serviceType: ClusterIP # optional
      # the following params are used to complete the ray start: ray start --head --block ...
      rayStartParams:
        dashboard-host: '0.0.0.0'
      #pod template
      template:
        spec:
          containers:
          # The Ray head container
          - name: ray-head
            image: rayproject/ray:2.5.0
            ports:
              - containerPort: 6379
                name: gcs-server
              - containerPort: 8265 # Ray dashboard
                name: dashboard
              - containerPort: 10001
                name: client
              - containerPort: 8000
                name: serve
            lifecycle:
              preStop:
                exec:
                  command: ["/bin/sh","-c","ray stop"]
            resources:
              limits:
                cpu: "3"
                memory: "2.5G"
              requests:
                cpu: "500m"
                memory: "2G"
          # tolerations are used to schedule pods if the node has the matching taints (i.e. AKS nodepool taints)
          tolerations:
            - effect: NoSchedule
              key: sku
              value: gpu
              operator: Equal
    workerGroupSpecs:
    # the pod replicas in this group typed worker
    - replicas: 2
      minReplicas: 2
      maxReplicas: 10
      # logical group name, for this called small-group, also can be functional
      groupName: small-group
      rayStartParams: {}
      template:
        spec:
          containers:
          - name: ray-worker
            image: rayproject/ray:2.5.0
            lifecycle:
              preStop:
                exec:
                  command: ["/bin/sh","-c","ray stop"]
            resources:
              limits:
                cpu: "2"
                memory: "2G"
              requests:
                cpu: "500m"
                memory: "1G"
          # tolerations are used to schedule pods if the node has the matching taints (i.e. AKS nodepool taints)
          tolerations:
            - effect: NoSchedule
              key: sku
              value: gpu
              operator: Equal
```

My python file is the following:
```
# file name: autoscale1.py
# This file deploys a translator application.
# The translator application uses a pre-trained model from the transformers library.

from starlette.requests import Request

from ray import serve

from transformers import pipeline

# Creates a Ray Serve deployment for a translator application.
# It specifies that the deployment should use 0.2 CPU cores.
# Refer to https://docs.ray.io/en/latest/serve/scaling-and-resource-allocation.html# for more information.
@serve.deployment(
    autoscaling_config={
        "min_replicas": 1,
        "initial_replicas": 2,
        "max_replicas": 10,
        "target_num_ongoing_requests_per_replica": 8,
        "upscale_delay_s": 5,
        "smoothing_factor": 1.5
    }
)
class Translator:
    def __init__(self):
        # Load model
        self.model = pipeline("translation_en_to_fr", model="t5-small")

    def translate(self, text: str) -> str:
        # Run inference
        model_output = self.model(text)

        # Post-process output to return only the translation text
        translation = model_output[0]["translation_text"]

        return translation

    # Asynchronously calls the translate function.
    async def __call__(self, http_request: Request) -> str:
        english_text: str = await http_request.json()
        translation = self.translate(english_text)
        return translation

# Binds the translator application and the driver to the same deployment.
translator_app = Translator.bind()
```

I created my test queries using [WRITING FAST ASYNC HTTP REQUESTS IN PYTHON - Gen 2](https://blog.jonlu.ca/posts/async-python-http) as I'm new to multithreading in Python. 

```
# file name: worker_threadpool.py
from queue import Queue

from threading import Thread


class Worker(Thread):
  """ Thread executing tasks from a given tasks queue """

  def __init__(self, tasks):
    Thread.__init__(self)
    self.tasks = tasks
    self.daemon = True
    self.start()

  def run(self):
    while True:
      func, args, kargs = self.tasks.get()
      try:
        func(*args, **kargs)
      except Exception as e:
        # An exception happened in this thread
        print(e)
      finally:
        # Mark this task as done, whether an exception happened or not
        self.tasks.task_done()


class ThreadPool:
  """ Pool of threads consuming tasks from a queue """

  def __init__(self, num_threads):
    self.tasks = Queue(num_threads)
    for _ in range(num_threads):
      Worker(self.tasks)

  def add_task(self, func, *args, **kargs):
    """ Add a task to the queue """
    self.tasks.put((func, args, kargs))

  def map(self, func, args_list):
    """ Add a list of tasks to the queue """
    for args in args_list:
      self.add_task(func, args)

  def wait_completion(self):
    """ Wait for completion of all the tasks in the queue """
    self.tasks.join()
```
```
# file name: autoscale_client.py
from queue import Queue
import requests
from threading import Thread
import time
from worker_threadpool import Worker, ThreadPool

start_time = time.time()
lines = [open("queries.txt", "r").readlines()][0]
pool = ThreadPool(40)

f = open("queries.txt", "r")

def post(line):
    r = requests.post("http://127.0.0.1:8000/", json=line)
    print(r.text)

pool.map(post, lines)
pool.wait_completion()

print("--- %s seconds ---" % (time.time() - start_time))
```
And this is my queries.txt:
```
The sun is shining brightly.
Cats are adorable creatures.
Books are a gateway to different worlds.
Water is essential for life.
The bird is soaring high above.
Dreams can inspire us to achieve.
Coffee is my morning elixir.
Time flies when you're having fun.
Laughter is the best medicine.
Music brings joy to my soul.
Learning never stops.
Happiness comes from within.
Rainbows are a beautiful sight.
Nature is full of wonders.
Patience is a virtue.
Kindness matters.
The ocean is vast and mysterious.
Butterflies are captivating creatures.
Art is a form of expression.
Adventure awaits around every corner.
Friendship is a precious gift.
Chocolate is irresistible.
Imagination has no limits.
Smiles are contagious.
Success comes with hard work.
Love conquers all.
Stars illuminate the night sky.
Silence can be golden.
Wisdom comes with experience.
Forgiveness heals wounds.
Dancing brings freedom.
Goals drive us forward.
Rain refreshes the earth.
Courage overcomes fear.
Science unlocks mysteries.
Inspiration sparks creativity.
Family provides unconditional love.
Mountains stand tall and majestic.
Dreams can become reality.
Artistic expression knows no boundaries.
Knowledge empowers us.
Honesty builds trust.
Kindness is a language everyone understands.
Challenges make us stronger.
Sunsets paint the sky with vibrant colors.
Memories last a lifetime.
Education opens doors to opportunity.
Birds sing melodies of nature.
Laughter brings people together.
Home is where the heart is.
Determination leads to success.
Compassion transforms lives.
Birds build intricate nests.
Imagination fuels innovation.
Beauty is found in the simplest things.
Joy is contagious.
Time spent with loved ones is priceless.
Reflection brings self-awareness.
Dreams inspire action.
Learning is a lifelong journey.
Kindness is never wasted.
Courageous acts leave a lasting impact.
Music transcends language barriers.
Gratitude opens doors to abundance.
Friendship enriches our lives.
Trees provide shade and oxygen.
Laughter is good for the soul.
Curiosity sparks discovery.
Teamwork achieves great things.
Sunflowers follow the sun's path.
Inspiration can be found everywhere.
Honesty breeds trust.
Self-care is essential for well-being.
Adventure fuels the spirit.
Challenges create opportunities for growth.
Rain cleanses the earth.
Compassion changes lives.
Dreams give us hope.
Success is a result of perseverance.
Nature's beauty is awe-inspiring.
Love knows no boundaries.
Creativity fuels innovation.
Books expand our horizons.
Friendship brings joy and support.
Laughter lightens the heart.
Resilience overcomes obstacles.
Dreams are the seeds of achievement.
Music lifts the soul.
Kindness is a gift we can all give.
Memories shape who we are.
Education is a lifelong pursuit.
Sunsets create breathtaking moments.
Curiosity leads to knowledge.
Inspiration drives progress.
Honesty is the foundation of trust.
Self-reflection fosters personal growth.
Dreams fuel ambition.
Beauty is found in diversity.
Love brings warmth to the heart.
Life is a precious gift.
I have a dream that one day this nation will rise up and live out the true meaning of its creed: 'We hold these truths to be self-evident, that all men are created equal.'
I have a dream that one day on the red hills of Georgia, the sons of former slaves and the sons of former slave owners will be able to sit down together at the table of brotherhood.
I have a dream that one day even the state of Mississippi, a state sweltering with the heat of injustice, sweltering with the heat of oppression, will be transformed into an oasis of freedom and justice.
I have a dream that my four little children will one day live in a nation where they will not be judged by the color of their skin but by the content of their character.
I have a dream today!
I have a dream that one day, down in Alabama, with its vicious racists, with its governor having his lips dripping with the words of 'interposition' and 'nullification,' one day right there in Alabama, little black boys and black girls will be able to join hands with little white boys and white girls as sisters and brothers.
I have a dream today!
I have a dream that one day every valley shall be exalted, every hill and mountain shall be made low, the rough places will be made plain, and the crooked places will be made straight, and the glory of the Lord shall be revealed, and all flesh shall see it together.
This is our hope, and this is the faith that I go back to the South with.
With this faith, we will be able to hew out of the mountain of despair a stone of hope.
With this faith, we will be able to transform the jangling discords of our nation into a beautiful symphony of brotherhood.
With this faith, we will be able to work together, to pray together, to struggle together, to go to jail together, to stand up for freedom together, knowing that we will be free one day.
This will be the day when all of God's children will be able to sing with a new meaning, 'My country, 'tis of thee, sweet land of liberty, of thee I sing. Land where my fathers died, land of the pilgrim's pride, from every mountainside, let freedom ring.'
And if America is to be a great nation, this must become true.
So let freedom ring from the prodigious hilltops of New Hampshire.
Let freedom ring from the mighty mountains of New York.
Let freedom ring from the heightening Alleghenies of Pennsylvania.
Let freedom ring from the snow-capped Rockies of Colorado.
Let freedom ring from the curvaceous slopes of California.
But not only that:
Let freedom ring from Stone Mountain of Georgia.
Let freedom ring from Lookout Mountain of Tennessee.
Let freedom ring from every hill and molehill of Mississippi.
From every mountainside, let freedom ring.
And when this happens, when we allow freedom to ring, when we let it ring from every village and every hamlet, from every state and every city, we will be able to speed up that day when all of God's children, black men and white men, Jews and Gentiles, Protestants and Catholics, will be able to join hands and sing in the words of the old Negro spiritual:
'Free at last! Free at last! Thank God Almighty, we are free at last!'
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
