### ISSUE TITLE
[Feature] Avoid manually importing Grafana dashboard JSON file

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#1285]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

In #1278, we ask users to import the JSON file `default_grafana_dashboard.json` file from the `/tmp/ray/session_latest/metrics/grafana/dashboards/` in the head Pod to Grafana.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
cc @alanwguo is there any pointer to create a dashboard in Grafana for a Ray cluster in the Ray dashboard initialization process?

**Comment by hongbo-miao** [comment]
Hi @kevin85421 here is the way I use. Hopefully it can help some people who have the same question.

I installed my Grafana by this Helm Chart: https://github.com/grafana/helm-charts/tree/main/charts/grafana

So to auto install Ray dashboards, you can add

- https://github.com/hongbo-miao/hongbomiao.com/blob/6240d984938b78d2c92d02cfe748ef3749e102f6/kubernetes/argo-cd/applications/production-hm/grafana/argo-cd-manifests/hm-grafana-application.yaml#L53-L60
- https://github.com/hongbo-miao/hongbomiao.com/blob/6240d984938b78d2c92d02cfe748ef3749e102f6/kubernetes/argo-cd/applications/production-hm/grafana/argo-cd-manifests/hm-grafana-application.yaml#L75-L83

which is

```yaml
# ...
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: ray-dashboards
        orgId: 1
        folder: Ray
        type: file
        disableDeletion: true
        editable: false
        options:
          path: /var/lib/grafana/dashboards/ray-dashboards
dashboards:
  ray-dashboards:
    ray-data-grafana-dashboard:
      url: https://raw.githubusercontent.com/ray-project/kuberay/refs/heads/master/config/grafana/data_grafana_dashboard.json
    ray-default-grafana-dashboard:
      url: https://raw.githubusercontent.com/ray-project/kuberay/refs/heads/master/config/grafana/default_grafana_dashboard.json
    ray-serve-deployment-grafana-dashboard:
      url: https://raw.githubusercontent.com/ray-project/kuberay/refs/heads/master/config/grafana/serve_deployment_grafana_dashboard.json
    ray-serve-grafana-dashboard:
      url: https://raw.githubusercontent.com/ray-project/kuberay/refs/heads/master/config/grafana/serve_grafana_dashboard.json
```
