### ISSUE TITLE
[Bug] [RayService] KubeRay does not handle voluntary disruptions well

### ISSUE THREAD

**Issue by smit-kiri** [ray-project/kuberay#1333]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

When trying to [safely drain a kubernetes node](https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/) using the `kubectl drain` [command](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#drain), there is a downtime until a new node spins up. 

This prohibits us to voluntarily take down nodes for maintenance like applying security patches. Kubernetes has [a well defined process](https://kubernetes.io/docs/concepts/workloads/pods/disruptions/) to deal with disruptions like this.

This affects high availability for our applications, since we routinely cycle our nodes for various reasons.

### Reproduction script

<details>
  <summary>
    demo.py
  </summary>

```python
from ray import serve


@serve.deployment(name="model1")
class Model1:
    def __int__(self):
        # Simulate a long init method
        from sentence_transformers import SentenceTransformer

        self.model = SentenceTransformer("paraphrase-multilingual-mpnet-base-v2 ")

    async def __call__(self, http_request):
        data: dict = await http_request.json()
        data["model"] = "model1"
        return data


model1 = Model1.bind()  # type: ignore
```

</details>

<details>
  <summary>
    demo2.py
  </summary>

```python
from ray import serve


@serve.deployment(name="model2")
class Model2:
    def __int__(self):
        # Simulate a long init method
        from sentence_transformers import SentenceTransformer

        self.model = SentenceTransformer("paraphrase-multilingual-mpnet-base-v2 ")

    async def __call__(self, http_request):
        data: dict = await http_request.json()
        data["model"] = "model2"
        return data


model2 = Model2.bind()  # type: ignore
```
</details>

<details>
  <summary>
    Dockerfile
  </summary>

```Dockerfile
FROM rayproject/ray:2.6.1-py310 as common

ENV WORKING_DIR /home/ray/models

WORKDIR ${WORKING_DIR}

ADD ./demo.py ${WORKING_DIR}
ADD ./demo2.py ${WORKING_DIR}
```

</details>

<details>
  <summary>
    rayservice_config.yaml
  </summary>

```yaml
apiVersion: ray.io/v1alpha1
kind: RayService
metadata:
  name: rayservice-sample
  annotations:
    ray.io/ft-enabled: "true"
spec:
  serviceUnhealthySecondThreshold: 900 # Config for the health check threshold for service. Default value is 60.
  deploymentUnhealthySecondThreshold: 900 # Config for the health check threshold for deployments. Default value is 60.
  serveConfigV2: |
    applications:
      - name: app1
        route_prefix: "/model1"
        import_path: "demo:model1"
        runtime_env:
          pip:
            - sentence-transformers==2.2.2
        deployments:
          - name: "model1"
            num_replicas: 1
            ray_actor_options:
              num_cpus: 2
    
      - name: app2
        route_prefix: "/model2"
        import_path: "demo2:model2"
        runtime_env:
          pip:
            - sentence-transformers==2.2.2
        deployments:
          - name: "model2"
            num_replicas: 1
            ray_actor_options:
              num_cpus: 2

  rayClusterConfig:
    rayVersion: 2.6.1   # should match the Ray version in the image of the containers
    enableInTreeAutoscaling: true
    ######################headGroupSpecs################################
    # Ray head pod template.
    headGroupSpec:
      # the following params are used to complete the ray start: ray start --head --block --redis-port=6379 ...
      rayStartParams:
        port: '6379' # should match container port named gcs-server
        dashboard-host: 0.0.0.0
      #pod template
      template:
        spec:
          serviceAccountName: rayserve
          containers:
          - name: ray-head
            image: DOCKER_IMAGE_URL
            imagePullPolicy: Always
            env:
            - name: RAY_LOG_TO_STDERR
              value: "1"
            - name: RAY_REDIS_ADDRESS
              value: redis://xxxx.use1.cache.amazonaws.com:6379
            resources:
              limits:
                cpu: 2
                memory: 8Gi
              requests:
                cpu: 2
                memory: 8Gi
            ports:
            - containerPort: 6379
              name: gcs-server
            - containerPort: 8265     # Ray dashboard
              name: dashboard
            - containerPort: 10001
              name: client
            - containerPort: 8000
              name: serve
    workerGroupSpecs:
      # the pod replicas in this group typed worker
    - replicas: 1
      minReplicas: 1
      maxReplicas: 15
        # logical group name, for this called small-group, also can be functional
      groupName: small-group
      rayStartParams: {}
        #pod template
      template:
        spec:
          serviceAccountName: rayserve
          containers:
          - name: ray-worker     # must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc'
            image: DOCKER_IMAGE_URL
            imagePullPolicy: Always
            lifecycle:
              preStop:
                exec:
                  command: [/bin/sh, -c, ray stop]
            resources:
              limits:
                cpu: 2
                memory: 8Gi
              requests:
                cpu: 2
                memory: 8Gi
```

</details>

<details>
  <summary>
    health_check.py
  </summary>

```python
import datetime
import time

import requests


def _get_current_time():
    return datetime.datetime.now().strftime("%d.%b %Y %H:%M:%S")


def check_health():
    response = requests.get("http://127.0.0.1:52365/api/serve/applications/")
    application_info = response.json()

    # Check health for all deployments
    for app_name, app_info in application_info["applications"].items():
        deployments = app_info["deployments"]
        for _, deployment_info in deployments.items():
            deployment_status = deployment_info["status"]
            deployment_name = deployment_info["name"]

            print(f"[{_get_current_time()}] {deployment_name}: {str(deployment_status)}")


if __name__ == "__main__":
    while True:
        check_health()
        time.sleep(5)
```

</details>

Reproduction steps:

- Build the docker image, and deploy the `rayservice_config.yaml`. Make sure to tweak the CPU requirements so that each deployment's `num_cpus` is equal to head / worker's CPU limits. This is to make sure only one app is running on a worker pod. Wait for both apps to be healthy.

- Run the `health_check.py` script which will print out deployment health every 5 seconds.

- Check the node of the worker using `kubectl get pods -o wide`. 

- Run `kubectl drain node_name --ignore-daemonsets` to drain the node.

- You will notice that one of the deployment becomes unhealthy for some time until a new pod spins up.

### Anything else

This will happen every time we drain a node. To avoid this, the only option is to make sure there are deployment replicas running on a different node, and then drain the node.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
