### ISSUE TITLE
[Question] How to choose a worker group

### ISSUE THREAD

**Issue by vilsonrodrigues** [ray-project/kuberay#1430]
The documentation mentions the possibility of me having more than one WorkerGroup. What is the correct way to tell Ray that I want to run in the 'gpu-group' as in the following example?

``` yaml
workerGroupSpecs:
  - groupName: small-group
    replicas: 1
    minReplicas: 1
    maxReplicas: 5
    rayStartParams:
        ...
    template: # Pod template
      spec:
        ...
  # Another workerGroup
  - groupName: medium-group
    ...
  # Yet another workerGroup, with access to special hardware perhaps.
  - groupName: gpu-group
    ...
```
