### ISSUE TITLE
[Bug]  Job CRD status not updated upon job completion

### ISSUE THREAD

**Issue by z103cb** [ray-project/kuberay#1478]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

When submitting a KubeRay job (ray job CRD) to be executed on a previously provisioned cluster, the ray job status is not set to [v1alpha1.JobStatusSucceeded](https://github.com/z103cb/kuberay/blob/a4e36c63a2d32ea3efeb9a56d5b65cdae2401a92/ray-operator/apis/ray/v1alpha1/rayjob_types.go#L19).

The underlying `batchv1.Job` status is completed.

### Reproduction script

To reproduce the issue:
1. Create k8s cluster
2. Deploy operator (v1.0.0-rc.0+) in default namespace
3. Create `ray-system` namespace: `kubectl create namespace ray-system`
4. Create a KubeRay cluster: kubectl apply -f [cluster.yaml.txt](https://github.com/ray-project/kuberay/files/12866019/cluster.yaml.txt)
5. Wait for cluster to be up an running
6. Create a KubeRay Job: kubectl apply -f [job.yaml.txt](https://github.com/ray-project/kuberay/files/12866095/job.yaml.txt)
7. Watch the job which doesn't have its status updated.

The job `batchv1.Job` has a status of 
```yaml
status:
  completionTime: "2023-10-11T06:56:19Z"
  conditions:
  - lastProbeTime: "2023-10-11T06:56:19Z"
    lastTransitionTime: "2023-10-11T06:56:19Z"
    status: "True"
    type: Complete
  startTime: "2023-10-11T06:55:46Z"
  succeeded: 1
```

Also, deleting the ray job doesn't delete the associated `batchv1.Job`
```sh
kubectl delete rayjob -n ray-system sample-job
# rayjob.ray.io "sample-job" deleted
kubectl get job -n ray-system sample-job

# NAME         COMPLETIONS   DURATION   AGE
# sample-job   1/1           33s        28m
```

### Anything else

Fairly consistent.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
