### ISSUE TITLE
[Bug] RayJob hang with incorrect status when head pod restarts

### ISSUE THREAD

**Issue by shaowei-su** [ray-project/kuberay#1489]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

1. The Bug

When head pod got deleted/preempted, job submitter pod will fail instantly and RayJob status got updated to `jobStatus: RUNNING, jobDeploymentStatus: FailedToGetJobStatus`. Despite the subsequent restart of head pod, the entire RayJob will hang up without: 1. worker pod rejoining the RayCluster; 2. spin up a new job submitter pod.

2. Expected Behavior

Fail the RayJob in the case of head pod failure; or restart the submission process.

3. Status log
```
status:
  dashboardURL: [...]
  jobDeploymentStatus: FailedToGetJobStatus
  jobId: rayjob-048a1172-6935-11ee-8d78-0e2269d24ab9-g8j5r
  jobStatus: RUNNING
  message: Job is currently running.
  observedGeneration: 2
  rayClusterName: rayjob-048a1172-6935-11ee-8d78-0e2269d24ab9-raycluster-lcxwm
  rayClusterStatus:
    availableWorkerReplicas: 2
    desiredWorkerReplicas: 2
    endpoints:
      client: "10001"
      dashboard: "8265"
      metrics: "8080"
      redis: "6379"
      serve: "8000"
    head:
      podIP: 100.119.93.22
      serviceIP: 100.124.30.136
    lastUpdateTime: "2023-10-12T19:39:45Z"
    maxWorkerReplicas: 2
    minWorkerReplicas: 2
    observedGeneration: 1
    reason: head pod r935-11ee-8d78-0e2269d24ab9-raycluster-lcxwm-head-8ftlx is not
      running nor pending
    state: ready
  startTime: "2023-10-12T19:33:06Z"
```

### Reproduction script

Start a RayJob with any workloads and run `kubectl delete pods [HEAD-POD]` before the task completes. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
