### ISSUE TITLE
[Bug] RayJob Volcano integration

### ISSUE THREAD

**Issue by zhiyi57** [ray-project/kuberay#1580]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

When label RayJob with volcano scheduler and queue，ray operator crashes. Raycluster object would be created with no status. None of relevant cluster pod would be created. Rayjob is the sample job provided in[ examples](https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/ray_v1alpha1_rayjob.yaml).  This happens in both v.0.6.0 and v.1.0.0
Tried same setup for RayCluster, everything works as expected.

The log from ray operator is the following:
```
INFO    controllers.RayCluster  reconcileHeadService    {"1 head service found": "rayjob-sample-raycluster-klhw9-head-svc"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13ad868]

goroutine 786 [running]:
github.com/ray-project/kuberay/ray-operator/controllers/ray/batchscheduler/volcano.(*VolcanoBatchScheduler).DoBatchSchedulingOnSubmission(0xc001758368?, 0xc008176500)
        /workspace/controllers/ray/batchscheduler/volcano/volcano_scheduler.go:55 +0xe8
github.com/ray-project/kuberay/ray-operator/controllers/ray.(*RayClusterReconciler).reconcilePods(0xc0003054f0, {0x194d558, 0xc008536ed0}, 0xc008176500)
        /workspace/controllers/ray/raycluster_controller.go:550 +0x23f
github.com/ray-project/kuberay/ray-operator/controllers/ray.(*RayClusterReconciler).rayClusterReconcile(0xc0003054f0, {0x194d558, 0xc008536ed0}, {{{0xc00812ee68, 0x8}, {0xc00814ab00, 0x1e}}}, 0xc008176500)
        /workspace/controllers/ray/raycluster_controller.go:340 +0xea8
github.com/ray-project/kuberay/ray-operator/controllers/ray.(*RayClusterReconciler).Reconcile(0xc0003054f0, {0x194d558, 0xc008536ed0}, {{{0xc00812ee68, 0x8}, {0xc00814ab00, 0x1e}}})
        /workspace/controllers/ray/raycluster_controller.go:158 +0x21e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc00025edc0, {0x194d558, 0xc008536e10}, {{{0xc00812ee68?, 0x163d900?}, {0xc00814ab00?, 0x4045d4?}}})
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114 +0x28b
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00025edc0, {0x194d4b0, 0xc000d2f040}, {0x158c6a0?, 0xc006dccf00?})
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311 +0x352
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00025edc0, {0x194d4b0, 0xc000d2f040})
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:223 +0x31c
Reproduced steadily. Volcano works fine with RayCluster, it’s only problematic with RayJob.  (both v.6.0.0 and V.1.0.0) 
```

### Reproduction script

apiVersion: ray.io/v1alpha1
kind: RayJob
metadata:
  name: rayjob-sample
  labels:
    ray.io/scheduler-name: volcano
    volcano.sh/queue-name: kuberay-test-queue
...

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zhiyi57** [comment]
@Jeffwan FYI

**Comment by architkulkarni** [comment]
@zhiyi57 
> The immediate fix is pretty trivial

What fix is this? Would you be willing to open a PR with the fix?

**Comment by zhiyi57** [comment]
> @zhiyi57
> 
> > The immediate fix is pretty trivial
> 
> What fix is this? Would you be willing to open a PR with the fix?

The basic fix is to check whether this filled is set or not before use it.
A better fix would be set default value on initialization. Not sure whether we would want a pr down on this road though.

**Comment by hylent** [comment]
Any updates of this issue?

**Comment by kevin85421** [comment]
cc @win5923 are you interested in this issue? Thanks!

**Comment by win5923** [comment]
Sure.

**Comment by win5923** [comment]
I can't reproduct this with `kuberay-operator` 1.4.2 and `volcano` 1.12.1. I think this is fixed now. 

I followed the steps from the Ray docs for [KubeRay integration with Volcano](https://docs.ray.io/en/latest/cluster/kubernetes/k8s-ecosystem/volcano.html), the only change I made was combining [ray-cluster.volcano-scheduler-queue.yaml](https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/ray-cluster.volcano-scheduler-queue.yaml) and [ray-job.sample.yaml](https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/ray-job.sample.yaml).
Steps:

1. Install Volcano
```
$ helm install volcano volcano-sh/volcano --version 1.12.1 -n volcano-system --create-namespace
```
2. Install the KubeRay Operator with batch scheduling
```
$ helm install kuberay-operator kuberay/kuberay-operator --version 1.4.2 --set batchScheduler.name=volcano
```
3. Create a queue with a capacity of 4 CPUs and 6Gi of RAM
```
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: kuberay-test-queue
spec:
  weight: 1
  capability:
    cpu: 4
    memory: 6Gi
```
4.  Create a RayJob with a head node (1 CPU + 2Gi of RAM) and two workers (1 CPU + 1Gi of RAM each), for a total of 3 CPU and 4Gi of RAM, and add the `Volcano` labels. This is from https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/ray-job.sample.yaml
```yaml
apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: rayjob-sample
  labels:
    ray.io/scheduler-name: volcano
    volcano.sh/queue-name: kuberay-test-queue
spec:
  # submissionMode specifies how RayJob submits the Ray job to the RayCluster.
  # The default value is "K8sJobMode", meaning RayJob will submit the Ray job via a submitter Kubernetes Job.
  # The alternative value is "HTTPMode", indicating that KubeRay will submit the Ray job by sending an HTTP request to the RayCluster.
  # submissionMode: "K8sJobMode"
  entrypoint: python /home/ray/samples/sample_code.py
  # shutdownAfterJobFinishes specifies whether the RayCluster should be deleted after the RayJob finishes. Default is false.
  # shutdownAfterJobFinishes: false

  # ttlSecondsAfterFinished specifies the number of seconds after which the RayCluster will be deleted after the RayJob finishes.
  # ttlSecondsAfterFinished: 10

  # activeDeadlineSeconds is the duration in seconds that the RayJob may be active before
  # KubeRay actively tries to terminate the RayJob; value must be positive integer.
  # activeDeadlineSeconds: 120

  # RuntimeEnvYAML represents the runtime environment configuration provided as a multi-line YAML string.
  # See https://docs.ray.io/en/latest/ray-core/handling-dependencies.html for details.
  # (New in KubeRay version 1.0.)
  runtimeEnvYAML: |
    pip:
      - requests==2.26.0
      - pendulum==2.1.2
    env_vars:
      counter_name: "test_counter"

  # Suspend specifies whether the RayJob controller should create a RayCluster instance.
  # If a job is applied with the suspend field set to true, the RayCluster will not be created and we will wait for the transition to false.
  # If the RayCluster is already created, it will be deleted. In the case of transition to false, a new RayCluster will be created.
  # suspend: false

  # rayClusterSpec specifies the RayCluster instance to be created by the RayJob controller.
  rayClusterSpec:
    rayVersion: '2.46.0' # should match the Ray version in the image of the containers
    # Ray head pod template
    headGroupSpec:
      # The `rayStartParams` are used to configure the `ray start` command.
      # See https://github.com/ray-project/kuberay/blob/master/docs/guidance/rayStartParams.md for the default settings of `rayStartParams` in KubeRay.
      # See https://docs.ray.io/en/latest/cluster/cli.html#ray-start for all available options in `rayStartParams`.
      rayStartParams: {}
      #pod template
      template:
        spec:
          containers:
          - name: ray-head
            image: rayproject/ray:2.46.0
            ports:
            - containerPort: 6379
              name: gcs-server
            - containerPort: 8265 # Ray dashboard
              name: dashboard
            - containerPort: 10001
              name: client
            resources:
              limits:
                cpu: "1"
                memory: "2Gi"
              requests:
                cpu: "1"
                memory: "2Gi"
            volumeMounts:
            - mountPath: /home/ray/samples
              name: code-sample
          volumes:
          # You set volumes at the Pod level, then mount them into containers inside that Pod
          - name: code-sample
            configMap:
              # Provide the name of the ConfigMap you want to mount.
              name: ray-job-code-sample
              # An array of keys from the ConfigMap to create as files
              items:
              - key: sample_code.py
                path: sample_code.py
    workerGroupSpecs:
    # the pod replicas in this group typed worker
    - replicas: 2
      minReplicas: 2
      maxReplicas: 2
      # logical group name, for this called small-group, also can be functional
      groupName: small-group
      # The `rayStartParams` are used to configure the `ray start` command.
      # See https://github.com/ray-project/kuberay/blob/master/docs/guidance/rayStartParams.md for the default settings of `rayStartParams` in KubeRay.
      # See https://docs.ray.io/en/latest/cluster/cli.html#ray-start for all available options in `rayStartParams`.
      rayStartParams: {}
      #pod template
      template:
        spec:
          containers:
          - name: ray-worker # must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc'
            image: rayproject/ray:2.46.0
            resources:
              limits:
                cpu: "1"
                memory: "1Gi"
              requests:
                cpu: "1"
                memory: "1Gi"

  # SubmitterPodTemplate is the template for the pod that will run the `ray job submit` command against the RayCluster.
  # If SubmitterPodTemplate is specified, the first container is assumed to be the submitter container.
  # submitterPodTemplate:
  #   spec:
  #     restartPolicy: Never
  #     containers:
  #     - name: my-custom-rayjob-submitter-pod
  #       image: rayproject/ray:2.46.0
  #       # If Command is not specified, the correct command will be supplied at runtime using the RayJob spec `entrypoint` field.
  #       # Specifying Command is not recommended.
  #       # command: ["sh", "-c", "ray job submit --address=http://$RAY_DASHBOARD_ADDRESS --submission-id=$RAY_JOB_SUBMISSION_ID -- echo hello world"]


######################Ray code sample#################################
# this sample is from https://docs.ray.io/en/latest/cluster/job-submission.html#quick-start-example
# it is mounted into the container and executed to show the Ray job at work
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ray-job-code-sample
data:
  sample_code.py: |
    import ray
    import os
    import requests

    ray.init()

    @ray.remote
    class Counter:
        def __init__(self):
            # Used to verify runtimeEnv
            self.name = os.getenv("counter_name")
            assert self.name == "test_counter"
            self.counter = 0

        def inc(self):
            self.counter += 1

        def get_counter(self):
            return "{} got {}".format(self.name, self.counter)

    counter = Counter.remote()

    for _ in range(5):
        ray.get(counter.inc.remote())
        print(ray.get(counter.get_counter.remote()))

    # Verify that the correct runtime env was used for the job.
    assert requests.__version__ == "2.26.0"
```

Rayjob status:
```
$ k get rayjob test-cluster-0
NAME             JOB STATUS   DEPLOYMENT STATUS   RAY CLUSTER NAME       START TIME             END TIME               AGE
test-cluster-0   SUCCEEDED    Complete            test-cluster-0-jnzgc   2025-08-03T16:14:11Z   2025-08-03T16:15:38Z   7m19s
```

podgroup:
```yaml
$ k get podgroup ray-rayjob-sample-mbs7q-pg -o yaml

apiVersion: scheduling.volcano.sh/v1beta1
kind: PodGroup
metadata:
  creationTimestamp: "2025-08-03T16:32:27Z"
  generation: 5
  name: ray-rayjob-sample-mbs7q-pg
  namespace: default
  ownerReferences:
  - apiVersion: ray.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: RayCluster
    name: rayjob-sample-mbs7q
    uid: f812976f-2153-4b67-803b-afc0cb49b001
  resourceVersion: "879"
  uid: 78bc499b-8191-4900-8007-6d51585d86f5
spec:
  minMember: 3
  minResources:
    cpu: "3"
    memory: 4Gi
  queue: kuberay-test-queue
status:
  conditions:
  - lastTransitionTime: "2025-08-03T16:33:17Z"
    reason: tasks in gang are ready to be scheduled
    status: "True"
    transitionID: b6854d7f-6a0c-4d99-8827-afc7fadb9858
    type: Scheduled
  phase: Running
  running: 3
```

```yaml
$ k get queue kuberay-test-queue -o yaml

apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"scheduling.volcano.sh/v1beta1","kind":"Queue","metadata":{"annotations":{},"name":"kuberay-test-queue"},"spec":{"capability":{"cpu":4,"memory":"6Gi"},"weight":1}}
  creationTimestamp: "2025-08-03T16:32:23Z"
  generation: 2
  name: kuberay-test-queue
  resourceVersion: "748"
  uid: 3c40e53d-021e-4eb8-9445-35cdb32d2ae5
spec:
  capability:
    cpu: 4
    memory: 6Gi
  parent: root
  reclaimable: true
  weight: 1
status:
  allocated:
    cpu: "3"
    memory: 4Gi
    pods: "3"
  reservation: {}
  state: Open
```

5. Add an additional `RayJob` with the same configuration of head and worker nodes, but with a different name:
```
sed 's/rayjob-sample/rayjob-sample-2/' ray-job.volcano-scheduler-queue.yaml | kubectl apply -f-
```


Check the status of its PodGroup to see that its phase is `Pending` and the last status is `Unschedulable`
```yaml
$ k get podgroup ray-rayjob-sample-2-nw5z6-pg -o yaml

apiVersion: scheduling.volcano.sh/v1beta1
kind: PodGroup
metadata:
  creationTimestamp: "2025-08-03T16:35:29Z"
  generation: 2
  name: ray-rayjob-sample-2-nw5z6-pg
  namespace: default
  ownerReferences:
  - apiVersion: ray.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: RayCluster
    name: rayjob-sample-2-nw5z6
    uid: ed739e69-a316-4ce3-8349-ba429a8a37c8
  resourceVersion: "1167"
  uid: ea3a440c-d5d1-44ec-bf67-a866f55ffb86
spec:
  minMember: 3
  minResources:
    cpu: "3"
    memory: 4Gi
  queue: kuberay-test-queue
status:
  conditions:
  - lastTransitionTime: "2025-08-03T16:35:29Z"
    message: '3/3 tasks in gang unschedulable: pod group is not ready, 3 Pending,
      3 minAvailable; Pending: 3 Unschedulable'
    reason: NotEnoughResources
    status: "True"
    transitionID: 599418fa-1971-4930-8ba0-03596895065b
    type: Unschedulable
  phase: Pending
```

```
$ k get pods

NAME                                             READY   STATUS      RESTARTS   AGE
kuberay-operator-66f6cb5f67-6mgwb                1/1     Running     0          7m1s
rayjob-sample-2-nw5z6-head-lbhr5                 0/1     Pending     0          3m48s
rayjob-sample-2-nw5z6-small-group-worker-79qdx   0/1     Pending     0          3m48s
rayjob-sample-2-nw5z6-small-group-worker-qbq8v   0/1     Pending     0          3m48s
rayjob-sample-4gnjz                              0/1     Completed   0          5m49s
rayjob-sample-mbs7q-head-f6wz4                   1/1     Running     0          6m50s
rayjob-sample-mbs7q-small-group-worker-g978z     1/1     Running     0          6m50s
rayjob-sample-mbs7q-small-group-worker-ldzvf     1/1     Running     0          6m50s

$ k describe pod rayjob-sample-2-nw5z6-head-lbhr5 | tail -n 3
  Type     Reason            Age    From     Message
  ----     ------            ----   ----     -------
  Warning  FailedScheduling  4m50s  volcano  pod group is not ready, 3 Pending, 3 minAvailable; Pending: 3 Unschedulable
```

6. Delete the first `RayJob` to make space in the queue:
```
$ k delete rayjob rayjob-sample
```

The PodGroup for the second cluster changed to the `Running` state
```yaml
$ k get podgroup ray-rayjob-sample-2-nw5z6-pg -o yaml
apiVersion: scheduling.volcano.sh/v1beta1
kind: PodGroup
metadata:
  creationTimestamp: "2025-08-03T16:35:29Z"
  generation: 6
  name: ray-rayjob-sample-2-nw5z6-pg
  namespace: default
  ownerReferences:
  - apiVersion: ray.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: RayCluster
    name: rayjob-sample-2-nw5z6
    uid: ed739e69-a316-4ce3-8349-ba429a8a37c8
  resourceVersion: "1913"
  uid: ea3a440c-d5d1-44ec-bf67-a866f55ffb86
spec:
  minMember: 3
  minResources:
    cpu: "3"
    memory: 4Gi
  queue: kuberay-test-queue
status:
  conditions:
  - lastTransitionTime: "2025-08-03T16:35:29Z"
    message: '3/3 tasks in gang unschedulable: pod group is not ready, 3 Pending,
      3 minAvailable; Pending: 3 Unschedulable'
    reason: NotEnoughResources
    status: "True"
    transitionID: 599418fa-1971-4930-8ba0-03596895065b
    type: Unschedulable
  - lastTransitionTime: "2025-08-03T16:41:08Z"
    reason: tasks in gang are ready to be scheduled
    status: "True"
    transitionID: 8ddd2b68-1099-40d7-a4d7-c84274819296
    type: Scheduled
  phase: Running
  running: 3
```

```
$ k get pods
NAME                                             READY   STATUS      RESTARTS   AGE
kuberay-operator-66f6cb5f67-6mgwb                1/1     Running     0          10m
rayjob-sample-2-nhw9r                            0/1     Completed   0          101s
rayjob-sample-2-nw5z6-head-lbhr5                 1/1     Running     0          7m34s
rayjob-sample-2-nw5z6-small-group-worker-79qdx   1/1     Running     0          7m34s
rayjob-sample-2-nw5z6-small-group-worker-qbq8v   1/1     Running     0          7m34s
```


But `gang scheduling` is currently supported only for `RayCluster`, we will extend Volcano scheduler support beyond `RayCluster` to also include `RayJob` and `RayService`.
