### ISSUE TITLE
[Bug] KubeRay operator Role missing 'batch' API Group rules

### ISSUE THREAD

**Issue by riccardomc** [ray-project/kuberay#1706]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

Deploying a fresh Kuberay Operator instance with helm values `crNamespacedRbacEnable: true` and `singleNamespaceInstall: true` results in the following errors in the operator logs:

```
W1204 14:38:49.665066       1 reflector.go:324] go/pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:167: failed to list *v1.Job: jobs.batch is forbidden: User "system:serviceaccount:mlserving-test:kuberay-operator" cannot list resource "jobs" in API group "batch" in the namespace "mlserving-test"
E1204 14:38:49.764696       1 reflector.go:138] go/pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:167: Failed to watch *v1.Job: failed to list *v1.Job: jobs.batch is forbidden: User "system:serviceaccount:mlserving-test:kuberay-operator" cannot list resource "jobs" in API group "batch" in the namespace "mlserving-test"
```

It appearst that the [multiple namespaces role](https://github.com/ray-project/kuberay/blob/master/helm-chart/kuberay-operator/templates/multiple_namespaces_role.yaml) is rules related to `batch` API Group and `jobs` resources.

### Reproduction script

1. `kubectl create namespace mlserving-test`
2. populate minimal `values.yaml`
```
---
image:
  repository: kuberay/operator
  tag: v1.0.0
serviceAccount:
  create: true
  name: "kuberay-operator"
rbacEnable: true
crNamespacedRbacEnable: true
singleNamespaceInstall: true
watchNamespace:
  - mlserving-test
```
3. install kuberay operator
```
helm upgrade --install \
  kuberay-operator \
  kuberay/kuberay-operator \
  --namespace mlserving-test \
  --values values.yaml \
  --version 1.0.0
```
4. fetch logs of Kuberay operator pod to observe the issue

### Anything else

Adding the following to the `rules:` of the generated `Role` seems to fix the issue:
```
  - apiGroups:
    - batch
    resources:
    - jobs
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
```

It also appears that [this is present](https://github.com/ray-project/kuberay/blob/master/helm-chart/kuberay-operator/templates/role.yaml) in the `ClusterRole` instead.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!
