### ISSUE TITLE
[Bug] Job submit failed with actor died

### ISSUE THREAD

**Issue by SimonCqk** [ray-project/kuberay#1744]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

I launched a simple RayJob instance in a standard Alibaba Cloud K8S cluster where the creation of resource objects such as HeadWorker/Service aligns with expectations. However, I encountered the following intermittent error when submitting tasks (running straightforward example code):

![image](https://github.com/ray-project/kuberay/assets/19202395/9a9b73bf-95da-43a8-b8e0-4832d7bd6838)

Inside the Head Worker node, I found the following error stack trace in the corresponding session directory.

![image](https://github.com/ray-project/kuberay/assets/19202395/6bf2ff37-ba2f-40e2-a2e5-34a5dacb62d5)

### Reproduction script

![image](https://github.com/ray-project/kuberay/assets/19202395/a48f95e1-296d-476d-97a2-3386d1e6e5e6)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
cc @architkulkarni

**Comment by architkulkarni** [comment]
@SimonCqk can you share the rayjob spec?

**Comment by architkulkarni** [comment]
Does the issue happen on multi-node clusters or does it happen on single-node clusters too?

**Comment by SimonCqk** [comment]
@architkulkarni  hi, rayjob spec is shown below, docker registry has been blurred since it is an internal address.

```yaml
apiVersion: ray.io/v1
kind: RayJob
metadata:
  finalizers:
  - ray.io/rayjob-finalizer
  generation: 2
  name: rayjob-test
  namespace: damo-cv
spec:
  entrypoint: python /home/ray/samples/sample_code.py
  rayClusterSpec:
    headGroupSpec:
      rayStartParams:
        dashboard-host: 0.0.0.0
      template:
        metadata: {}
        spec:
          containers:
          - image: xxxx/cvl/ray:2.8.0-py310-cu118
            name: ray-head
            ports:
            - containerPort: 6379
              name: gcs-server
              protocol: TCP
            - containerPort: 8265
              name: dashboard
              protocol: TCP
            - containerPort: 10001
              name: client
              protocol: TCP
            resources:
              limits:
                cpu: "4"
                memory: 8G
              requests:
                cpu: "4"
                memory: 8G
            volumeMounts:
            - mountPath: /home/ray/samples
              name: code-sample
            value: sigma_public
          volumes:
          - configMap:
              items:
              - key: sample_code.py
                path: sample_code.py
              name: ray-job-code-sample
            name: code-sample
    rayVersion: 2.8.0
    workerGroupSpecs:
    - groupName: small-group
      maxReplicas: 5
      minReplicas: 1
      rayStartParams: {}
      replicas: 1
      scaleStrategy: {}
      template:
        metadata: {}
        spec:
          containers:
          - image: xxxx/cvl/ray:2.8.0-py310-cu118
            lifecycle:
              preStop:
                exec:
                  command:
                  - /bin/sh
                  - -c
                  - ray stop
            name: ray-worker
            resources:
              limits:
                cpu: "4"
                memory: 8G
              requests:
                cpu: "4"
                memory: 8G
  submitterPodTemplate:
    metadata: {}
    spec:
      containers:
      - args:
        - "while true; do\n  if ray health-check --address ${RAYCLUSTER_SVC_NAME}.damo-cv.svc.cluster.local:6379;
          then\n    echo \"GCS is ready.\"\n    break\n  fi\n  echo \"Waiting for
          GCS to be ready.\"\n  sleep 5    \ndone\n\nray job submit --address http://${RAYCLUSTER_SVC_NAME}.damo-cv.svc.cluster.local:8265
          -- python /home/ray/samples/sample_code.py\n\nwhile true; echo \"hello\";
          do sleep 30; done;\n"
        command:
        - /bin/sh
        - -c
        image: xxxx/cvl/ray:2.8.0-py310-cu118
        name: rayjob-submitter
        resources: {}
      restartPolicy: Never

```
