### ISSUE TITLE
[Bug] Unable to set up cluster storage

### ISSUE THREAD

**Issue by jokerwenxiao** [ray-project/kuberay#1753]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

I submitted a pytorch distributed Job through RayJob and encountered an exception during the training process. 

The error information
```
(base) ray@rayjob-sample-raycluster-tl77k-head-2trwt:~/ray_results/TorchTrainer_2023-12-14_23-58-06/TorchTrainer_aea03_00000_0_2023-12-14_23-58-07$ cat error.txt
Failure # 1 (occurred at 2023-12-15_00-02-47)
ray::_Inner.train() (pid=1216, ip=172.23.141.88, actor_id=356d9a79f6ced8d0154396d502000000, repr=TorchTrainer)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/tune/trainable/trainable.py", line 342, in train
    raise skipped from exception_cause(skipped)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/train/_internal/utils.py", line 43, in check_for_failure
    ray.get(object_ref)
ray.exceptions.RayTaskError(RuntimeError): ray::_RayTrainWorker__execute.get_next() (pid=172, ip=172.20.173.145, actor_id=08f331301ddc3feeec4187dc02000000, repr=<ray.train._internal.worker_group.RayTrainWorker object at 0x7f55a861b850>)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/train/_internal/worker_group.py", line 33, in __execute
    raise skipped from exception_cause(skipped)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/train/_internal/utils.py", line 118, in discard_return_wrapper
    train_func(*args, **kwargs)
  File "/home/ray/samples/sample_code.py", line 43, in train_func
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/train/_internal/session.py", line 644, in wrapper
    return fn(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/train/_internal/session.py", line 706, in report
    _get_session().report(metrics, checkpoint=checkpoint)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/train/_internal/session.py", line 417, in report
    persisted_checkpoint = self.storage.persist_current_checkpoint(checkpoint)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/train/_internal/storage.py", line 549, in persist_current_checkpoint
    self._check_validation_file()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/train/_internal/storage.py", line 504, in _check_validation_file
    raise RuntimeError(
RuntimeError: Unable to set up cluster storage at storage_path=/home/ray/ray_results
Check that all nodes in the cluster have read/write access to the configured storage path.
```

### Reproduction script

RayJob information：
```
apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: rayjob-sample
spec:
  entrypoint: python /home/ray/samples/sample_code.py
  # shutdownAfterJobFinishes specifies whether the RayCluster should be deleted after the RayJob finishes. Default is false.
  # shutdownAfterJobFinishes: false

  # ttlSecondsAfterFinished specifies the number of seconds after which the RayCluster will be deleted after the RayJob finishes.
  # ttlSecondsAfterFinished: 10

  # RuntimeEnvYAML represents the runtime environment configuration provided as a multi-line YAML string.
  # See https://docs.ray.io/en/latest/ray-core/handling-dependencies.html for details.
  # (New in KubeRay version 1.0.)
  runtimeEnvYAML: |
    pip:
      - requests==2.26.0
      - pendulum==2.1.2
    env_vars:
      counter_name: "test_counter"

  # Suspend specifies whether the RayJob controller should create a RayCluster instance.
  # If a job is applied with the suspend field set to true, the RayCluster will not be created and we will wait for the transition to false.
  # If the RayCluster is already created, it will be deleted. In the case of transition to false, a new RayCluste rwill be created.
  # suspend: false

  # rayClusterSpec specifies the RayCluster instance to be created by the RayJob controller.
  rayClusterSpec:
    rayVersion: '2.7.0' # should match the Ray version in the image of the container
    # Ray head pod template
    headGroupSpec:
      # The `rayStartParams` are used to configure the `ray start` command.
      # See https://github.com/ray-project/kuberay/blob/master/docs/guidance/rayStartParams.md for the default settings of `rayStartParams` in KubeRay.
      # See https://docs.ray.io/en/latest/cluster/cli.html#ray-start for all available options in `rayStartParams`.
      rayStartParams:
        dashboard-host: '0.0.0.0'
      #pod template
      template:
        spec:
          containers:
            - name: ray-head
              image: xxx/other/ray-ml:gpu
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265 # Ray dashboard
                  name: dashboard
                - containerPort: 10001
                  name: client
              resources:
                limits:
                  cpu: "10"
                  nvidia.com/gpu: "1"
                requests:
                  cpu: "10"
                  nvidia.com/gpu: "1"
              volumeMounts:
                - mountPath: /home/ray/samples
                  name: code-sample
          volumes:
            # You set volumes at the Pod level, then mount them into containers inside that Pod
            - name: code-sample
              configMap:
                # Provide the name of the ConfigMap you want to mount.
                name: ray-job-code-sample
                # An array of keys from the ConfigMap to create as files
                items:
                  - key: sample_code.py
                    path: sample_code.py
    workerGroupSpecs:
      # the pod replicas in this group typed worker
      - replicas: 1
        minReplicas: 1
        maxReplicas: 5
        # logical group name, for this called small-group, also can be functional
        groupName: small-group
        # The `rayStartParams` are used to configure the `ray start` command.
        # See https://github.com/ray-project/kuberay/blob/master/docs/guidance/rayStartParams.md for the default settings of `rayStartParams` in KubeRay.
        # See https://docs.ray.io/en/latest/cluster/cli.html#ray-start for all available options in `rayStartParams`.
        rayStartParams: {}
        #pod template
        template:
          spec:
            containers:
              - name: ray-worker # must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc'
                image: xxx/other/ray-ml:gpu
                lifecycle:
                  preStop:
                    exec:
                      command: [ "/bin/sh","-c","ray stop" ]
                resources:
                  limits:
                    cpu: "10"
                    nvidia.com/gpu: "1"
                  requests:
                    cpu: "10"
                    nvidia.com/gpu: "1"
  # SubmitterPodTemplate is the template for the pod that will run the `ray job submit` command against the RayCluster.
  # If SubmitterPodTemplate is specified, the first container is assumed to be the submitter container.
  # submitterPodTemplate:
  #   spec:
  #     restartPolicy: Never
  #     containers:
  #       - name: my-custom-rayjob-submitter-pod
  #         image: rayproject/ray:2.7.0
  #         # If Command is not specified, the correct command will be supplied at runtime using the RayJob spec `entrypoint` field.
  #         # Specifying Command is not recommended.
  #         # command: ["ray job submit --address=http://rayjob-sample-raycluster-v6qcq-head-svc.default.svc.cluster.local:8265 -- echo hello world"]


######################Ray code sample#################################
# this sample is from https://docs.ray.io/en/latest/cluster/job-submission.html#quick-start-example
# it is mounted into the container and executed to show the Ray job at work
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ray-job-code-sample
data:
  sample_code.py: |
    import tempfile
    import torch
    import ray
    from torchvision.models import resnet18
    from torchvision.datasets import FashionMNIST
    from torchvision.transforms import ToTensor, Normalize, Compose
    from torch.utils.data import DataLoader
    from torch.optim import Adam
    from torch.nn import CrossEntropyLoss
    from ray.train.torch import TorchTrainer
    from ray.train import ScalingConfig, Checkpoint

    def train_func(config):

        # Model, Loss, Optimizer
        model = resnet18(num_classes=10)
        model.conv1 = torch.nn.Conv2d(1, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
        # [1] Prepare model.
        model = ray.train.torch.prepare_model(model)
        criterion = CrossEntropyLoss()
        optimizer = Adam(model.parameters(), lr=0.001)

        # Data
        transform = Compose([ToTensor(), Normalize((0.5,), (0.5,))])
        train_data = FashionMNIST(root='./data', train=True, download=True, transform=transform)
        train_loader = DataLoader(train_data, batch_size=128, shuffle=True)
        # [2] Prepare dataloader.
        train_loader = ray.train.torch.prepare_data_loader(train_loader)

        # Training
        for epoch in range(2):
            for images, labels in train_loader:
                outputs = model(images)
                loss = criterion(outputs, labels)
                optimizer.zero_grad()
                loss.backward()
                optimizer.step()

            checkpoint_dir = tempfile.gettempdir()
            checkpoint_path = checkpoint_dir + "/model.checkpoint"
            torch.save(model.state_dict(), checkpoint_path)
            # [3] Report metrics and checkpoint.
            ray.train.report({"loss": loss.item()}, checkpoint=Checkpoint.from_directory(checkpoint_dir))

    # [4] Configure scaling and resource requirements.
    scaling_config = ScalingConfig(num_workers=2, use_gpu=True)

    # [5] Launch distributed training job.
    trainer = TorchTrainer(train_func, scaling_config=scaling_config)
    result = trainer.fit()

```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
