### ISSUE TITLE
Readiness probe fails when creating a Ray cluster supporting serve 

### ISSUE THREAD

**Issue by blublinsky** [ray-project/kuberay#1828]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

I initially opened an issue https://github.com/ray-project/kuberay/issues/1826 about readiness probe, and was told that this is a feature. Unfortunately, this assumes that a ray cluster with serve support is already populated with the application, which might not be true. The following yaml is perfectly valid:
```
apiVersion: ray.io/v1
kind: RayCluster
metadata:
  annotations:
    ray.io/enable-serve-service: "true"
  name: test-cluster
spec:
  headGroupSpec:
    rayStartParams:
      dashboard-agent-listen-port: "52365"
      dashboard-host: 0.0.0.0
      metrics-export-port: "8080"
    serviceType: ClusterIP
    template:
      spec:
        containers:
          - name: ray-head
            image: rayproject/ray:2.9.0-py310
            ports:
              - containerPort: 6379
                name: gcs
              - containerPort: 8265
                name: dashboard
              - containerPort: 10001
                name: client
              - containerPort: 8000
                name: serve
            resources:
              limits:
                cpu: "2"
                memory: 4Gi
              requests:
                cpu: "2"
                memory: 4Gi
  workerGroupSpecs:
    - groupName: small-wg
      maxReplicas: 1
      minReplicas: 1
      replicas: 1
      rayStartParams:
        node-ip-address: $MY_POD_IP
      template:
        spec:
          containers:
          - name: ray-worker
            image: rayproject/ray:2.9.0-py310
            lifecycle:
              preStop:
                exec:
                  command:
                    - /bin/sh
                    - -c
                    - ray stop
            resources:
              limits:
                cpu: "2"
                memory: 4Gi
              requests:
                cpu: "2"
                memory: 4Gi
```
It creates a cluster with serve annotation without any applications. Readiness probe in this case is guaranteed to fail because port 8000 was not initialized yet

### Reproduction script

Use the above yaml

### Anything else

The current Readiness probe is designed to be not generic, but rather for a very specific use case where the cluster is immediately populated with applications. If this is not the case then
```
wget -T 2 -q -O- http://localhost:8000/-/healthz | grep success]
```
Is guaranteed to fail

I think the better option is not to enforce it in the general case, as it is done, but rather:
1. Remove it from the pod.go
2. Define the desired readiness probe explicitly in the rayservice_controller.go to overwrite the default

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
