### ISSUE TITLE
[Feature] Add default volumes and volumeMounts for `/tmp/ray` to Ray Pods

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#1851]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

In most KubeRay YAML manifests, you will find volumes and volumeMounts for `/tmp/ray`, as illustrated below. This enables users to access Ray logs even after the Ray container restarts. I am unsure whether it is common for some Kubernetes clusters to reject Pods with volumeMounts or not. If it is rare, we can add the volumes and volumeMounts for users automatically.

```yaml
volumeMounts:
  - mountPath: /tmp/ray
    name: ray-logs

volumes:
  - name: ray-logs
    emptyDir: {}
```

Note: If Ray Autoscaler is enabled, the volume and volumeMount will be set automatically. See [code](https://github.com/ray-project/kuberay/blob/33f29f61d6be0809662df2a58bbc605e7256a114/ray-operator/controllers/ray/common/pod.go#L319) for more details.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
