### ISSUE TITLE
[Feature] GPU Support Allow setting runtimeClass in template.spec

### ISSUE THREAD

**Issue by autolisis** [ray-project/kuberay#1876]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

I was trying to set up one of the examples with GPU support (I know that this particular example doesn't make use of the GPU)

```yaml
apiVersion: ray.io/v1alpha1
kind: RayService
metadata:
  name: rayservice-fake-emails
spec:
  serviceUnhealthySecondThreshold: 300
  deploymentUnhealthySecondThreshold: 300
  serveConfigV2: |
    applications:
      - name: fake
        import_path: fake:app
        route_prefix: /
  rayClusterConfig:
    rayVersion: 2.5.0 # Should match Ray version in the containers
    headGroupSpec:
      rayStartParams:
        dashboard-host: 0.0.0.0
      template:
        spec:
          containers:
            - name: ray-head
              image: shrekrisanyscale/serve-fake-email-example:example
              resources:
                requests:
                  nvidia.com/gpu: 1
                limits:
                  nvidia.com/gpu: 1
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265 # Ray dashboard
                  name: dashboard
                - containerPort: 10001
                  name: client
                - containerPort: 8000
                  name: serve
    workerGroupSpecs:
      - replicas: 1
        minReplicas: 1
        maxReplicas: 1
        groupName: small-group
        rayStartParams: {}
        template:
          spec:
            runtimeClass: nvidia
            containers:
              - name: ray-worker
                image: shrekrisanyscale/serve-fake-email-example:example
                lifecycle:
                  preStop:
                    exec:
                      command: ["/bin/sh","-c","ray stop"]
            resources:
                requests:
                  nvidia.com/gpu: 1
                limits:
                  nvidia.com/gpu: 1
```

That fails with the following error:
```
unknown field "spec.rayClusterConfig.workerGroupSpecs[0].template.spec.resources", unknown field "spec.rayClusterConfig.workerGroupSpecs[0].template.spec.runtimeClass"
```

Because it does not pass the field validation.

It would be nice if we could transparently pass all the children of spec to the created pod.

### Use case

I make use of K3S, which when used with containerd, requires Pods to have the additional spec `runtimeClass: nvidia` field set, to run with the Nvidia container runtime.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!
