### ISSUE TITLE
[Bug] Long Route names and namespaces auto-generate invalid host

### ISSUE THREAD

**Issue by neilisaur** [ray-project/kuberay#1882]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

When a Route is generated by the Ray Operator in OpenShift, it is populated with the Route `{metadata.name }`as provided by the ray-operator to be `<providedname>-head-route`, where `<providedname>-head-route` is ultimately checked for size maximums and reduced to 50 characters. The difficulty lies in that the `spec.host` value is not provided to the Route object, so when a `spec.host` is auto-generated it is created as the Route's: `{metadata.name}-{metadata.namespace}`. If the namespace is longer than 12 characters, then the generated `spec.host` value for the route's first DNS label is >63 characters, which is invalid per RFC 1035.

Example:
`my-task-does-not-have-too-long-a-name-raycluster-abcde-head-route` <- initial Route name
`t-have-too-long-a-name-raycluster-abcde-head-route` <- truncated name to 50 chars
`t-have-too-long-a-name-raycluster-abcde-head-route-my-namespace-here.mycluster.com` <- namespace appended to first portion of DNS by OpenShift is now 68 characters and will fail to create a route every time

### Reproduction script

Route that will fail to create in OpenShift that could be vaildly generated by Ray operator:

```
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: t-have-too-long-a-name-raycluster-abcde-head-route
  namespace: more-than-twelve-chars
spec:
  to:
    kind: Service
    name: t-have-too-long-a-name-raycluster-abcde-head-route
    weight: 100
  port:
    targetPort: 8265
  wildcardPolicy: None
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!
