### ISSUE TITLE
[Bug] Ray Head access to extra GPU resources

### ISSUE THREAD

**Issue by shaowei-su** [ray-project/kuberay#2098]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

If Ray head node is scheduled on GPU node with no GPU resource requested, e.g
```
      resources:
        limits:
          ephemeral-storage: 10Gi
          memory: 16Gi
        requests:
          cpu: '4'
          ephemeral-storage: 10Gi
          memory: 16Gi
```
Ray resource scheduler can still access those GPUs accidentally and considered the entire host GPU as "Logical Resources" during scheduling.

![Screenshot 2024-04-23 at 16 39 18](https://github.com/ray-project/kuberay/assets/7682657/238c908e-cd95-4b24-bd6d-be299e65313b)
![Screenshot 2024-04-23 at 16 39 11](https://github.com/ray-project/kuberay/assets/7682657/b152f72c-d01d-4f61-8bd3-840576944138)

### Reproduction script

Use `RayJob` CRD to scheduled both head and workers on the same physical host with > 1 GPUs.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!
