### ISSUE TITLE
[Bug] RayJob should surface errors with underlying RayCluster

### ISSUE THREAD

**Issue by han-steve** [ray-project/kuberay#2182]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

When you create a RayJob that is exceeds the resource quota, instead of surfacing this error, the RayJob's status stays at `Initializing`:
```
status:
  jobDeploymentStatus: Initializing
  jobId: rayjob-test2-krlp9
  rayClusterName: rayjob-test2-raycluster-bsh5z
  rayClusterStatus:
    desiredCPU: "0"
    desiredGPU: "0"
    desiredMemory: "0"
    desiredTPU: "0"
    head: {}
```
However, the RayCluster status correctly reflects the fact that the cluster has failed due to resource quota issue: 
```
status:
  desiredCPU: "0"
  desiredGPU: "0"
  desiredMemory: "0"
  desiredTPU: "0"
  head: {}
  reason: 'pods "rayjob-test2-raycluster-bsh5z-worker-small-wg-mh9v2" is forbidden:
    exceeded quota: low-resource-quota, requested: limits.cpu=200m,limits.memory=256Mi,
    used: limits.cpu=0,limits.memory=0, limited: limits.cpu=100m,limits.memory=107374182400m'
  state: failed
```
It will be great if the RayJob status can also accurately reflect the failed state of the underlying RayCluster, such as by setting the `jobDeploymentStatus` to `Failed` and `message` to the error message. 

### Reproduction script

I can contribute an integration test for this, but it'll be too long for here. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!
