### ISSUE TITLE
[Bug] spec.workerGroupSpecs[0].template.spec.containers[0].env: Invalid value: "null"

### ISSUE THREAD

**Issue by hongbo-miao** [ray-project/kuberay#2239]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

Others

### What happened + What you expected to happen

I try to deploy Ray Cluster by Helm Chart 1.1.1. I expect it succeed, but got error.

### Reproduction script

When deploy Ray cluster (I am using Argo CD)

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: horizon-ray-cluster
  namespace: production-horizon-argo-cd
  labels:
    app.kubernetes.io/name: horizon-ray-cluster
spec:
  project: production-horizon
  source:
    repoURL: https://ray-project.github.io/kuberay-helm
    # https://github.com/ray-project/kuberay/releases
    targetRevision: 1.1.1
    chart: ray-cluster
    helm:
      releaseName: horizon-ray-cluster
      values: |
        # https://github.com/ray-project/kuberay/blob/master/helm-chart/ray-cluster/values.yaml
        ---
        head:
          resources:
            requests:
              cpu: 1000m
              memory: 2Gi
            limits:
              cpu: 2000m
              memory: 4Gi
          containerEnv:
            - name: RANDOM_ENV
              value: "1"
          ports: []
        worker:
          resources:
            requests:
              cpu: 1000m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 8Gi
          containerEnv:
            - name: RANDOM_ENV
              value: "1"
          ports: []
  destination:
    namespace: production-horizon-ray-cluster
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true

```

I got error

```
RayCluster.ray.io "horizon-ray-cluster-kuberay" is invalid: [spec.headGroupSpec.template.spec.containers[0].env: Invalid value: "null": spec.headGroupSpec.template.spec.containers[0].env in body must be of type array: "null", spec.workerGroupSpecs[0].template.spec.containers[0].env: Invalid value: "null": spec.workerGroupSpecs[0].template.spec.containers[0].env in body must be of type array: "null", spec.workerGroupSpecs[0].template.spec.containers[0].ports: Invalid value: "null": spec.workerGroupSpecs[0].template.spec.containers[0].ports in body must be of type array: "null"]
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
It is solved by https://github.com/ray-project/kuberay/issues/2174

**Comment by kevin85421** [comment]
Close this issue. Feel free to reopen it if it doesn't solve by #2174

**Comment by hongbo-miao** [comment]
Thank you @kevin85421 !

**Comment by hongbo-miao** [comment]
Forgot this, just add a follow up.

On version 1.2.2, I can confirm without

```yaml
  containerEnv:
    - name: RANDOM_ENV
      value: "1"
  ports: []
```

it works now, thanks! ☺️
