### ISSUE TITLE
Conditions HeadPodReady and RayClusterReady have overlapping meanings

### ISSUE THREAD

**Issue by andrewsykim** [ray-project/kuberay#2297]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

This is the current conditions for a RayCluster in steady state:
```
  status:
    availableWorkerReplicas: 1
    conditions:
    - lastTransitionTime: "2024-08-09T19:16:09Z"
      message: ""
      reason: HeadPodRunningAndReady
      status: "True"
      type: HeadPodReady
    - lastTransitionTime: "2024-08-09T19:16:09Z"
      message: Only check head after all Ray Pods are initially ready
      reason: HeadPodRunningAndReady
      status: "True"
      type: RayClusterReady
```

I find it a bit confusing that both the HeadPodReady and RayClusterReady condition have the same reason  HeadPodRunningAndReady. After the initialization of the cluster, they are semantically the same. 

I propose that we change the `RayClusterReady` condition to something like `RayClusterProvisioned` or `RayClusterInitialized` which only represents the first time all pods are ready and does not track head Pod readiness afterwards. This reduces the overlap between these two conditions and makes it clearer which condition should be checked.  

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
