### ISSUE TITLE
[Feature] Allow referring requirements.txt path from zipfile in runtime_env in serveConfigV2

### ISSUE THREAD

**Issue by hanish-sx** [ray-project/kuberay#2351]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Allow users to refer the `requirements.txt` file in `runtime_env` from the zipfile provided as `working_dir`.

### Use case

Allowing users to refer the `requirements.txt` file in `runtime_env` from the zipfile provided as `working_dir`, will be convenient to package the app with their requirements rather than having to enumerate each dependency in the `pip` section. Having to enumerate each dependency one by one can get unwieldy.

I like to use the compiled requirements created by using `pip-tools` to pin each dependency. So having that in a file would be convenient as well as keep the yaml file short. 

```
apiVersion: ray.io/v1alpha1
kind: RayService
metadata:
  name: rayservice-sample
spec:
  serveConfigV2: |
    applications:
      - name: text_ml_app
        import_path: text_ml.app
        route_prefix: /summarize_translate
        runtime_env:
          working_dir: "s3://bucket/path/app.zip"
          pip:
            - "./requirements.txt" # This will be from the app.zip
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
