### ISSUE TITLE
[Feature] Support standard k8 spec for ray-job-submitter pod in Ray Job CRD

### ISSUE THREAD

**Issue by eyadgaran** [ray-project/kuberay#2392]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Ray jobs automatically template a ray-job-submitter pod to submit jobs to the head node, but the parameters are not configurable forcing the deployed pod to use default settings. It would be ideal to support similar parameterization to other templates (autoscaler, head node, worker nodes, etc) to better control the behavior.
ref: https://github.com/ray-project/kuberay/blob/73e6c5d66b9b14fd1aa5ca17a3ffad8c29957236/helm-chart/kuberay-operator/crds/ray.io_rayjobs.yaml#L50

### Use case

some examples of use cases that i personally have had are:
- service account name (not using the k8 default) to support workload identity
- image - being able to customize the image and dependencies for the job submitter independent of what is used on the head node
- volume mounts - being able to mount specific volumes or buckets to the container to customize the working dir

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by eyadgaran** [comment]
Found the reference to `submitterPodTemplate` which is what i was looking for! apologies for the false alarm

**Comment by andrewsykim** [comment]
no problem @eyadgaran! 

If it helps, we have an example reference here for using submitterPodTemplate https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/ray-job.sample.yaml#L103-L113 

and some dods about it here https://docs.ray.io/en/latest/cluster/kubernetes/getting-started/rayjob-quick-start.html#rayjob-configuration

Feel free to re-open the issue if you run into any issues

**Comment by eyadgaran** [comment]
thanks @andrewsykim! 
i am running into an issue that seems non deterministic. when i specify any values for the submitterPodTemplate the job hangs in the initializing phase after it creates the ray cluster instead of spawning the submitter pod. it seems like the issue stems from enabling the autoscaler (i went stepwise off the sample config introducing the differences in my target job) but subsequently commenting it out had no effect on future runs and the jobs still hang after creating the cluster. dropping the submitter block at any point reverts back to normal execution.
is there a debugging guide to step through the k8 crd execution to help diagnose why it is hanging? all the places i looked didnt yield anything interesting
i will try to chase this down more and may open another issue if i cant get to the bottom of it

**Comment by andrewsykim** [comment]
> is there a debugging guide to step through the k8 crd execution to help diagnose why it is hanging? all the places i looked didnt yield anything interesting

This is common feedback we got from other users actually and we recently just merged a PR to generate events for these types of failures: https://github.com/ray-project/kuberay/pull/2389. WIll be available in v1.2.2 or v1.3.0 

Do you know if the submitter Job is being created at all or does it run but fail to submit the job?
 
If you are overriding the `command` in `submitterPodTemplate`, keep in mind that you need to specify `--address=http://$RAY_DASHBOARD_ADDRESS --submission-id=$RAY_JOB_SUBMISSION_ID` similar to https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/ray-job.sample.yaml#L113C53-L113C131

**Comment by eyadgaran** [comment]
good to know! in this case it doesnt launch the submitter pod at all. also in case it is relevant, this happens even without overwriting the command parameter

**Comment by andrewsykim** [comment]
Are you able to share your RayJob YAML with any internal information redacted?

**Comment by eyadgaran** [comment]
yes of course! i extended the sample job but it uses the same python file moved to a bucket (instead of a config map)

```
apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: rayjob-sample
  namespace: ray-jobs
spec:
  shutdownAfterJobFinishes: true
  ttlSecondsAfterFinished: 60
  entrypoint: python sample_code.py
  runtimeEnvYAML: |
    pip:
      - requests==2.26.0
      - pendulum==2.1.2
    env_vars:
      counter_name: "test_counter"
    working_dir: "/bucket-mnt/test"

  rayClusterSpec:
    rayVersion: '2.35.0'
    # enableInTreeAutoscaling: true

    headGroupSpec:
      serviceType: ClusterIP
      rayStartParams:
        num-cpus: "0"
        num-gpus: "0"
        dashboard-host: '0.0.0.0'
      template:
        metadata:
          annotations:
            gke-gcsfuse/volumes: "true"
            gke-gcsfuse/memory-limit: 2000Mi
            gke-gcsfuse/ephemeral-storage-limit: 30Gi
        spec:
          serviceAccountName: ray-head
          containers:
            - name: ray-head
              image: rayproject/ray:2.35.0
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265
                  name: dashboard
                - containerPort: 10001
                  name: client
              resources:
                limits:
                  cpu: "1"
                requests:
                  cpu: "200m"
              volumeMounts:
                - name: gcs-fuse-csi-ephemeral
                  mountPath: /bucket-mnt
          volumes:
            - name: gcs-fuse-csi-ephemeral
              csi:
                driver: gcsfuse.csi.storage.gke.io
                volumeAttributes:
                  bucketName: some-bucket
                  mountOptions: "implicit-dirs"
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: "cloud.google.com/gke-nodepool"
                        operator: "In"
                        values: ["ray-heads"]
          tolerations:
            - key: "pool"
              operator: "Equal"
              value: "ray-heads"
              effect: "NoSchedule"
    workerGroupSpecs:
      - replicas: 0
        minReplicas: 0
        maxReplicas: 5
        groupName: small-group
        rayStartParams: {}
        template:
          metadata:
            annotations:
              gke-gcsfuse/volumes: "true"
              gke-gcsfuse/memory-limit: 2000Mi
              gke-gcsfuse/ephemeral-storage-limit: 30Gi
          spec:
            serviceAccountName: ray-worker
            containers:
              - name: ray-worker
                image: rayproject/ray:2.35.0
                lifecycle:
                  preStop:
                    exec:
                      command: [ "/bin/sh","-c","ray stop" ]
                resources:
                  limits:
                    cpu: "1"
                  requests:
                    cpu: "200m"
                volumeMounts:
                  - name: gcs-fuse-csi-ephemeral
                    mountPath: /bucket-mnt
            volumes:
            - name: gcs-fuse-csi-ephemeral
              csi:
                driver: gcsfuse.csi.storage.gke.io
                volumeAttributes:
                  bucketName: some-bucket
                  mountOptions: "implicit-dirs"
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: "cloud.google.com/gke-nodepool"
                          operator: "In"
                          values: ["cpu-large"]
            tolerations:
              - key: "pool"
                operator: "Equal"
                value: "cpu-large"
                effect: "NoSchedule"
  # SubmitterPodTemplate is the template for the pod that will run the `ray job submit` command against the RayCluster.
  # If SubmitterPodTemplate is specified, the first container is assumed to be the submitter container.
  submitterPodTemplate:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
        gke-gcsfuse/memory-limit: 200Mi
        gke-gcsfuse/ephemeral-storage-limit: 1Gi
    spec:
      serviceAccountName: ray-head
      containers:
        - name: ray-job-submitter
          image: rayproject/ray:2.35.0
          volumeMounts:
            - name: gcs-fuse-csi-ephemeral
              mountPath: /bucket-mnt
      volumes:
      - name: gcs-fuse-csi-ephemeral
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: some-bucket
            mountOptions: "implicit-dirs"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "cloud.google.com/gke-nodepool"
                    operator: "In"
                    values: ["ray-heads"]
      tolerations:
        - key: "pool"
          operator: "Equal"
          value: "ray-heads"
          effect: "NoSchedule"
```
