### ISSUE TITLE
Statistics of other types of gpu

### ISSUE THREAD

**Issue by zjj2wry** [ray-project/kuberay#2484]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

https://github.com/ray-project/kuberay/blob/33ba38546ddda0fa9121df20b357a13d47bb90d9/ray-operator/controllers/ray/raycluster_controller.go#L1623

if use aliyun k8s gpu share, gpu key is `aliyun.com/gpu-mem`
```
    workerGroupSpecs:
            resources:
              limits:
                aliyun.com/gpu-mem: "1"
                cpu: "1"
                memory: 2Gi
              requests:
                aliyun.com/gpu-mem: "1"
                cpu: "1"
                memory: 2Gi
```

autoscaler will not work when request gpu resource
```
(autoscaler +3m13s) Error: No available node types can fulfill resource request {'GPU': 1.0, 'CPU': 1.0}. Add suitable node types to this cluster to resolve this issue.
```

code:
```python
import ray
import time

ray.init()

@ray.remote(num_gpus=1) 
def gpu_task():
    import torch
    x = torch.rand(10000, 10000).cuda()  
    y = torch.mm(x, x) 
    return y.sum().item()

future = gpu_task.remote()
result = ray.get(future)

print("Result:", result)

ray.shutdown()
```

### Related issues

none

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
