### ISSUE TITLE
[Bug] RayService starts execution before K8s container resources are detected

### ISSUE THREAD

**Issue by ryanaoleary** [ray-project/kuberay#2494]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

RayServices or RayJobs that execute a script which rely on `ray.available_resources` being set can run into errors stemming from the K8s container resources not being detected prior to script execution, returning 0 and resulting in unexpected behavior. When creating Ray CRs through KubeRay, it'd be useful if K8s container resources specified in the CR manifest were set in the available resources from `ray start`. I observed this issue with RayServices using worker groups that request `google.com/tpu` resources.

### Reproduction script

1. I created a file with the following contents. I previously created a secret with my HF token and built a vLLM TPU image using the custom Dockerfile which are used below:
```
apiVersion: ray.io/v1
kind: RayService
metadata:
  name: vllm-tpu
spec:
  serveConfigV2: |
    applications:
      - name: llm
        import_path: ai-ml.gke-ray.rayserve.llm.serve_tpu:model
        deployments:
        - name: VLLMDeployment
          num_replicas: 1
        runtime_env:
          working_dir: "https://github.com/ryanaoleary/kubernetes-engine-samples/archive/refs/heads/multihost-example.zip"
          env_vars:
            MODEL_ID: "meta-llama/Meta-Llama-3.1-70B"
  rayClusterConfig:
    rayVersion: 2.34.0
    headGroupSpec:
      rayStartParams: {}
      template:
        spec:
          containers:
          - name: ray-head
            image: <YOUR-VLLM-TPU-IMAGE>
            imagePullPolicy: IfNotPresent
            ports:
            - containerPort: 6379
              name: gcs
            - containerPort: 8265
              name: dashboard
            - containerPort: 10001
              name: client
            - containerPort: 8000
              name: serve
            env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-secret
                  key: hf_api_token
            resources:
              limits:
                cpu: "8"
                memory: 40G
              requests:
                cpu: "8"
                memory: 40G
    workerGroupSpecs:
    - groupName: tpu-group
      replicas: 1
      minReplicas: 1
      maxReplicas: 1
      numOfHosts: 8
      rayStartParams: {}
      template:
        spec:
          containers:
            - name: ray-worker
              image: <YOUR-VLLM-TPU-IMAGE>
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  cpu: "100"
                  google.com/tpu: "4"
                  ephemeral-storage: 400Gi
                  memory: 200G
                requests:
                  cpu: "100"
                  google.com/tpu: "4"
                  ephemeral-storage: 400Gi
                  memory: 200G
              env:
                - name: JAX_PLATFORMS
                  value: "tpu"
                - name: HUGGING_FACE_HUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: hf-secret
                      key: hf_api_token 
          nodeSelector:
            cloud.google.com/gke-tpu-accelerator: tpu-v5-lite-podslice
            cloud.google.com/gke-tpu-topology: 4x4
```
2. Apply the CR manifest
```
kubectl apply -f ray-service-tpu.yaml
```
3. A KeyError will be thrown because `ray.available_resources["TPU"]` is not set.

### Anything else

This error is resolved by setting the `TPU` custom resource in the `rayStartParams` of the TPU worker group manifest. With https://github.com/ray-project/kuberay/pull/2409, `google.com/tpu` can be added to the list of known custom accelerators to automatically detect the k8s container resource and add it to the generated `rayStartCommand`. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!
