### ISSUE TITLE
[Feature][Helm] Support multiple Ray worker types in the KubeRay Helm chart

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/kuberay#255]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

KubeRay's RayCluster CRD supports multiple worker groups. However, the Helm chart supports only one worker group. It would be good to expose multiple groups.

Implementation ideas:

- One way to achieve this is to add a `workerGroups` field to the KubeRay CR, which would be a mapping from user-specified string names to configuration that is currently in the worker field.

- Another way is to have an array `workerGroups`.

The [Helm docs](https://v2.helm.sh/docs/chart_best_practices/#consider-how-users-will-use-your-values) suggest a map might be preferred over an array if the user uses --set to override values in the chart.
However, in my experience, a map can be confusing, because the user may interpret the keys as part of the schema, rather than as arbitrary names.

`workerGroups` would either override the current `worker` field OR the `worker` config would be internally appending to `workerGroups`.

### Use case

Easy configurability for mixed workloads (e.g. workloads the require GPUs and CPUs).

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by ecm200** [comment]
Just to back up this feature on @DmitriGekhtman  has already said, I have found it advantageous to be able to specify pod types, like you can with the Kubernetes helm chart deployment, and then match these up with underlying node pools. It means then you can give the cluster the option of determining the most efficient worker node instance types to use given the resource demands.

For example, giving the cluster building blocks of agent pools of 8, 16, 32 and 64 cpus instances, then the cluster can see what combination of these instance types closely matches the required cpu resource requirement. It avoids the spinning up of say a 32 cpu node when only 8 cpu units are needed.

**Comment by ecm200** [comment]
A Kubernetes based helm chart (i.e. non `kuberay`) would look like the following:

```yaml
podTypes:
    # The key for each podType is a user-defined string.
    # Since we set headPodType: rayHeadType, the Ray head pod will use the configuration
    # defined in this entry of podTypes:
    rayHeadType:
        # CPU is the number of CPUs used by this pod type.
        # (Used for both requests and limits. Must be an integer, as Ray does not support fractional CPUs.)
        CPU: 3
        # memory is the memory used by this Pod type.
        # (Used for both requests and limits.)
        memory: 3064Mi
        # GPU is the number of NVIDIA GPUs used by this pod type.
        # (Optional, requires GPU nodes with appropriate setup. See https://docs.ray.io/en/master/cluster/kubernetes-gpu.html)
        GPU: 0
        # rayResources is an optional string-int mapping signalling additional resources to Ray.
        # "CPU", "GPU", and "memory" are filled automatically based on the above settings, but can be overriden;
        # For example, rayResources: {"CPU": 0} can be used in the head podType to prevent Ray from scheduling tasks on the head.
        # See https://docs.ray.io/en/master/advanced.html#dynamic-remote-parameters for an example of usage of custom resources in a Ray task.
        rayResources: {"CPU": 0}
        # Optionally, set a node selector for this podType: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector
        nodeSelector: {"agentpool": "agentpool"}

        # tolerations for Ray pods of this podType (the head's podType in this case)
        #   ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
        #   Note that it is often not necessary to manually specify tolerations for GPU
        #   usage on managed platforms such as AKS, EKS, and GKE.
        #   ref: https://docs.ray.io/en/master/cluster/kubernetes-gpu.html
        tolerations: []
        # - key: "nvidia.com/gpu"
        #   operator: Exists
        #   effect: NoSchedule

    rayWorkerType_default:
        # minWorkers is the minimum number of Ray workers of this pod type to keep running.
        minWorkers: 0
        # maxWorkers is the maximum number of Ray workers of this pod type to which Ray will scale.
        maxWorkers: 4
        # memory is the memory used by this Pod type.
        # (Used for both requests and limits.)
        memory: 56000Mi
        # CPU is the number of CPUs used by this pod type.
        # (Used for both requests and limits. Must be an integer, as Ray does not support fractional CPUs.)
        CPU: 15
        # GPU is the number of NVIDIA GPUs used by this pod type.
        # (Optional, requires GPU nodes with appropriate setup. See https://docs.ray.io/en/master/cluster/kubernetes-gpu.html)
        GPU: 0
        # rayResources is an optional string-int mapping signalling additional resources to Ray.
        # "CPU", "GPU", and "memory" are filled automatically based on the above settings, but can be overriden;
        # For example, rayResources: {"CPU": 0} can be used in the head podType to prevent Ray from scheduling tasks on the head.
        # See https://docs.ray.io/en/master/advanced.html#dynamic-remote-parameters for an example of usage of custom resources in a Ray task.
        rayResources: [] #{"PODTYPE_VLARGE": 15}
        # Optionally, set a node selector for this Pod type. See https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector
        nodeSelector: {"agentpool": "raypool"}

        # tolerations for Ray pods of this podType
        #   ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
        #   Note that it is often not necessary to manually specify tolerations for GPU
        #   usage on managed platforms such as AKS, EKS, and GKE.
        #   ref: https://docs.ray.io/en/master/cluster/kubernetes-gpu.html
        tolerations: 
        - key: kubernetes.azure.com/scalesetpriority
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
        # - key: nvidia.com/gpu
        #   operator: Exists
        #   effect: NoSchedule

    rayWorkerType_large:
        # minWorkers is the minimum number of Ray workers of this pod type to keep running.
        minWorkers: 0
        # maxWorkers is the maximum number of Ray workers of this pod type to which Ray will scale.
        maxWorkers: 4
        # memory is the memory used by this Pod type.
        # (Used for both requests and limits.)
        memory: 110000Mi
        # CPU is the number of CPUs used by this pod type.
        # (Used for both requests and limits. Must be an integer, as Ray does not support fractional CPUs.)
        CPU: 31
        # GPU is the number of NVIDIA GPUs used by this pod type.
        # (Optional, requires GPU nodes with appropriate setup. See https://docs.ray.io/en/master/cluster/kubernetes-gpu.html)
        GPU: 0
        # rayResources is an optional string-int mapping signalling additional resources to Ray.
        # "CPU", "GPU", and "memory" are filled automatically based on the above settings, but can be overriden;
        # For example, rayResources: {"CPU": 0} can be used in the head podType to prevent Ray from scheduling tasks on the head.
        # See https://docs.ray.io/en/master/advanced.html#dynamic-remote-parameters for an example of usage of custom resources in a Ray task.
        rayResources: [] # {"PODTYPE_VLARGE": 15}
        # Optionally, set a node selector for this Pod type. See https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector
        nodeSelector: {"agentpool": "raypoollarge"}

        # tolerations for Ray pods of this podType
        #   ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
        #   Note that it is often not necessary to manually specify tolerations for GPU
        #   usage on managed platforms such as AKS, EKS, and GKE.
        #   ref: https://docs.ray.io/en/master/cluster/kubernetes-gpu.html
        tolerations: 
        - key: kubernetes.azure.com/scalesetpriority
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
        # - key: nvidia.com/gpu
        #   operator: Exists
        #   effect: NoSchedule

    rayWorkerType_small:
        # minWorkers is the minimum number of Ray workers of this pod type to keep running.
        minWorkers: 0
        # maxWorkers is the maximum number of Ray workers of this pod type to which Ray will scale.
        maxWorkers: 8
        # memory is the memory used by this Pod type.
        # (Used for both requests and limits.)
        memory: 28000Mi
        # CPU is the number of CPUs used by this pod type.
        # (Used for both requests and limits. Must be an integer, as Ray does not support fractional CPUs.)
        CPU: 7
        # GPU is the number of NVIDIA GPUs used by this pod type.
        # (Optional, requires GPU nodes with appropriate setup. See https://docs.ray.io/en/master/cluster/kubernetes-gpu.html)
        GPU: 0
        # rayResources is an optional string-int mapping signalling additional resources to Ray.
        # "CPU", "GPU", and "memory" are filled automatically based on the above settings, but can be overriden;
        # For example, rayResources: {"CPU": 0} can be used in the head podType to prevent Ray from scheduling tasks on the head.
        # See https://docs.ray.io/en/master/advanced.html#dynamic-remote-parameters for an example of usage of custom resources in a Ray task.
        rayResources: [] #{"PODTYPE_VLARGE": 15}
        # Optionally, set a node selector for this Pod type. See https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector
        nodeSelector: {"agentpool": "raypoolsmall"}

        # tolerations for Ray pods of this podType
        #   ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
        #   Note that it is often not necessary to manually specify tolerations for GPU
        #   usage on managed platforms such as AKS, EKS, and GKE.
        #   ref: https://docs.ray.io/en/master/cluster/kubernetes-gpu.html
        tolerations: 
        - key: kubernetes.azure.com/scalesetpriority
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
        # - key: nvidia.com/gpu
        #   operator: Exists
        #   effect: NoSchedule
```
