### ISSUE TITLE
[Feature] Remove unnecessary `preStop` from sample YAMLs

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#2606]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

It's not necessary to call `ray stop` in `preStop`.

```yaml
lifecycle:
  preStop:
    exec:
      command: ["/bin/sh","-c","ray stop"]
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
