### ISSUE TITLE
[Bug] botocore unable to locate credentials when using IRSA on workers

### ISSUE THREAD

**Issue by pkit** [ray-project/kuberay#2625]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

Starting a script on a kuberay cluster worker fails when the remote script tries to use AWS credentials.

`botocore.exceptions.NoCredentialsError: Unable to locate credentials`

You can see the RayCluster definition below.

It looks like although all the needed env vars are present on the worker the script (run with `.remote()`) fails to retrieve the credentials.
The worker AWS vars look fine.
```
AWS_DEFAULT_REGION : us-east-2
AWS_REGION : us-east-2
AWS_ROLE_ARN : arn:aws:iam::123456789012:role/worker
AWS_STS_REGIONAL_ENDPOINTS : regional
AWS_WEB_IDENTITY_TOKEN_FILE : /var/run/secrets/eks.amazonaws.com/serviceaccount/token
```
Works fine with `ray.init()`.
Works fine with any other script runner using the same docker image.
It looks like it's a problem with how remote scripts are started.

### Reproduction script

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/worker
---
apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: ray-cluster
spec:
  headGroupSpec:
    rayStartParams:
      dashboard-host: '0.0.0.0'
    template:
      metadata:
        labels: {}
      spec:
        containers:
        - name: ray-head
          image: ....
          ports:
          - containerPort: 6379
            name: gcs
          - containerPort: 8265
            name: dashboard
          - containerPort: 10001
            name: client
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","ray stop"]
          resources:
            limits:
              cpu: "1"
              memory: "2G"
            requests:
              cpu: "1"
              memory: "2G"
          env:
            - name: PYTHONPATH
              value: /
  workerGroupSpecs:
    - replicas: 1
      minReplicas: 1
      maxReplicas: 10
      groupName: w-group
      rayStartParams: { }
      template:
        spec:
          serviceAccountName: worker-sa
          containers:
            - name: ray-worker
              image: ....
              lifecycle:
                preStop:
                  exec:
                    command: [ "/bin/sh","-c","ray stop" ]
              resources:
                limits:
                  cpu: "4"
                  memory: "16G"
                requests:
                  cpu: "4"
                  memory: "16G"
              env:
                - name: PYTHONPATH
                  value: /
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
