### ISSUE TITLE
[GCS FT] Move GCS FT API from annotations to RayCluster CRD

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#2695]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Currently, users need to use an annotation `ray.io/ft-enabled` to enable GCS FT ([doc](https://docs.ray.io/en/latest/cluster/kubernetes/user-guides/kuberay-gcs-ft.html#enable-gcs-fault-tolerance)). Move the GCS API from annotations to RayCluster CRD.

Some possible APIs can be something similar to Autoscaler.

```yaml
enableGcsFaultTolerance: true
gcsFaultToleranceOptions:
  ... # maybe redis address / redis password ... etc
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
