### ISSUE TITLE
[Bug] Issues with RayCluster CRD and kubectl apply

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/kuberay#271]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

Others

### What happened + What you expected to happen

`kubectl apply -k manifests/cluster-scope-resources` yields the error
`The CustomResourceDefinition "rayclusters.ray.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes.`

Reason:
After re-generating the KubeRay CRD in https://github.com/ray-project/kuberay/pull/268, some pod template fields from recent versions of K8s were generated. Now the CRD is too big to fit in the metadata.lastAppliedConfiguration field used by `kubectl apply`.

The solution I'd propose is to move the CRD out of the kustomization file and advise users to `kubectl create` the CRD before installing the rest of the cluster-scoped resources.

### Reproduction script

See above.

### Anything else

After running `kubectl apply -k`, I tried to `kubectl delete -k` so that I could subsequently `kubectl create -k`.
Unfortunately, my `ray-system` namespace is hanging in a terminating state!
edit: My ray-system namespace is hanging simply because cluster is 100% borked.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by askainet** [comment]
In case this helps other people using ArgoCD to deploy KubeRay, we solved this issue using a Kustomization and patching the RayCluster CRD with the annotation `argocd.argoproj.io/sync-options: Replace=true` to make ArgoCD use `kubectl replace` instead of `kubectl apply` when syncing this particular resource:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/ray-project/kuberay/manifests/cluster-scope-resources/?ref=master
  - https://github.com/ray-project/kuberay/manifests/base/?ref=master

patchesStrategicMerge:
  # CRD rayclusters.ray.io manifest is too big to fit in the
  # annotation `kubectl.kubernetes.io/last-applied-configuration`
  # added by `kubectl apply` used by ArgoCD, and so it fails
  # https://github.com/ray-project/kuberay/issues/271
  # Annotate this CRD to make ArgoCD use `kubectl replace` and avoid the error when syncing it
  - |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: rayclusters.ray.io
      annotations:
        argocd.argoproj.io/sync-options: Replace=true
```
