### ISSUE TITLE
[Bug] TPU_WORKER_HOSTNAMES with long rayclusters name

### ISSUE THREAD

**Issue by a-pichard** [ray-project/kuberay#2923]
### Search before asking

- [x] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

I'm trying to run some TPU RayJob but i couldn't find a way to make the simple `jax.devices()` work. So far i understand that i need to install [this](https://github.com/GoogleCloudPlatform/ai-on-gke/tree/main/ray-on-gke/guides/tpu) webhook in order to have multi-host TPU with the 2 required environment variables injected in the containers `TPU_WORKER_ID` and `TPU_WORKER_HOSTNAMES`.

The problem is:
- i named my rayjob `experiment-0353b325-c892`. Which is not a very long name in my opinion.
- Then it creates a raycluster `experiment-0353b325-c892-raycluster-ndbdj`. Size almost doubled, why `-raycluster-`? We already know it's a raycluster since it's the resource kind. Why not for the extra hash at the end, Kubernetes usually does that on child resources.
- The headless worker service created for the worker to worker communication in the TPU context has it's prefix named cropped: `r353b325-c892-raycluster-ndbdj-headless-worker-svc`. Note that at this point, more than half of the name is a group of constant added on raycluster and a suffix on the service.

Anyway just naming stuff. The main issue is the generated `TPU_WORKER_HOSTNAMES` that does not match the headless service name: `TPU_WORKER_HOSTNAMES=tpu-pool-0-0.experiment-0353b325-c892-raycluster-ndbdj-headless-worker-svc,tpu-pool-0-1.experiment-0353b325-c892-raycluster-ndbdj-headless-worker-svc,tpu-pool-0-2.experiment-0353b325-c892-raycluster-ndbdj-headless-worker-svc,tpu-pool-0-3.experiment-0353b325-c892-raycluster-ndbdj-headless-worker-svc`

So the TPU workers fail connect to each other.

### Reproduction script

Part of the RayJob

```
          numOfHost: 4 
            name: worker
            resources:
              limits:
                cpu: "8"
                google.com/tpu: "4"
                memory: 8G
              requests:
                cpu: "4"
                google.com/tpu: "4"
                memory: 8G
          nodeSelector:
            cloud.google.com/gke-tpu-accelerator: tpu-v5-lite-podslice
            cloud.google.com/gke-tpu-topology: 4x4
```

Script is https://github.com/GoogleCloudPlatform/ai-on-gke/blob/main/ray-on-gke/tpu/kuberay-tpu-webhook/samples/tpu-test.py

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
