### ISSUE TITLE
[Feature] Add shellcheck to pre-commit

### ISSUE THREAD

**Issue by MortalHappiness** [ray-project/kuberay#2932]
### Search before asking

- [x] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Add https://github.com/koalaman/shellcheck-precommit to pre-commit.

Add the following snippets to `.pre-commit-config.yaml`

```yaml
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
```

And run `pre-commit run shellcheck --all-files` to fix all errors.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
