### ISSUE TITLE
[Bug][RayJob][1.3] RayJob with K8sJobMode fails to submit job using entrypoint

### ISSUE THREAD

**Issue by ryanaoleary** [ray-project/kuberay#2959]
### Search before asking

- [x] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

RayJobs with `K8sJobMode` fail when submitting the `entrypoint` script to the k8s Job. This same issue does not occur with `HTTPMode`. It looks like the `entrypoint` script is not getting parsed correctly, returning a `/bin/sh: 1: Syntax error: Bad function name` error.

### Reproduction script

Create a RayJob with the following spec:
```
apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: rayjob-test
  namespace: default
spec:
  submissionMode: "K8sJobMode"
  entrypoint: python -c "import ray; ray.init(); print(ray.cluster_resources())"
  rayClusterSpec:
    rayVersion: '2.40.0'
    headGroupSpec:
      rayStartParams:
        dashboard-host: '0.0.0.0'
      template:
        spec:
          containers:
          - name: ray-head
            image: rayproject/ray:2.40.0
            ports:
            - containerPort: 6379
              name: gcs-server
            - containerPort: 8265
              name: dashboard
            - containerPort: 10001
              name: client
            resources:
              limits:
                cpu: "1"
                memory: "4G"
              requests:
                cpu: "1"
                memory: "4G"
    workerGroupSpecs:
    - replicas: 1
      minReplicas: 1
      maxReplicas: 5
      groupName: small-group
      rayStartParams: {}
      template:
        spec:
          containers:
          - name: ray-worker
            image: rayproject/ray:2.40.0
            resources:
              limits:
                cpu: "1"
                memory: "4G"
              requests:
                cpu: "1"
                memory: "4G"
```

Apply the RayJob:
```
kubectl apply -f ray-job.yaml
```

Check the status to see it failed:
```
kubectl get rayjobs
NAME          JOB STATUS   DEPLOYMENT STATUS   RAY CLUSTER NAME               START TIME             END TIME               AGE
rayjob-test                Failed              rayjob-test-raycluster-g66d8   2025-02-06T21:31:43Z   2025-02-06T21:32:37Z   66s
```

Check the logs:
```
kubectl logs rayjob-test-bbwzg
/bin/sh: 1: Syntax error: Bad function name
```

### Anything else

I've verified the above reproduction script works for the same manifest but with `submissionMode: "HTTPMode"`. I tested the same reproduction script with the nightly KubeRay image and verified the same issue occurs. I then tested with KubeRay `v1.2.1` and did not encounter the issue, so this bug is introduced in v1.3.

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!
