### ISSUE TITLE
[Bug] Inconsistent resource requirement treatment when scheduling pods on EKS Auto Mode node pools

### ISSUE THREAD

**Issue by jleben** [ray-project/kuberay#3079]
### Search before asking

- [x] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

I am trying to set up a Ray cluster on an EKS Auto Mode cluster with auto-scaling using node pools. Following recommendations in KubeRay documentation, I am aiming for each node to have exactly one Ray pod scheduled on it which will manage all of the node's CPUs.

I am seeing an inability for KubeRay pods to be scheduled on my node pools, even though the resource requests of those pods is lower than the node pool instances provide.

For example, in the cluster created by the reproduction config below, the head pod fails to schedule with the error:
```
incompatible with nodepool "ray-debug-head", daemonset overhead={"pods":"0"}, no instance type has enough resources, requirements=, resources={"cpu":"1500m","memory":"512Mi","pods":"1"};
```
However, the nodepool provides an m5.large instance which has 2 vCPUs.

Note that this can be sidestepped in some cases by specifying lower resource requirements. In the above example, the pod successfully schedules if I reduce the explicit requirement for the head container from 1 CPU to 800m. The issue with specifying too low requirements however is that it can result in multiple pods scheduled on the same node

Moreover, I am unable at all to schedule any head or worker pod on a node with only 1 vCPU, even when I explicitly specify a resource request of 0 CPUs.

I have observed this issue across different EC2 instances and for both head and worker Ray pods. In some cases (with some EC2 instance types), like in the example given above, I can deterministically reproduce the issue and I can fine tune the resource requirement so as to allow the pod to schedule on the desired node while preventing multiple pods scheduling on the same node. In other cases, the issue appears only occasionally even when the Ray cluster and nodepool configuration is kept the same.

I have observed no such issue when creating my own pod with equal resource requirements as the problematic Ray pods - my own pods get successfully scheduled on nodes from the same node pools used by the Ray cluster.

### Reproduction script

```
apiVersion: eks.amazonaws.com/v1
kind: NodeClass
metadata:
  name: ray-debug-head
spec:
  subnetSelectorTerms:
  - id: subnet-05324181c6015696c
  securityGroupSelectorTerms:
  - id: sg-0aa9d1a25b2dee959
  role: AmazonEKSAutoNodeRole
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: ray-debug-head
  labels:
    earthdaily.com/ray-cluster: sample
spec:
  template:
    metadata:
      labels:
        ray-debug-head: 'true'
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: ray-debug-head
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
        - m5.large
---
apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: debug
spec:
  rayVersion: 2.42.1
  enableInTreeAutoscaling: true
  headGroupSpec:
    serviceType: ClusterIP
    rayStartParams: {}
    template:
      metadata: {}
      spec:
        nodeSelector:
          ray-debug-head: 'true'
        containers:
        - name: head
          image: 'rayproject/ray:latest-cpu'
          resources:
            requests:
              cpu: 1
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - ray stop
```

### Anything else

KubeRay version: 1.2.2, 1.3.0

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
