### ISSUE TITLE
[Feat][kubectl-plugin] Support mounting S3 Buckets

### ISSUE THREAD

**Issue by MortalHappiness** [ray-project/kuberay#3145]
Support automatically mounting GCS / S3 buckets:

```sh
kubectl ray create cluster --provider=gke --bucket=<bucket-name> --mount-path=<some-path>
```

**Comment by davidxia** [comment]
Is this with GCS Fuse? I'm adding GCS Fuse support in #3225 and can take this one too.

**Comment by MortalHappiness** [comment]
@davidxia Thanks. I've assigned this issue to you.

**Comment by davidxia** [comment]
Thanks. @andrewsykim this is mounting with GCS fuse, right?

**Comment by andrewsykim** [comment]
yes that's correct

**Comment by davidxia** [comment]
#3225 will allow users to use a config file to enable GCSFUse. Is that enough or do you think we also need to add CLI flags for this?


```yaml
# file is /tmp/t.yaml
namespace: hyperkube
name: dxia-test

gke:
  # Cloud Storage FUSE options
  gcsfuse:
    # Required bucket name
    bucket-name: my-bucket
    # Required mount path where bucket will be mounted in both head and worker nodes
    mount-path: /mnt/cluster_storage
    # See the Cloud Storage FUSE CLI file docs for all supported mount options.
    # https://cloud.google.com/storage/docs/cloud-storage-fuse/cli-options#options
    mount-options: "implicit-dirs,uid=1000,gid=100"
    # Optional resource configs for Cloud Storage FUSE CSI driver sidecar container
    resources:
      cpu: 250m
      memory: 256Mi
      ephemeral-storage: 5Gi
    # Optional volume attributes for Cloud Storage FUSE CSI driver
    # from the following page excluding the ones that Google recommends you set as mount options.
    # https://cloud.google.com/kubernetes-engine/docs/reference/cloud-storage-fuse-csi-driver/volume-attr
    disable-metrics: true
    gcsfuse-metadata-prefetch-on-mount: false
    skip-csi-bucket-access-check: false
```

```bash
$ kubectl ray create cluster dxia-test --file /tmp/t.yaml --dry-run

apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: dxia-test
  namespace: hyperkube
spec:
  headGroupSpec:
    rayStartParams:
      dashboard-host: 0.0.0.0
    template:
      metadata:
        annotations:
          gke-gcsfuse/cpu-request: 250m
          gke-gcsfuse/ephemeral-storage-limit: 5Gi
          gke-gcsfuse/ephemeral-storage-request: 5Gi
          gke-gcsfuse/memory-limit: 256Mi
          gke-gcsfuse/memory-request: 256Mi
      spec:
        containers:
        - image: rayproject/ray:2.41.0
          name: ray-head
          ports:
          - containerPort: 6379
            name: gcs-server
          - containerPort: 8265
            name: dashboard
          - containerPort: 10001
            name: client
          resources:
            limits:
              memory: 4Gi
            requests:
              cpu: "2"
              memory: 4Gi
          volumeMounts:
          - mountPath: /mnt/cluster_storage
            name: cluster-storage
        volumes:
        - csi:
            driver: gcsfuse.csi.storage.gke.io
            volumeAttributes:
              bucketName: my-bucket
              disableMetrics: "true"
              gcsfuseMetadataPrefetchOnMount: "false"
              mountOptions: implicit-dirs,uid=1000,gid=100
              skipCSIBucketAccessCheck: "false"
          name: cluster-storage
  rayVersion: 2.41.0
  workerGroupSpecs:
  - groupName: default-group
    rayStartParams:
      metrics-export-port: "8080"
    replicas: 1
    template:
      metadata:
        annotations:
          gke-gcsfuse/cpu-request: 250m
          gke-gcsfuse/ephemeral-storage-limit: 5Gi
          gke-gcsfuse/ephemeral-storage-request: 5Gi
          gke-gcsfuse/memory-limit: 256Mi
          gke-gcsfuse/memory-request: 256Mi
      spec:
        containers:
        - image: rayproject/ray:2.41.0
          name: ray-worker
          resources:
            limits:
              memory: 4Gi
            requests:
              cpu: "2"
              memory: 4Gi
          volumeMounts:
          - mountPath: /mnt/cluster_storage
            name: cluster-storage
        volumes:
        - csi:
            driver: gcsfuse.csi.storage.gke.io
            volumeAttributes:
              bucketName: my-bucket
              disableMetrics: "true"
              gcsfuseMetadataPrefetchOnMount: "false"
              mountOptions: implicit-dirs,uid=1000,gid=100
              skipCSIBucketAccessCheck: "false"
          name: cluster-storage
```
