### ISSUE TITLE
[Bug] kubecrl-ray  create cluster : Error: failed to create Ray cluster: the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json

### ISSUE THREAD

**Issue by tanguofu** [ray-project/kuberay#3192]
### Search before asking

- [x] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

Others

### What happened + What you expected to happen

```
root@9.134.50.101:/data/workspace/ai-operater/kuberay/kubectl-plugin# kubectl --kubeconfig ./kubeconfig  version --output=yaml
clientVersion:
  buildDate: "2024-03-14T01:05:39Z"
  compiler: gc
  gitCommit: 1649f592f1909b97aa3c2a0a8f968a3fd05a7b8b
  gitTreeState: clean
  gitVersion: v1.26.15
  goVersion: go1.21.8
  major: "1"
  minor: "26"
  platform: linux/amd64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2024-11-15T06:21:17Z"
  compiler: gc
  gitCommit: 8126bbdb38f143bf9476b6e56640192780a322b1
  gitTreeState: tcs
  gitVersion: v1.22.5-8126bbdb
  goVersion: go1.21.5
  major: "1"
  minor: 22+
  platform: linux/amd64
```

```
root@9:/kubectl-plugin# kubectl ray create cluster   --kubeconfig ./kubeconfig  cuda-check --image ray-check:cu12.4 --head-cpu 12 --head-memory 48  --head-gpu 2  --worker-replicas 0

Error: failed to create Ray cluster: the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json

```

### Reproduction script

 kubectl ray create cluster   --kubeconfig ./kubeconfig  cuda-check --image ray-check:cu12.4 --head-cpu 12 --head-memory 48  --head-gpu 2  --worker-replicas 0

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by andrewsykim** [comment]
@chiayi @MortalHappiness

**Comment by MortalHappiness** [comment]
Hi @tanguofu could you also provide your:
1. kubectl plugin version
2. kuberay operator version

**Comment by tanguofu** [comment]
```
root@9.134.50.101:/data/workspace/ai-operater/kuberay/kubectl-plugin# kubectl --kubeconfig ./kubeconfig  version --output=yaml
clientVersion:
  buildDate: "2024-03-14T01:05:39Z"
  compiler: gc
  gitCommit: 1649f592f1909b97aa3c2a0a8f968a3fd05a7b8b
  gitTreeState: clean
  gitVersion: v1.26.15
  goVersion: go1.21.8
  major: "1"
  minor: "26"
  platform: linux/amd64
kustomizeVersion: v4.5.7
```
 operator is  master branch.
