### ISSUE TITLE
[Feature] RayService Incremental Upgrade Project Tracker

### ISSUE THREAD

**Issue by ryanaoleary** [ray-project/kuberay#3209]
### Search before asking

- [x] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

- [ ] Implement [Ray Serve APIs for users to define custom timeouts for readiness](https://github.com/ray-project/ray/issues/50883)
- [ ] [RayService Incremental Upgrade Alpha](https://github.com/ray-project/kuberay/pull/3166)
- [ ] Add tests for upgrade rollback cases

### Use case

It'd be useful to support an API to incrementally upgrade the RayService, scaling a new RayCluster to handle only a % capacity of the total traffic to the RayService in order to avoid delays in the upgrade process due to resource constraints. This issue will track the progress of implementing the RayService incremental upgrade feature.

### Related issues

REP: https://github.com/ray-project/enhancements/blob/main/reps/2024-12-4-ray-service-incr-upgrade.md

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by ryanaoleary** [comment]
cc: @MortalHappiness

**Comment by ryanaoleary** [comment]
cc: @Future-Outlier This tracking issue is a pretty rough outline of the alpha scope, I can continue to add details so that it's more helpful. If anything sticks out to you, feel free to add to/comment on this issue.

**Comment by Future-Outlier** [comment]
TODO: We should document the resources we will use to teach users how to decide the parameters.
The total resource will be as follows:

## Formula

R_total_worker_pods = ceil(R_base_worker × (1 + MaxSurgePercent/100))
R_total(t) = R_head_A + R_head_B + R_total_worker_pods × R_per_worker


## Example

### Configuration
```yaml
apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: example-cluster
spec:
  headGroupSpec:
    template:
      spec:
        containers:
        - name: ray-head
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
  workerGroupSpecs:
  - replicas: 2
    template:
      spec:
        containers:
        - name: ray-worker
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
```

### Resource Calculation

**Head Pod Resources:**
```
R_head_A = 1 CPU + 2Gi memory
R_head_B = 1 CPU + 2Gi memory
R_head_total = 2 CPU + 4Gi memory
```

**Worker Pod Base Resources:**
```
R_base_worker_cpu = 2 replicas × 2 CPU = 4 CPU cores
R_base_worker_memory = 2 replicas × 4Gi = 8Gi memory
```

**Incremental Upgrade Total Resource Formula:**
```
R_total_worker_pods = ceil(R_base_worker_count × (1 + MaxSurgePercent/100))
R_total_cpu(t) = R_head_total_cpu + R_total_worker_pods × R_per_worker_cpu
R_total_memory(t) = R_head_total_memory + R_total_worker_pods × R_per_worker_memory
```

### Actual Calculation (MaxSurgePercent = 40%)
#### Step 1: Calculate Total Worker Pods
```
R_base_worker_count = 2
MaxSurgePercent = 40%
R_total_worker_pods = ceil(2 × (1 + 40/100)) = ceil(2 × 1.4) = ceil(2.8) = 3
```
#### Step 2: Calculate Total Resources
```
R_per_worker_cpu = 2 CPU
R_per_worker_memory = 4Gi memory

R_total_worker_cpu = 3 × 2 = 6 CPU cores
R_total_worker_memory = 3 × 4Gi = 12Gi memory

R_total_cpu(t) = 2 + 6 = 8 CPU cores
R_total_memory(t) = 4Gi + 12Gi = 16Gi memory
```
#### Step 3: Final Result
```
R_total(t) = 8 CPU cores + 16Gi memory
```
