### ISSUE TITLE
[Bug] RayCluster fails to transit Status.State to Ready when numOfHosts > 1

### ISSUE THREAD

**Issue by jyakaranda** [ray-project/kuberay#3274]
### Search before asking

- [x] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.


### KubeRay Component

ray-operator

### What happened + What you expected to happen

When I set `workerGroupSpecs.numOfHosts` greater than 1, such as 2, the raycluster fails to transit Status.State to Ready, which would block RayJob from submitting as a side effect.
https://github.com/ray-project/kuberay/blob/5a02146eb0ee64d2bff203f86c52a9da3854aee7/ray-operator/controllers/ray/rayjob_controller.go#L193-L196

It seems related with the DesiredWorkerReplicas calculation, which only stands for single host case.
https://github.com/ray-project/kuberay/blob/5a02146eb0ee64d2bff203f86c52a9da3854aee7/ray-operator/controllers/ray/raycluster_controller.go#L1299-L1304

Related logs in kuberay operator:
`{"level":"info","ts":"2025-04-07T05:28:27.310Z","logger":"controllers.RayCluster","msg":"inconsistentRayClusterStatus","RayCluster":{"name":"henry-ray-plan-off-raycluster-d9ht7","namespace":"ray"},"reconcileID":"65a566fd-4f94-4492-b8f6-eacfcdf3b2cd","oldReadyWorkerReplicas":4,"newReadyWorkerReplicas":5,"oldAvailableWorkerReplicas":5,"newAvailableWorkerReplicas":6,"oldDesiredWorkerReplicas":3,"newDesiredWorkerReplicas":3,"oldMinWorkerReplicas":1,"newMinWorkerReplicas":1,"oldMaxWorkerReplicas":6,"newMaxWorkerReplicas":6}`

### Reproduction script

part of workerGroupSpecs
```
  workerGroupSpecs:                                                                                                                                                                                                                                                         
  - rayStartParams:                                                                                                                                                                                                                                                         
      {}                                                                                                                                                                                                                                                                    
    replicas: 3                                                                                                                                                                                                                                                             
    minReplicas: 1                                                                                                                                                                                                                                                          
    maxReplicas: 6                                                                                                                                                                                                                                                          
    numOfHosts: 2                                                                                                                                                                                                                                                           
    groupName: workergroup
```

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
