### ISSUE TITLE
[Bug] ray allocates gpu from other node cause error “unknow devices”

### ISSUE THREAD

**Issue by estuday** [ray-project/kuberay#3275]
### Search before asking

- [x] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

environment:
ray: 2.24.0
vllm: 0.8.2

I am trying to use k8s + ray + volcano + vllm to deploy a LLM inference service. 
There are three nodes in the k8s cluster, one master node (without GPU) and two worker nodes (with GPU)
The specific cr is as follows：
```
apiVersion: ray.io/v1
kind: RayService
metadata:
  name: qwen25-05b
  namespace: deployment-system
  labels:
    ray.io/gang-scheduling-enbale: "true"
    ray.io/scheduler-name: volcano
    volcano.sh/queue-name: model-deploy
spec:
  serveConfigV2: |
    applications:
    - name: llm
      route_prefix: /
      import_path:  kuberay.ray-operator.config.samples.vllm.serve:model
      deployments:
      - name: VLLMDeployment
        num_replicas: 1
        ray_actor_options:
          num_cpus: 2
          num_gpus: 1
      runtime_env:
        env_vars:
          MODEL_ID: "/model"
          TENSOR_PARALLELISM: "1"
          PIPELINE_PARALLELISM: "2"
  rayClusterConfig:
    headGroupSpec:
      rayStartParams:
        dashboard-host: '0.0.0.0'
        disable-usage-stats: "true"
        no-monitor: "true"
      template:
        spec:
          nodeSelector:
            accelerator: cpu
          schedulerName: volcano
          volumes:
            - name: model
              nfs:
                server: finetunemaster
                path: /nfs/public/model/Qwen/
            - name: kuberay
              nfs: 
                server: finetunemaster
                path: /nfs/kuberay/kuberay-master
          containers:
          - name: ray-head
            image: docker.io/library/ray:2.40.0-torch2.5.1-cuda12.1-patch-fix
            resources:
              limits:
                cpu: "4"
                memory: "8Gi"
              requests:
                cpu: "4"
                memory: "8Gi"
            ports:
            - containerPort: 6379
              name: gcs-server
            - containerPort: 8265
              name: dashboard
            - containerPort: 10001
              name: client
            - containerPort: 8000
              name: serve
            volumeMounts:
              - name: model
                mountPath: /model
              - name: kuberay
                mountPath: /kuberay
    workerGroupSpecs:
    - replicas: 2
      minReplicas: 0
      maxReplicas: 4
      groupName: gpu-group
      rayStartParams:
        num-cpus: "4"
        num-gpus: "1"
        resources: '"{\"vgpu-memory\": 3000}"'
        disable-usage-stats: "true"
        no-monitor: "true"
      template:
        spec:
          schedulerName: volcano
          volumes:
            - name: model
              nfs:
                server: finetunemaster
                path: /nfs/public/model/Qwen/
            - name: kuberay
              nfs:
                server: finetunemaster
                path: /nfs/kuberay/kuberay-master
          containers:
          - name: llm
            image: docker.io/library/ray:2.40.0-torch2.5.1-cuda12.1-patch-fix
            resources:
              limits:
                cpu: 4
                memory: "8Gi"
                volcano.sh/vgpu-number: 1
                volcano.sh/vgpu-memory: 3000
              requests:
                cpu: "4"
                memory: "8Gi"
                volcano.sh/vgpu-number: 1
                volcano.sh/vgpu-memory: 3000
            volumeMounts:
              - name: model
                mountPath: /model
              - name: kuberay
                mountPath: /kuberay
---
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata: 
  name: model-deploy
spec:
  weight: 1
  capability:
    cpu: 16
    memory: 32Gi
    volcano.sh/vgpu-number: 2
    volcano.sh/vgpu-memory: 8000
 ```
When I apply this cr, I get the following error：
![Image](https://github.com/user-attachments/assets/3b8c9141-bbf3-4770-8b0b-e9092e3863f9)

The worker node that failed reported the error:
```
nvidia-container-cli: device error: GPU-xxxxxxx: unknown device: unknown
```
In fact, the failed node is looking for the GPU device of the successful node.

the dashboard logs of head nodes:
```
ValueError: Current node has no GPU available. current_node_resource={'node:172.20.252.143': 1.0, 'vgpu-memory': 3000.0, 'memory': 8589934592.0, 'CPU': 2.0, 'object_store_memory': 2540051251.0, 'accelerator_type:V100': 1.0}. vLLM engine cannot start without GPU. Make sure you have at least 1 GPU available in a node current_node_id='43d5b44296426cf542acd738d5b4d4ad9b536ba0941d25694adcf30c' current_ip='172.20.252.143'.
```

### Reproduction script

as same above

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
