### ISSUE TITLE
[Bug] "setup_timeout_seconds" runtime_env variable breaks the serve engine

### ISSUE THREAD

**Issue by egoulya** [ray-project/kuberay#3366]
### Search before asking

- [x] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

1) Bug:
Specifying the "setup_timeout_seconds" variable inside the: 
`serveConfigV2->applications->runtime_env->config`
results in infinite retries of runtime build. Here is controller log showing described behaviour:
```
INFO 2025-04-14 07:04:25,396 controller 488 -- Controller starting (version='2.43.0').
INFO 2025-04-14 07:04:25,403 controller 488 -- Starting proxy on node '1ae58adca95e7fd43e9607fedf5367039aad337c69bad4b6cf3855cf' listening on '0.0.0.0:8000'.
INFO 2025-04-14 07:04:26,904 controller 488 -- Deploying new app 'llm'.
INFO 2025-04-14 07:04:26,905 controller 488 -- Importing and building app 'llm'.
INFO 2025-04-14 07:04:26,917 controller 488 -- Importing and building app 'llm'.
INFO 2025-04-14 07:04:26,934 controller 488 -- Importing and building app 'llm'.
INFO 2025-04-14 07:04:26,962 controller 488 -- Importing and building app 'llm'.
INFO 2025-04-14 07:04:27,004 controller 488 -- Importing and building app 'llm'.
<continues indefinitely unless stopped>
```

2) I expect this variable to be able to change the default timeout of initial app setup. 

3) I'm trying to deploy vllm model using Kuberay operator through RayService CRD. RayService manifest is attached in reproduction script below. I've checked all the logs from "Logs" tab inside the Ray dashboard and didn't find any apparent issues/errors.

### Reproduction script

1) Install Kuberay operator using Helm:
```bash
helm repo add kuberay https://ray-project.github.io/kuberay-helm/
helm repo update
helm install kuberay-operator kuberay/kuberay-operator --version 1.3.2
```
2) Apply attached RayService manifest
```yaml
apiVersion: ray.io/v1
kind: RayService
metadata:
  name: qwen-3b-instruct
spec:
  serveConfigV2: |
    applications:
    - name: llm
      route_prefix: /
      import_path:  ray-operator.config.samples.vllm.serve:model
      deployments:
      - name: VLLMDeployment
        num_replicas: 2
        ray_actor_options:
          num_cpus: 8
      runtime_env:
        config: {
          "setup_timeout_seconds": "-1", # This can be set to anything other than 0, resulting in the same issue.
        }
        pip: ["git+https://github.com/vllm-project/vllm@main"]
        working_dir: "https://github.com/ray-project/kuberay/archive/refs/tags/v1.3.2.zip"
        env_vars:
          MODEL_ID: "Qwen/Qwen2.5-3B-Instruct"
          TENSOR_PARALLELISM: "2"
          PIPELINE_PARALLELISM: "2"
  rayClusterConfig:
    headGroupSpec:
      headService:
        metadata:
          annotations:
            metallb.universe.tf/address-pool: fast-pool
        spec:
          type: LoadBalancer
      rayStartParams:
        dashboard-host: '0.0.0.0'
      template:
        spec:
          containers:
          - name: ray-head
            image: rayproject/ray-ml:2.43.0.deprecated-py311-gpu
            resources:
              limits:
                cpu: "2"
                memory: "16Gi"
              requests:
                cpu: "2"
                memory: "16Gi"
            ports:
            - containerPort: 6379
              name: gcs-server
            - containerPort: 8265
              name: dashboard
            - containerPort: 10001
              name: client
            - containerPort: 8000
              name: serve
    workerGroupSpecs:
    - replicas: 2
      minReplicas: 2
      maxReplicas: 2
      groupName: gpu-group
      rayStartParams: {}
      template:
        spec:
          containers:
          - name: llm
            image: rayproject/ray-ml:2.43.0.deprecated-py311-gpu
            resources:
              limits:
                cpu: "8"
                memory: "32Gi"
                nvidia.com/gpu: "2"
              requests:
                cpu: "8"
                memory: "32Gi"
                nvidia.com/gpu: "2"
          tolerations:
            - key: "nvidia.com/gpu"
              operator: "Exists"
              effect: "NoSchedule"
```
3) Open Ray Dashboard running on port 8265
4) Open the "Serve" tab
5) You will get the same output described in the bug above.

### Anything else

This behaviour is always present, as long as "setup_timeout_seconds" variable is specified in the config. I need to use this variable to install "vllm" from source. Without it, I get timeout error while "vllm" package is being installed.

I couldn't find the reason behind this behavior myself.

The reason I want to use this variable - to be able to install "vllm" or any other python libraries from the source (specifying the repo instead of package name). There is currently an error produced by the latest version of vllm (0.8.3), which is already fixed in the main branch of their repo.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
