### ISSUE TITLE
[Bug] Ray cluster worker group not support volumeMount on data disk because of 'replicas' concept

### ISSUE THREAD

**Issue by f0rest9999** [ray-project/kuberay#3421]
### Search before asking

- [x] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

Hello ^ ^, we encountered a tricky case when deploying the ray cluster using the Kuberay operator.

Background: We found that the Pods of ray cluster use the system disk on the node by default. To optimize this situation, we want to use the data disk as the default mount directory of ray cluster Pods, that is, to place the data of /tmp/ray. The currently used method is pvc. For the head node, this is relatively easy to achieve:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-data1
provisioner: rancher.io/local-path
parameters:
  nodePath: /disk1
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
```

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc
  namespace: ray-system
spec:
  storageClassName: local-path-data1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi
```

And then, the yaml can be: 
```
headGroupSpec:
      ...
          volumeMounts:
            - name: ray-pvc
              mountPath: /tmp        

        volumes:
        - name: ray-pvc
          persistentVolumeClaim:
            claimName: test-pvc
```

However, there is a problem with workerGroup. Since workergroup is a replica concept, all replicas will share the configuration in yaml.

```
workerGroupSpecs:
  - replicas: 3
    minReplicas: 3
    maxReplicas: 3
      ...
          volumeMounts:
            - name: ray-pvc
              mountPath: /tmp        

        volumes:
        - name: ray-pvc
          # ERROR
          persistentVolumeClaim:
            # ERROR
            claimName: test-pvc

```

Then, the volumes here should not be set to pvc (one pvc corresponds to one pod), but rather a concept similar to a storage class, and for each worker, operator generate a pvc dynamically possibly. Then the life cycle of pvc is managed by the operator: creation, binding, deletion, etc.
```
workerGroupSpecs:
    - replicas: 3
      minReplicas: 3
      maxReplicas: 3

      storageVolumes:
          - name: be-storage
            storageClassName: local-path-data1
            storageSize: 100Gi
            mountPath: /tmp
```

**The problem is**
1. **I don't know if Kuberay operator has supported this kind of case. As far as I know, it hasn't. If not, is there any consideration for subsequent support?**
2.  **Are there any other recommended solutions for this situation?**
**Hope I have expressed the problem clearly. Looking forward to your reply. Thank you very much!!**

### Reproduction script

As mentioned above

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ltbringer** [comment]
We are facing the same issue. What is needed to implement this (happy to submit a PR)?

**Comment by Future-Outlier** [comment]
Hi, @f0rest9999 @ltbringer 
does this solve your problem?
https://github.com/ray-project/kuberay/issues/3839

**Comment by ltbringer** [comment]
@Future-Outlier Hey IIUC, it is not implemented?
The [proposal](https://docs.google.com/document/d/1jGFRrw-jnpomV5XgJzzFh5OOKtBx9B02O41AN29O1xQ/edit?tab=t.0#heading=h.bwydk3j2wpyz) goal addresses the problem. We needed each replica to mount its own pv.

**Comment by Future-Outlier** [comment]
Hi, @ltbringer 

can this solve your problem?

https://github.com/ray-project/kuberay/issues/3839#issuecomment-3125181853

**Comment by ltbringer** [comment]
```
...
        volumes:
        - ephemeral:
            volumeClaimTemplate:
              metadata:
                labels:
                  type: my-volume
              spec:
                accessModes:
                - ReadWriteOnce
                resources:
                  requests:
                    storage: 20Gi
                storageClassName: alicloud-disk-essd
          name: test-ephemeral
```
Yes this should solve my problem as well.
