### ISSUE TITLE
[Bug] [raycluster][service]Failed creating service xx/deepseek-r1-distill-llama-8b-v3-qf5duc, services "deepseek-r1-distill-llama-8b-v3-qf5duc" already exists

### ISSUE THREAD

**Issue by ying2025** [ray-project/kuberay#3489]
### Search before asking

- [x] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

@kevin85421 @andrewsykim When fixing the name of the head service, create raycluster, delete it, and then create it again. The service is created first, and raycluster reports an error stating that the service already exists.Before I create the raycluster, the service already delete.I expecte the raycluster can create normail.

### Reproduction script

```
  Head Group Spec:
    Head Service:
      Metadata:
        Annotations:
          prometheus.io/port:    8000
          prometheus.io/scrape:  true
        Labels:
          model.aibrix.ai/name:    deepseek-r1-distill-llama-8b-v3-qf5duc
          Prometheus - Discovery:  true
        Name:                      deepseek-r1-distill-llama-8b-v3-qf5duc
      Spec:
      Status:
        Load Balancer:
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by troychiu** [comment]
Take

**Comment by troychiu** [comment]
Hi @ying2025 , I tried to reproduce the issue on my end but wasn’t able to. Below is the Ray cluster YAML configuration and the exact steps I followed:
```yaml
apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: raycluster-kuberay
spec:
  rayVersion: '2.41.0-aarch64' # should match the Ray version in the image of the containers
  # Ray head pod template
  headGroupSpec:
    headService:
      metadata:
        name: raycluster-test-service
    rayStartParams: {}
    #pod template
    template:
      spec:
        containers:
        - name: ray-head
          image: rayproject/ray:2.41.0-aarch64
          resources:
            limits:
              cpu: 1
              memory: 2G
            requests:
              cpu: 1
              memory: 2G
          ports:
          - containerPort: 6379
            name: gcs-server
          - containerPort: 8265 # Ray dashboard
            name: dashboard
          - containerPort: 10001
            name: client
  workerGroupSpecs:
    # the pod replicas in this group typed worker
    - replicas: 1
      minReplicas: 1
      maxReplicas: 5
      # logical group name, for this called small-group, also can be functional
      groupName: workergroup
      rayStartParams: {}
      #pod template
      template:
        spec:
          containers:
            - name: ray-worker # must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc'
              image: rayproject/ray:2.41.0-aarch64
              resources:
                limits:
                  cpu: 1
                  memory: 1G
                requests:
                  cpu: 1
                  memory: 1G
```
Steps I used:

1. Ran kubectl apply -f ray-cluster.yaml to create the Ray cluster.
2. Verified that both the Ray cluster and its service were created.
3. Deleted the Ray cluster using kubectl delete raycluster raycluster-kuberay. The associated service was also deleted, as it has an owner reference to the Ray cluster.
4. Re-applied the YAML file with kubectl apply -f ray-cluster.yaml.
5. The Ray cluster was created successfully without any issues.

Is there anything different in your setup or steps that might help pinpoint the issue? If possible, could you share how you’re reproducing it?
Thanks!
