### ISSUE TITLE
[Bug][kubectl-plugin] Wrong behavior for InteractiveMode RayJob with BackoffLimit set

### ISSUE THREAD

**Issue by MortalHappiness** [ray-project/kuberay#3525]
### Search before asking

- [x] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

The "deployment status" transitions from `Running` if `backoffLimit` is set to a value greater than 1 for RayJob with `InteractiveMode`. It should be `Waiting` or `Failed` and needs some discussion.

### Reproduction script

`rayjob.yaml`

```yaml
apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: my-rayjob
  namespace: default
spec:
  rayClusterSpec:
    headGroupSpec:
      rayStartParams:
        dashboard-host: 0.0.0.0
      template:
        spec:
          containers:
            - image: rayproject/ray:2.41.0
              name: ray-head
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265
                  name: dashboard
                - containerPort: 10001
                  name: client
              resources:
                limits:
                  memory: 4Gi
                requests:
                  cpu: "2"
                  memory: 4Gi
    rayVersion: 2.41.0
    workerGroupSpecs:
      - groupName: default-group
        rayStartParams:
          metrics-export-port: "8080"
        replicas: 1
        template:
          spec:
            containers:
              - image: rayproject/ray:2.41.0
                name: ray-worker
                resources:
                  limits:
                    memory: 4Gi
                  requests:
                    cpu: "2"
                    memory: 4Gi
  submissionMode: InteractiveMode
  backoffLimit: 2
```

`kubectl ray job submit --working-dir . -f rayjob.yaml -- python task1.py` (note that there is no `task1.py` in the current working directory)

`kubectl get rayjob`

The "deployment status" transitions from `Initializing` to `Waiting` when the first RayCluster is created. Then it finds that `task1.py` does not exist and fails. When the second RayCluster is created, it goes back to `Initializing` again, but since `spec.JobId` is already set, it transitions to `Running` instead of `Waiting`.

### Anything else

We should discuss the behavior of `BackoffLimit` for `InteractiveMode`. We can either:

- Don't support it at all.
- Clear `spec.JobId` when the second RayCluster is created. And then wait for the user update `spec.JobId` again.
- Remember all inputs from user and then retry automatially. This might be problematic because we need to handle `workingDir` properly.

Update: After discussion, we decide to not support it at all.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
