### ISSUE TITLE
[Feature][DRA] Automatically detect GPUs set by DRA and pass it into ray start params

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#3527]
### Search before asking

- [x] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Related to #3506 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
cc @siyuanfoundation

**Comment by jackfrancis** [comment]
cc @nojnhuh

this might be ~related as a jumping off point https://github.com/ray-project/kuberay/pull/3567

cc @ritazh

**Comment by nojnhuh** [comment]
For DRA, it won't be possible to follow the same general approach as #3567 of inspecting the Pod and any ResourceClaims it references to derive how many GPU devices are requested. Since ResourceClaims can request "all of the devices in a pool" (i.e. GPUs on a Node) or a [prioritized list](https://github.com/kubernetes/enhancements/blob/20c9001ee24191c64add9d2ffcb6da3ed56fc9f4/keps/sig-scheduling/4816-dra-prioritized-list/README.md) of preferred outcomes, the number of GPUs allocated for a Pod in those cases can only be determined after the Pod is scheduled. Especially since the [docs suggest](https://docs.ray.io/en/latest/cluster/kubernetes/user-guides/config.html#resources) to size Pods to take up an entire Node, I expect creating ResourceClaims with `allocationMode: All` for GPUs would be recommended as a best practice.

Can we rely on Ray to accurately [determine itself](https://github.com/ray-project/ray/blob/9fb7d772619b2781e9a44bec468feae771b3bf25/python/ray/_private/resource_and_label_spec.py#L469-L472) how many GPUs are available to its container? Or is it otherwise preferable to set `--num-gpus` explicitly for `ray start`?

**Comment by andrewsykim** [comment]
cc @siyuanfoundation

**Comment by andrewsykim** [comment]
> Can we rely on Ray to accurately determine itself how many GPUs are available to its container? 

I think this is the question to answer before we do any additional work for KubeRay's DRA integration. There's probably a good reason we set `--num-gpus` based on resource requests, but it could make more sense to fallback to runtime check if DRA is enabled. We should run some tests and validate the current behavior.

**Comment by nojnhuh** [comment]
I finally got around to trying this out and it looks like the right values are already being picked up when DRA is in use. I'm following the [RayCluster Quickstart](https://docs.ray.io/en/master/cluster/kubernetes/getting-started/raycluster-quick-start.html) with a Kubernetes 1.34 cluster with one worker node with 2 A100 GPUs and Ray 1.4.2.

Here are the steps I took:
1. Create a RayCluster with the following Helm values:
    ```yaml
    head:
      resources:
        limits: null
        claims:
        - name: gpu
    worker:
      disabled: true
    ```
1. Edit the RayCluster to add DRA config, e.g. with the following merge patch:
    ```yaml
    apiVersion: ray.io/v1
    kind: RayCluster
    metadata:
      name: raycluster-kuberay
    spec:
      headGroupSpec:
        template:
          spec:
            resourceClaims:
            - name: gpu
              resourceClaimTemplateName: ray-gpus
    ```
1. Delete the existing head Pod to so a new one is created with the new config.
1. Create the following ResourceClaimTemplate:
    ```yaml
    apiVersion: resource.k8s.io/v1
    kind: ResourceClaimTemplate
    metadata:
      name: ray-gpus
    spec:
      spec:
        devices:
          requests:
          - name: all-gpus
            exactly:
              deviceClassName: gpu.nvidia.com
    ```
1. Once the Pod is ready, query for resources. One GPU is found:
    ```
    kubectl exec -it $(kubectl get pods --selector=ray.io/node-type=head -o custom-columns=POD:metadata.name --no-headers) -- python -c "import ray; ray.init(); print(ray.cluster_resources())"
    ```
    ```
    2025-09-15 11:52:07,727	INFO worker.py:1554 -- Using address 127.0.0.1:6379 set in the environment variable RAY_ADDRESS
    2025-09-15 11:52:07,727	INFO worker.py:1694 -- Connecting to existing Ray cluster at address: 192.168.197.161:6379...
    2025-09-15 11:52:07,740	INFO worker.py:1879 -- Connected to Ray cluster. View the dashboard at 192.168.197.161:8265 
    {'object_store_memory': 10000000000.0, 'memory': 451188673536.0, 'node:192.168.197.161': 1.0, 'node:__internal_head__': 1.0, 'CPU': 1.0, 'GPU': 1.0, 'accelerator_type:A100': 1.0}`
    ```

Modifying the ResourceClaimTemplate to request `All` GPUs, Ray detects both GPUs on the node which were allocated by DRA:
```yaml
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: ray-gpus
spec:
  spec:
    devices:
      requests:
      - name: all-gpus
        exactly:
          deviceClassName: gpu.nvidia.com
          allocationMode: All
```
```
2025-09-15 11:55:34,849	INFO worker.py:1554 -- Using address 127.0.0.1:6379 set in the environment variable RAY_ADDRESS
2025-09-15 11:55:34,849	INFO worker.py:1694 -- Connecting to existing Ray cluster at address: 192.168.197.162:6379...
2025-09-15 11:55:34,861	INFO worker.py:1879 -- Connected to Ray cluster. View the dashboard at 192.168.197.162:8265 
{'memory': 451194235904.0, 'node:192.168.197.162': 1.0, 'CPU': 1.0, 'accelerator_type:A100': 1.0, 'GPU': 2.0, 'node:__internal_head__': 1.0, 'object_store_memory': 10000000000.0}
```
