### ISSUE TITLE
[Bug] Unable to deploy standalone ray-operator from stable version v0.2.0

### ISSUE THREAD

**Issue by jeroen-vankelecom** [ray-project/kuberay#355]
### Search before asking

- [ ] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

# Bug
We are installing the `ray-operator` following the instructions from the [README](https://github.com/ray-project/kuberay/tree/master/ray-operator#deploy-the-operator) - but we would like to pin the version on the stable version 0.2.0.

```
$ kubectl apply -k "github.com/ray-project/kuberay/ray-operator/config/default?ref=v0.2.0&timeout=90s"
```

# Expected behaviour

Expecting to see v0.2.0 of the operator launched on the cluster, but it seems it is using the nightly build:

```
$ kubectl get pods --namespace ray-system -o jsonpath="{.items[*].spec.containers[*].image}"
kuberay/operator:nightly
```

The image tag is wrongly set in the [default Kustomization](https://github.com/ray-project/kuberay/blob/v0.2.0/ray-operator/config/default/kustomization.yaml#L26) for the ray-operator.

# Workaround?

Deploying ray-operator through the [base Kustomization](https://github.com/ray-project/kuberay/blob/v0.2.0/manifests/base/kustomization.yaml) seems to work fine, but it also deploys the api server (which we do not need).

So our questions:
1. Is there a workaround to override the tag, or to disable the api-server deployment?
2. Could you pin the operator version?

### Reproduction script

```
kubectl get pods --namespace ray-system -o jsonpath="{.items[*].spec.containers[*].image}"
kubectl apply -k "github.com/ray-project/kuberay/ray-operator/config/default?ref=v0.2.0&timeout=90s"
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jeroen-vankelecom** [comment]
Currently working around the issue by using another Kustomization:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- git@github.com:ray-project/kuberay/ray-operator/config/default?ref=v0.2.0&timeout=90s

images:
- name: kuberay/operator
  newName: kuberay/operator
  newTag: v0.2.0
```
