### ISSUE TITLE
[Bug] KubeRay not compatible with CUDA MPS of NVIDIA device plugin for Kubernetes

### ISSUE THREAD

**Issue by PaoPaoYue** [ray-project/kuberay#3634]
### Search before asking

- [x] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

I configured GPU sharing provided by [NVIDIA device plugin](https://github.com/NVIDIA/k8s-device-plugin), with configuration like the following:
```
version: v1
sharing:
  mps:
    resources:
    - name: nvidia.com/gpu
      replicas: 10
```
And then I declared resource usage in the worker pod Spec of RayService CRD/RayCluster CRD like:
```
resources:
  limits:
    nvidia.com/gpu: 1
  requests:
    nvidia.com/gpu: 1
```
The problem is, in any of the worker pod I cannot access GPU when using torch:
```
>>> import torch
>>> torch.cuda.is_available()
/home/ray/anaconda3/lib/python3.9/site-packages/torch/cuda/__init__.py:129: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 205: mapping of buffer object failed (Triggered internally at /pytorch/c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
False
```

But nvida-smi shows that GPU is available on the pod. And if I initialize a ray cluster for a scratch (not using ray-operator/RayService CRD/RayCluster CRD, just run pure pods and call `ray start` command in the container entry), I can get access to shared GPU with MPS enabled.

Another interesting point is if I use time-slicing mode, KubeRay can get access to GPU.
```
version: v1
sharing:
  timeSlicing:
    resources:
    - name: nvidia.com/gpu
      replicas: 10
```

### Reproduction script

> helm upgrade -i nvdp nvdp/nvidia-device-plugin --values nvidia-device-plugin.yaml 
```
# nvidia-device-plugin.yaml 
version: v1
sharing:
  mps:
    resources:
    - name: nvidia.com/gpu
      replicas: 10
```
In the worker pod Spec of RayService CRD/RayCluster CRD:
```
resources:
  limits:
    nvidia.com/gpu: 1
  requests:
    nvidia.com/gpu: 1
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
