### ISSUE TITLE
[Feature] Provide a better experience to manage the KubeRay with ArgoCD and GitOps

### ISSUE THREAD

**Issue by cmontemuino** [ray-project/kuberay#3659]
### Search before asking

- [x] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Install CRDs from a subchart instead of using Helm 3 `crds` directory.

Having CRDs installed from a chart solves several issues: clean uninstall, possibility for upgrades, templating.

## Motivation and Context

My main motivation is to have a better experience when managing this operator with Argo CD. That said, moving away from Helm 3 approach to install CRDs might be helpful in other scenarios too. I'm posting the full rationale below.

Helm 3 does not manage CRDs (see https://helm.sh/docs/chart_best_practices/custom_resource_definitions/). `helm uninstall` won't remove CRDs, and `helm updgrade` won't upgrade them. Manual intervention is required with the current setup.
- CRDs installed from `crds` folder **are not included into the helm release**.
- Additionally, it is not possible to template CRDs in Helm 3 in the `crds` folder.

The following comes from helm best practices around CRDs:

> There is no support at this time for upgrading or deleting CRDs using Helm. This was an explicit decision after much community discussion due to the danger for unintentional data loss.

ref: https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you

Another alternatively, which is what I propose and comes from Helm page:

> Another way to do this is to put the CRD definition in one chart, and then put any resources that use that CRD in another chart.
>
> In this method, each chart must be installed separately. However, this workflow may be more useful for cluster operators who have admin access to a cluster

ref: https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-2-separate-charts

**How this can be done?**

The change is pretty straightforward. It requires creating a subchart and a bit of scripting to keep CRDs in sync between `crds` folder and the templates in the subchart. File `values.yaml` for the subchart would look like this:
```yaml
crds:
   # -- Toggle to install and upgrade CRDs from a subchart. Make sure to use it with `--skip-crds` to avoid conflicts. [More info about limitations on CRDs in Helm 3](https://helm.sh/docs/topics/charts/#limitations-on-crds)
   install: false
   # -- Annotations to be added to all CRDs
   annotations: {}
```

This way, the KubeRay Operator can be managed with ArgoCD with ease.

**I'm completely fine to open a PR with the required refactoring, without impacting current installations**.

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!
