### ISSUE TITLE
[Bug] Custom resources are badly parsed and show error on

### ISSUE THREAD

**Issue by pinduzera** [ray-project/kuberay#3756]
### Search before asking

- [x] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

kubectl-plugin, ray-operator

### What happened + What you expected to happen

When using the env variables custom command with `KUBERAY_GEN_RAY_START_CMD` with custom resources, it can't properly parse the resources. The pod fails to start with the following error:

```bash
Error: Got unexpected extra arguments (1, \"custom-rec2\": 10}")
```

It only happens with annotation to overwrite. Running a command before, without relying directly on `KUBERAY_GEN_RAY_START_CMD` works as intended.

### Reproduction script

Add a custom resource to start params of head and/or workers adn overwrite entrypoint to use $KUBERAY_GEN_RAY_START_CMD.

```yaml
apiVersion: ray.io/v1
kind: RayCluster
metadata:
  annotations:
    ray.io/overwrite-container-cmd: "true"
  ...
spec:
  headGroupSpec:
    rayStartParams: 
        resources: '"{\"custom-rec1\": 1, \"custom-rec2\": 10}"'
    template:
      spec:
        containers:
        - name: ray-head
          image: rayproject/ray:2.8.0
          command: ["/bin/bash", "-lc", "--"]
          args: ["ulimit -n 65536; echo head; $KUBERAY_GEN_RAY_START_CMD"]
          ...
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
