### ISSUE TITLE
[Doc] `ray job submit -- echo aaa; echo bbb` and `echo aaa` will be executed in the cluster but `echo bbb` will be executed in the submitter

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#3802]
### Search before asking

- [x] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

TODO

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by a-pichard** [comment]
Hello, i use to start a bunch of RayJob and my entrypoints contain multiple statements like
`entrypoint: "echo abc && echo bbb; echo hello"`.
Since i upgraded from 1.2.2 to 1.4.1 i noticed this change. To me it is bug to fix, not something to document (I'm referring to [Doc] in the title).

From the example i shared above, only the first cmd will be executed on the head (incluster), the other ones will be executed on the submitter which makes no sense from the RayJob user perspective.

**Comment by a-pichard** [comment]
The command/args in the submitter used to look like this in 1.2.2

```yaml
  containers:
  - command:
    - ray
    - job
    - submit
    - --address
    - http://experiment-my-exp-ca58-head-svc.my-namespace.svc.cluster.local:8265
    - --submission-id
    - experiment-my-exp-ca58-tpmwm
    - --
    - python
    - /app/main.py
    - --someflag
    - a
    - --someother-flag
    - b
    - '&&' # quote part of the string value, not yaml
    - echo
    - hello
```

Now in 1.4.1 it looks like this

```yaml
spec:
  containers:
  - args:
    - if ! ray job status --address http://experiment-my-exp-ca58-head-svc.my-ns.svc.cluster.local:8265
      experiment-my-exp-ca58-7j72w >/dev/null 2>&1 ; then ray job submit --address
      http://experiment-my-exp-ca58-head-svc.my-ns.svc.cluster.local:8265
      --no-wait --submission-id experiment-my-exp-ca58-7j72w -- python /app/main.py
      --someflag a --someother-flag b && echo hello ; fi ; ray job
      logs --address http://experiment-my-exp-ca58-head-svc.my-ns.svc.cluster.local:8265
      --follow  experiment-my-exp-ca58-7j72w
    command:
    - /bin/bash
    - -ce
    - --
```

We can understand that starting from `&& echo hello` we escape the `ray submit` context and see that everything is getting executed afterwards is just executed in the submitter.

I believe this is a regression from https://github.com/ray-project/kuberay/pull/2949

**Comment by a-pichard** [comment]
If we pass the entrypoint in quotes like

```
then ray job submit --address http://experiment-my-exp-ca58-head-svc.my-ns.svc.cluster.local:8265 --no-wait --submission-id experiment-my-exp-ca58-7j72w -- '{entrypoint}' ; fi 
```

```
then ray job submit --address http://experiment-my-exp-ca58-head-svc.my-ns.svc.cluster.local:8265 --no-wait --submission-id experiment-my-exp-ca58-7j72w -- 'python /app/main.py --someflag a --someother-flag b && echo hello' ; fi 
```

Do you think it would solve the issue while keeping the fix for quotes mentioned in #2949 ?


If we do that, we may need to omit `--`

**Comment by a-pichard** [comment]
hello @kevin85421 any update on this ?

**Comment by Future-Outlier** [comment]
Since I am contributing to RayJob controller, I think I can investigate this.

**Comment by Future-Outlier** [comment]
Hi, @a-pichard 
Do you mind take a look at this PR and verify is this what you want?
https://github.com/ray-project/kuberay/pull/4052

**Comment by a-pichard** [comment]
That seems like a nice fix! 
Could you execute the 3 echo but also with $HOSTNAME, just to make sure that it actually prints the head's name.

**Comment by Future-Outlier** [comment]
> That seems like a nice fix! Could you execute the 3 echo but also with $HOSTNAME, just to make sure that it actually prints the head's name.

it works now, let me discuss with other maintainer, thank you!

<img width="1145" height="409" alt="Image" src="https://github.com/user-attachments/assets/2fb8c5f7-c99b-4f85-92c3-876c5d84abe7" />

**Comment by Future-Outlier** [comment]
> That seems like a nice fix! Could you execute the 3 echo but also with $HOSTNAME, just to make sure that it actually prints the head's name.

Hi, @a-pichard 

After discussing with @rueian,
I realized that we should keep the behavior the same, since this is how ray job submit works in the Ray repo now.
We should align with how the Ray repo works.
The reason we are not going to change this is that we want to let the user decide whether to use `bash -c `or not, which is more flexible.


To support your use case, I suggest you change your entrypoint in the yaml file to 
```yaml
apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: rayjob-sample
spec:
  entrypoint: bash -c 'echo $HOSTNAME; echo $HOSTNAME; echo $HOSTNAME'
```

<img width="1205" height="435" alt="Image" src="https://github.com/user-attachments/assets/0036b114-4655-4d1a-9f06-cfc2634942d3" />

**Comment by a-pichard** [comment]
First, single quotes `'` are replaced by double by ray submit, so some things are getting escaped

Second, I tested this, this works for simple commands like these ones by i face some issue when i get into some more complex ones.

For example i am executing: 

```yaml
apiVersion: ray.io/v1
kind: RayJob
metadata:
spec:
  entrypoint: /bin/bash -c 'export VSCODE_TUNNEL_NAME=eb4d7883-3aa5-$(LC_ALL=C tr
    -dc '\''a-zA-Z0-9'\'' < /dev/urandom | fold -w 5 | head -n 1) && (/opt/code
    tunnel user login --provider github && /opt/code tunnel --name ${VSCODE_TUNNEL_NAME})
    & sleep 43200 ; kill $!'
```

which translates into the submitter's args like
```yaml
    args:
    - if ! ray job status --address http://experiment-eb4d7883-3aa5-head-svc.adr-smoke-gl-bab6f11756984a0e.svc.cluster.local:8265
      experiment-eb4d7883-3aa5-hc85w >/dev/null 2>&1 ; then ray job submit --address
      http://experiment-eb4d7883-3aa5-head-svc.adr-smoke-gl-bab6f11756984a0e.svc.cluster.local:8265
      --no-wait --submission-id experiment-eb4d7883-3aa5-hc85w -- /bin/bash -c 'export
      VSCODE_TUNNEL_NAME=eb4d7883-3aa5-$(LC_ALL=C tr -dc '\''a-zA-Z0-9'\'' < /dev/urandom
      | fold -w 5 | head -n 1) && (/opt/code tunnel user login --provider github
      && /opt/code tunnel --name ${VSCODE_TUNNEL_NAME}) & sleep 43200 ; kill $!'
      ; fi ; ray job logs --address http://experiment-eb4d7883-3aa5-head-svc.adr-smoke-gl-bab6f11756984a0e.svc.cluster.local:8265
      --follow experiment-eb4d7883-3aa5-hc85w
```

Then in the head when i list processes i get

```sh
>  ps -aux
...
# here we can see that the command seems fine but as stated above, somehow the `'` got transformed into `"`
/bin/sh -c /bin/bash -c "export VSCODE_TUNNEL_NAME=eb4d7883-3aa5-$(LC_ALL=C tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w 5 | head -n 1) && (/opt/code tunnel user login --provider github && /opt/code tunnel --name ${VSCODE_TUNNEL_NAME}) & sleep 43200 ; kill $!"
...
```

but then i got

```sh
>  ps -aux
...
# VSCODE_TUNNEL_NAME env var got properly created
# but then the ${VSCODE_TUNNEL_NAME} env var got interpreted too early and disappeared since it got interpreted in the wrong context due to switched quotes ' -> "
/bin/bash -c export VSCODE_TUNNEL_NAME=eb4d7883-3aa5-T5LTd && (/opt/code tunnel user login --provider github && /opt/code tunnel --name ) & sleep 43200 ; kill
...
```

**Comment by Future-Outlier** [comment]
Hi, @a-pichard 
I will investigate this before the release of kuberay 1.15.0, do you mind try this PR to see if it supports your use case if you are urgent?
https://github.com/ray-project/kuberay/pull/3943

**Comment by seanlaii** [comment]
I can also help take a look👍

**Comment by a-pichard** [comment]
Hi @Future-Outlier i confirm that my 'complex' use-case works fine with the submitter software.

For reference i'm doing:

```yaml
apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: experiment-9a1b4d22-d82f
  namespace: smok-adr-76afdcae14eb4f54
spec:
  backoffLimit: 0
  entrypoint: export VSCODE_TUNNEL_NAME=9a1b4d22-d82f-$(LC_ALL=C tr -dc 'a-zA-Z0-9'
    < /dev/urandom | fold -w 5 | head -n 1) && (/opt/code tunnel user login --provider
    github && /opt/code tunnel --name ${VSCODE_TUNNEL_NAME}) & sleep 43200 ; kill
    $!
  rayClusterSpec:
  ...
  submitterPodTemplate:
    spec:
      containers:
      - args:
        - --
        - export VSCODE_TUNNEL_NAME=9a1b4d22-d82f-$(LC_ALL=C tr -dc 'a-zA-Z0-9' <
          /dev/urandom | fold -w 5 | head -n 1) && (/opt/code tunnel user login
          --provider github && /opt/code tunnel --name ${VSCODE_TUNNEL_NAME}) &
          sleep 43200 ; kill $!
        command:
        - /submitter
        image: kuberay-submitter:latest
        name: submitter
        resources: {}
      restartPolicy: Never
      serviceAccountName: default
```
