### ISSUE TITLE
[Bug] RayService controller doesn't seem to respect the deploymentUnhealthySecondThreshold value on the first run

### ISSUE THREAD

**Issue by jianyuan** [ray-project/kuberay#539]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

The RayService controller doesn't seem to respect the `deploymentUnhealthySecondThreshold` value on the first run.

Our deployment has a slow `__init__`/`reconfigure` method. During initialisation, we get the following warning in console:
> Deployment MyDeployment has 2 replicas that have taken more than 30s to initialize. This may be caused by a slow __init__ or reconfigure method.

The controller kills the deployment after 60 seconds.

Changing `deploymentUnhealthySecondThreshold` doesn't seem to influence the timeout.

### Reproduction script

```python
import time

@serve.deployment
class MyDeployment:
    def __init__(self):
        time.sleep(120)

    def __call__(self, request):
        return True
```

```yaml
apiVersion: ray.io/v1alpha1
kind: RayService
metadata:
  name: my-inference
spec:
  serviceUnhealthySecondThreshold: 240 # Config for the health check threshold for service. Default value is 60.
  deploymentUnhealthySecondThreshold: 240 # Config for the health check threshold for deployments. Default value is 60.
  serveConfig:
    importPath: serving:my_service
    deployments:
      - name: my-deployment
        numReplicas: 1
        routePrefix: /
# ...
```

### Anything else

I suspect the issue is with this method call:

https://github.com/ray-project/kuberay/blob/5254dcae5c803224674ed1fea10264f6265c5446/ray-operator/controllers/ray/rayservice_controller.go#L765

The last parameter is set to `nil` instead of `rayServiceInstance.Spec.DeploymentUnhealthySecondThreshold` like here:

https://github.com/ray-project/kuberay/blob/5254dcae5c803224674ed1fea10264f6265c5446/ray-operator/controllers/ray/rayservice_controller.go#L711

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!
