### ISSUE TITLE
[Bug][RayJobs] Ray spawns more pods than threshold (Max Workers for specific Group).

### ISSUE THREAD

**Issue by peterghaddad** [ray-project/kuberay#560]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

Others

### What happened + What you expected to happen

During worker pod termination after a Ray Job, the cluster will try respawning new workers and it will start to scale above the threshold. I've seen Ray clusters scale to over workers 100 pods due to this issue when the threshold is at 25.

The `workersToDelete:` array continues to grow and more pods continue to spawn. Not that the threshold is only `5` for this type of worker.

I think it's because the Ray Workers get stuck in a terminating state, so it tries to respawn them to gracefully terminate. This behavior happens randomly and isn't after every job. Is there a way for to tell the autoscaler to not spawn additional pods if the `replicas` are equal to maxWorkers?

### Reproduction script
```
apiVersion: ray.io/v1alpha1
kind: RayCluster
metadata:
  name: raycluster-complete
  namespace: ray
  labels:
    controller-tools.k8s.io: '1.0'
spec:
  enableInTreeAutoscaling: true
  headGroupSpec:
    rayStartParams:
      port: '6379'
      dashboard-host: 0.0.0.0
      node-manager-port: '9998'
      block: 'true'
      no-monitor: 'true'
      num-gpus: '0'
      object-manager-port: '9999'
      node-ip-address: $MY_POD_IP
      object-store-memory: '100000000'
    replicas: 1
    serviceType: ClusterIP
    template:
      metadata:
        labels:
          groupName: headgroup
          rayCluster: raycluster
          rayNodeType: head
      spec:
        containers:
          - env:
              - name: CPU_REQUEST
                valueFrom:
                  resourceFieldRef:
                    containerName: ray-head
                    resource: requests.cpu
              - name: CPU_LIMITS
                valueFrom:
                  resourceFieldRef:
                    containerName: ray-head
                    resource: limits.cpu
              - name: MEMORY_LIMITS
                valueFrom:
                  resourceFieldRef:
                    containerName: ray-head
                    resource: limits.memory
              - name: MEMORY_REQUESTS
                valueFrom:
                  resourceFieldRef:
                    containerName: ray-head
                    resource: requests.memory
              - name: MY_POD_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.podIP
            image: 'rayproject/ray:2.0.0-py39'
            imagePullPolicy: Always
            lifecycle:
              preStop:
                exec:
                  command:
                    - /bin/sh
                    - '-c'
                    - ray stop
            name: ray-head
            ports:
              - containerPort: 6379
                name: gcs
                protocol: TCP
              - containerPort: 8265
                name: dashboard
                protocol: TCP
              - containerPort: 10001
                name: client
                protocol: TCP
            resources:
              limits:
                cpu: '20'
                memory: 20Gi
              requests:
                cpu: '10'
                memory: 20Gi
  rayVersion: 2.0.0
  workerGroupSpecs:
    - groupName: cpu-group
      maxReplicas: 15
      minReplicas: 0
      rayStartParams:
        block: 'true'
        node-ip-address: $MY_POD_IP
        num-gpus: '0'
      replicas: 0
      template:
        spec:
          containers:
            - env:
                - name: RAY_DISABLE_DOCKER_CPU_WARNING
                  value: '1'
                - name: TYPE
                  value: worker
                - name: CPU_REQUEST
                  valueFrom:
                    resourceFieldRef:
                      containerName: ray-worker
                      resource: requests.cpu
                - name: CPU_LIMITS
                  valueFrom:
                    resourceFieldRef:
                      containerName: ray-worker
                      resource: limits.cpu
                - name: MEMORY_LIMITS
                  valueFrom:
                    resourceFieldRef:
                      containerName: ray-worker
                      resource: limits.memory
                - name: MEMORY_REQUESTS
                  valueFrom:
                    resourceFieldRef:
                      containerName: ray-worker
                      resource: requests.memory
                - name: MY_POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: MY_POD_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.podIP
              image: 'rayproject/ray:2.0.0-py39-9'
              lifecycle:
                preStop:
                  exec:
                    command:
                      - /bin/sh
                      - '-c'
                      - ray stop
              name: ray-worker
              ports:
                - containerPort: 80
                  protocol: TCP
              resources:
                limits:
                  cpu: '18'
                  memory: 28Gi
                requests:
                  cpu: '18'
                  memory: 28Gi
              volumeMounts:
                - mountPath: /var/log
                  name: log-volume
          initContainers:
            - command:
                - sh
                - '-c'
                - >-
                  until nslookup $RAY_IP.$(cat
                  /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local;
                  do echo waiting for myservice; sleep 2; done
              image: 'busybox:1.28'
              name: init-myservice
          volumes:
            - emptyDir: {}
              name: log-volume
    - groupName: gpu-group
      maxReplicas: 5
      minReplicas: 0
      rayStartParams:
        block: 'true'
        node-ip-address: $MY_POD_IP
        num-gpus: '1'
      replicas: 9
      scaleStrategy:
        workersToDelete:
          - raycluster-complete-worker-gpu-group-tm72g
          - raycluster-complete-worker-gpu-group-tm71g
          - raycluster-complete-worker-gpu-group-tm42g
          - raycluster-complete-worker-gpu-group-tm32g
          - raycluster-complete-worker-gpu-group-tm62g
          - raycluster-complete-worker-gpu-group-tm22g 
          - raycluster-complete-worker-gpu-group-tm52g
          - raycluster-complete-worker-gpu-group-tm12g
          - raycluster-complete-worker-gpu-group-tm32g
          containers:
            - env:
                - name: RAY_DISABLE_DOCKER_CPU_WARNING
                  value: '1'
                - name: TYPE
                  value: worker
                - name: CPU_REQUEST
                  valueFrom:
                    resourceFieldRef:
                      containerName: ray-worker-gpu
                      resource: requests.cpu
                - name: CPU_LIMITS
                  valueFrom:
                    resourceFieldRef:
                      containerName: ray-worker-gpu
                      resource: limits.cpu
                - name: MEMORY_LIMITS
                  valueFrom:
                    resourceFieldRef:
                      containerName: ray-worker-gpu
                      resource: limits.memory
                - name: MEMORY_REQUESTS
                  valueFrom:
                    resourceFieldRef:
                      containerName: ray-worker-gpu
                      resource: requests.memory
                - name: MY_POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: MY_POD_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.podIP
              image: 'rayproject/ray:2.0.0-py39-cu111'
              lifecycle:
                preStop:
                  exec:
                    command:
                      - /bin/sh
                      - '-c'
                      - ray stop
              name: gpu
              ports:
                - containerPort: 80
                  protocol: TCP
              resources:
                limits:
                  cpu: 20
                  memory: 20Gi
                  nvidia.com/gpu: 1
                requests:
                  cpu: 1
                  memory: 20Gi
                  nvidia.com/gpu: 1
              volumeMounts:
                - mountPath: /var/log
                  name: log-volume
          initContainers:
            - command:
                - sh
                - '-c'
                - >-
                  until nslookup $RAY_IP.$(cat
                  /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local;
                  do echo waiting for myservice; sleep 2; done
              image: 'busybox:1.28'
              name: init-myservice
          volumes:
            - emptyDir: {}
              name: log-volume
```

### Anything else

Running Ray 2.0 with the latest stable Kuberay Operator.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
I think one important item here is to investigate why termination takes so long:
https://github.com/ray-project/kuberay/issues/503

Another important item is to make sure there aren't races between end-of-job cluster termination and pod creation.

**Comment by DmitriGekhtman** [comment]
cc @harryge00

**Comment by peterghaddad** [comment]
@DmitriGekhtman and @harryge00 wanted to politely follow up. Any thoughts on this functionality for having the autoscaler not try and spawn pods until they are fully terminated, not in a terminating state?

**Comment by DmitriGekhtman** [comment]
Thanks for your patience.

Here's a proposed solution: 
Add a flag to the ** kuberay operator** that instructs the raycluster controller to avoid having >=maxWorkers total (terminating or not) pods.
In this setup, the autoscaler's requests to add an unexpected number of pods would simply be ignored.

The required logic should be straightforward to implement -- I'll have a shot at it this week.

**Comment by harryge00** [comment]
I am trying to reproduce this problem. @peterghaddad Could you also provide the `Rayjob` yaml? The script you posted is actually a `RayCluster` yaml

**Comment by peterghaddad** [comment]
I think safe guards are the way to go. @DmitriGekhtman 

This is with multiple types of jobs and I am submitting through the JobSubmissionSDK. This problem usually occurs when pods are terminating but the autoscaler tries to spin new ones up. This causing tons of pods to spawn. I believe the autoscaler is what controls this? Hope that clarifies some things!

**Comment by DmitriGekhtman** [comment]
We may need to tighten up autoscaling logic as well. From the autoscaler logs posted above, it seems very unusual that the number of GPU nodes is increasing, but there are no log messages indicating that nodes are being scaled up.

If you see this behavior again, it would be great to see the autoscaler logs
```
kubectl logs <head-pod> -c autoscaler
```
or `/tmp/ray/session_latest/logs/monitor.*` in the head node's autoscaler or ray container. (The log directory is mounted into both containers.)

**Comment by DmitriGekhtman** [comment]
The output of `ray status` from within the Ray cluster is also very useful.

**Comment by DmitriGekhtman** [comment]
Finally, I'll mention that autoscaling is an optional feature -- if you know the total required Ray nodes for your job, it may be better to run a statically sized cluster and terminate the cluster once the job is done.

**Comment by peterghaddad** [comment]
@DmitriGekhtman Our cluster is not static since we are running on Kubernetes. The pods are in a terminating state and it seems that it tries to respawn the pod leaving the terminating one stuck for a while. The delays causes the Cluster to exceed those limits due to the rapid growth.

**Comment by DmitriGekhtman** [comment]
> @DmitriGekhtman We are using Ray for the dynamic scalability features. The autoscaler is beneficial.

Sounds good, ok!

> The pods are in a terminating state and it seems that it tries to respawn the pod leaving the terminating one stuck for a while.

It would be great to diagnose the cause of this behavior! Autoscaler logs and `ray status` output appreciated.
Why the autoscaler is trying to terminate and create nodes in rapid succession is important to understand.

I'll mention that I do have some ideas in general on improving the structure of autoscaling logic such that
(a) we're more confident that the autoscaler is making correct decisions
(b) the decisions are easily explainable and observable
(This is not to say I'm aware yet of any race conditions causing the currently observed behavior.)

**Comment by peterghaddad** [comment]
```
$ ray status
======== Autoscaler status: 2022-10-11 14:32:56.726898 ========
Node status
---------------------------------------------------------------
Healthy:
 1 head-group
Pending:
 IP not yet assigned: gpu-group, waiting
 IP not yet assigned: gpu-group, waiting
 IP not yet assigned: gpu-group, waiting
 IP not yet assigned: gpu-group, waiting
 IP not yet assigned: gpu-group, waiting
 IP not yet assigned: gpu-group, waiting
 IP not yet assigned: gpu-group, waiting
 IP not yet assigned: gpu-group, waiting
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/20.0 CPU
 0.0/1.0 {{stripped_out}}
 0.00/20.000 GiB memory
 0.00/0.093 GiB object_store_memory

Demands:
 (no resource demands)
```

Additionally, I was able to reproduce the same problem without launching a job.

I re-launched a Ray Cluster, set maxReplicas: 10, minReplicas: 12, and replicas to 12. This caused the Cluster to get into the same state that we were experiencing when launching jobs. Unsure how it gets into this state when a Job is launched (i.e not manually).

**Comment by DmitriGekhtman** [comment]
```
maxReplicas: 10, minReplicas: 12, and replicas to 12
```
Ideally, K8s or the operator would reject this configuration, since max > min.

Do you mean minReplicas=10, maxReplicas=12?

**Comment by DmitriGekhtman** [comment]
Concerning this config snippet from the issue description:
```
    - groupName: gpu-group
      maxReplicas: 5
      minReplicas: 0
      rayStartParams:
        block: 'true'
        node-ip-address: $MY_POD_IP
        num-gpus: '1'
      replicas: 9
      scaleStrategy:
```

I see replicas is greater than maxReplicas, which is most concerning.
At the time of deploying the configuration was it the case that replicas=minReplicas=0?
