### ISSUE TITLE
[Feature] Customise Ray head service in RayCluster CR

### ISSUE THREAD

**Issue by sigmundv** [ray-project/kuberay#625]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

I would like to be able to customise the Ray head service that's created as part of the RayCluster CR. See the use case below for more details.

### Use case

I'm using KubeRay to deploy a Ray cluster to Kubernetes. To enable TLS between pods I'm using Open Service Mesh (OSM), and to make Ray work I need to add a field `appProtocol` to the ports in the head service (see YAML below). I can do this by patching the service after it has been created, but it would be good to have a way to customise the service in the RayCluster CR.

```yaml

ports:
  - appProtocol: tcp
    name: client
    port: 10001
    protocol: TCP
    targetPort: 10001
  - appProtocol: tcp
    name: dashboard
    port: 8265
    protocol: TCP
    targetPort: 8265
  - appProtocol: tcp
    name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  - appProtocol: tcp
    name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
