### ISSUE TITLE
[Bug] Head Node service is not getting exposed on Internal Load Balancer despite proper annotations

### ISSUE THREAD

**Issue by snow01** [ray-project/kuberay#637]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

I am trying to set up the head node service exposed as LoadBalancer but on an internal one, but KubeRay is still using public LoadBalancer despite giving proper annotations. 

I have all the necessary modules installed in my EKS cluster, such as AWS Load Balancer, and I also have a sample service working to expose internal LoadBalancer. That way, I know my annotations are correct.

For the ray cluster setup, I have given annotations both at the top level and within the template - hoping it will be picked from one of them.

Pls see the config snippet below.

### Reproduction script

```
apiVersion: ray.io/v1alpha1
kind: RayCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: ${RAY_CLUSTER}
  namespace: ${RAY_CLUSTER_NS}
  annotations:
   service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
   service.beta.kubernetes.io/aws-load-balancer-scheme: internal
   service.beta.kubernetes.io/aws-load-balancer-internal: "0.0.0.0/0"
   service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
spec:
  rayVersion: '2.0.0'
  enableInTreeAutoscaling: true

  autoscalerOptions:
    upscalingMode: Default
resources.
    idleTimeoutSeconds: 60
    imagePullPolicy: Always
required.
    resources:
      limits:
        cpu: "1"
        memory: "2Gi"
      requests:
        cpu: "1"
        memory: "2Gi"
  ######################headGroupSpec#################################
  headGroupSpec:
    serviceType: LoadBalancer
    enableIngress: true

    rayStartParams:
      # Flag "no-monitor" will be automatically set when autoscaling is enabled.
      dashboard-host: '0.0.0.0'
      block: 'true'
      num-cpus: '0' # can be auto-completed from the limits
    template:
      metadata:
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
          service.beta.kubernetes.io/aws-load-balancer-scheme: internal
          service.beta.kubernetes.io/aws-load-balancer-internal: "0.0.0.0/0"
          service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
...
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
