### ISSUE TITLE
[Bug] Fail to create ingress due to the deprecation of the ingress.class annotation 

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#645]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

Thank @rokiyer for pointing this out! 

This issue is not totally same as #441, and thus I opened a new issue. Users cannot create `ingress` with the instructions in https://ray-project.github.io/kuberay/guidance/ingress/. The operator also reports the error message:

```
2022-10-18T00:34:38.187Z	ERROR	controllers.RayCluster	Ingress create error!	{"Ingress.Error": "Ingress.extensions \"raycluster-ingress-head-ingress\" is invalid: annotations.kubernetes.io/ingress.class: Invalid value: \"nginx\": can not be set when the class field is also set", "error": "Ingress.extensions \"raycluster-ingress-head-ingress\" is invalid: annotations.kubernetes.io/ingress.class: Invalid value: \"nginx\": can not be set when the class field is also set"}
github.com/ray-project/kuberay/ray-operator/controllers/ray.(*RayClusterReconciler).reconcileIngress
	/workspace/controllers/ray/raycluster_controller.go:256
github.com/ray-project/kuberay/ray-operator/controllers/ray.(*RayClusterReconciler).rayClusterReconcile
	/workspace/controllers/ray/raycluster_controller.go:192
github.com/ray-project/kuberay/ray-operator/controllers/ray.(*RayClusterReconciler).Reconcile
	/workspace/controllers/ray/raycluster_controller.go:97
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227
```

As shown in the following code snippet, the error message is reported by the function `ValidateIngressCreate` ([Link](https://github.com/kubernetes/kubernetes/blob/v1.23.6/pkg/apis/networking/validation/validation.go#L243-L246)) in Kubernetes. When both `annotations.kubernetes.io/ingress.class` and `spec.IngressClassName` are set at the same time, the validation function will report the error "can not be set when the class field is also set". 

```go
if annotationIsSet && ingress.Spec.IngressClassName != nil {
   annotationPath := field.NewPath("annotations").Child(annotationIngressClass)
   allErrs = append(allErrs, field.Invalid(annotationPath, annotationVal, "can not be set when the class field is also set"))
}
```

In [doc](https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation), it indicates that `annotations.kubernetes.io/ingress.class` was deprecated in Kubernetes 1.18, and `spec.ingressClassName` is a replacement for this annotation.

### Reproduction script
```
apiVersion: ray.io/v1alpha1
kind: RayCluster
metadata:
  name: raycluster-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rayVersion: '2.0.0' # should match the Ray version in the image of the containers
  headGroupSpec:
    serviceType: NodePort
    enableIngress: true
    replicas: 1
    rayStartParams:
      port: '6379'
      dashboard-host: '0.0.0.0'
      num-cpus: '1' # can be auto-completed from the limits
      node-ip-address: $MY_POD_IP # auto-completed as the head pod IP
    #pod template
    template:
      spec:
        containers:
        - name: ray-head
          image: rayproject/ray:2.0.0
          env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          ports:
          - containerPort: 6379
            name: gcs-server
          - containerPort: 8265 # Ray dashboard
            name: dashboard
          - containerPort: 10001
            name: client
```

* Deploy the RayCluster YAML file, and the head pod will not be created.
* Use `kubectl logs` to check the error messages reported by operator.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!
