### ISSUE TITLE
[Bug?][Documentation] nginx Ingress for client times out

### ISSUE THREAD

**Issue by tbukic** [ray-project/kuberay#729]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

Others

### What happened + What you expected to happen

Wrapping up [this](https://ray-distributed.slack.com/archives/C02GFQ82JPM/p1668430849201679) discussion:

I'm still not sure if this is a bug or just me misunderstanding documentation, but when I try to access ray Client via Ingress `client.[hostname]`; command: `ray.init("ray://client.[hostname]")` I get timeout errors.

### Reproduction script

For the comparison, this configuration renders dashboard just fine:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-ingress-dashboard 
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: dashboard.{{ .Values.hostRoot }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.name }}-head-svc
                port:
                  name: dashboard 
```

Configurations that fails are

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-ingress-client
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/server-snippet: |
      underscores_in_headers on;
      ignore_invalid_headers on;
spec:
  rules:
    - host: client.{{ .Values.hostRoot }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.name }}-head-svc
                port:
                  name: client
```

and

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-ingress-client
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/server-snippet: |
      underscores_in_headers on;
      ignore_invalid_headers on;
spec:
  ingressClassName: nginx
  rules:
    - host: client.{{ .Values.hostRoot }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.name }}-head-svc
                port:
                  number: 10001
  tls:
  - hosts:
      - client.{{ .Values.hostRoot }}
    secretName: {{ .Values.httpsSecretName }}
```
(and without tls as well :) ). My efforts up to now were inspired by [this](https://discuss.ray.io/t/doesnt-work-ray-client-on-k8s-with-ingress/3160/2) example - which is basically [this](https://docs.ray.io/en/latest/cluster/running-applications/job-submission/ray-client.html#connection-through-the-ingress) paragraph from the documentation - and by @kevin85421 's comments on Slack.

### Anything else

I'd prefer to access client in the form of `client.[host]`, thus I don't follow [existing example for exposing dashboard](https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/ray-cluster.separate-ingress.yaml#L38-L62). Also, my dashboard works fine; as well as client when it's port-forwarded from either pod or service and accessed via `localhost:[port]`. I want maximally simplify access to client for DS colleagues who don't use k8s, so I'm trying to skip kubectl and port-forwarding.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
