### ISSUE TITLE
[Bug] [Ray Cluster] Installing cluster with Helm chart results in workers not connecting to head node

### ISSUE THREAD

**Issue by ecm200** [ray-project/kuberay#770]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

Others

## Problem Summary

This is in relation to starting a `ray cluster` on Kubernetes using the `KubeRay` operator and ray-cluster helm charts.

I successfully stand up a `kuberay operator` using the latest helm chart.

I then start a `ray-cluster` using the latest helm chart, with changed values for an autoscaling cluster.

When the worker nodes are scaling in at the start, the autoscaler reports the status correctly:

```
======== Autoscaler status: 2022-11-29 04:07:22.923348 ========
Node status
---------------------------------------------------------------
Healthy:
 1 head-group
Pending:
 IP not yet assigned: largeGroup, pending
 IP not yet assigned: workergroup, pending
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.00/2.794 GiB memory
 0.00/0.758 GiB object_store_memory

Demands:
 (no resource demands)
```

However, once the containers are spun up, the workers disappear from the ray status page, and not shown as a resource.

Connecting to a running worker node which is not shown in the `ray status` summary, shows they are failing to connect  to the head node due to errors connecting to the head node GCS port (as reported by the logs). This appears to be related to the `head-node-svc` which it cannot get a connection on the GCS port.

```
2022-11-29 04:10:27,409	WARNING utils.py:1346 -- Unable to connect to GCS at itc-raycluster-head-svc:6379. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.
```

Looking at the service definition, it is clear from the service information, that for some reason the `head-node-svc` service has not successfully attached to the head node, and is therefore not giving an entry point to the head node. Even though the service definition looks to have the right ports specified:

![image](https://user-images.githubusercontent.com/34489160/204528287-b612b702-4af0-47e7-b2a8-8b574aded497.png)

Lens information shows that the endpoints are not connected properly.

![image](https://user-images.githubusercontent.com/34489160/204528161-03033a78-18af-4b7e-9e71-9c690dc2fb50.png)

It is also not possible to connect to the head node dashboard via the service (on port 8265).

**So, on the face of it, this appears to be an issue with the configuration of the head node ports, or the `IPCluster` service that is attaching to the head node.**

## Further investigation using equivalent `kubectl apply` and `yaml` cluster definition

To make sure this wasn't issues with operator setup or indeed my custom ray image, I created an equivalent autoscaling `ray-cluster` using the `yaml` definition and the `kubectl apply` command, and this results in the cluster starting without issue and operating as expected. I have tried to make the helm chart and the `yaml` definition files equivalent in parameterization.

When looking at the service, it shows a connection the head node, with endpoints, and it is possible to connect to the dashboard. The worker nodes also successfully attach to the head node, and there are no GCS errors.

```
======== Autoscaler status: 2022-11-29 04:31:37.518227 ========
Node status
---------------------------------------------------------------
Healthy:
 1 head-group
 1 default-group
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/15.0 CPU
 0.00/57.481 GiB memory
 0.00/17.136 GiB object_store_memory

Demands:
 (no resource demands)
```

![image](https://user-images.githubusercontent.com/34489160/204529433-ae142444-090c-43bd-8e09-f73f45ccae31.png)

![image](https://user-images.githubusercontent.com/34489160/204529228-3d5178b1-ca99-47e2-a659-2478faf6b3b5.png)

## Commands for installing operator:

In both case, the following commands are run to start the namespaced `KubeRay` operator.

First install the CRD definitions:

`kubectl create -k "github.com/ray-project/kuberay/ray-operator/config/crd?ref=v0.3.0&timeout=90s"`

Then install the `kuberay operator` using the helm chart:

`helm install kuberay-operator --namespace ray-itc --create-namespace ./kuberay-operator-0.3.0`

## Helm chart install of `ray-cluster`:

Then install the `ray cluster` using the latest adapted helm chart:

`helm install -n ray-itc ./ray-cluster-latest`

## `yaml` install of `ray-cluster` using `kubectl`:

Install an autoscaling cluster using a YAML configuration file and `kubectl apply`. This based off and adapted version of the sample `ray-cluster.autoscaler.yaml`.

`kubectl apply -n ray-itc -f ray-cluster-dev.autoscaler.yaml` 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by ecm200** [comment]
For completeness, here is the `values.yaml` from the `ray-cluster-latest` helm chart (based on the latest commit):

```
# Default values for ray-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The KubeRay community welcomes PRs to expose additional configuration
# in this Helm chart.

image:
  repository: rayproject/ray
  tag: 2.1.0
  pullPolicy: IfNotPresent

nameOverride: "raycluster"
fullnameOverride: ""

imagePullSecrets: []
  # - name: an-existing-secret

head:
  groupName: headgroup
  rayVersion: 2.1.0
  # If enableInTreeAutoscaling is true, the autoscaler sidecar will be added to the Ray head pod.
  # Ray autoscaler integration is supported only for Ray versions >= 1.11.0
  # Ray autoscaler integration is Beta with KubeRay >= 0.3.0 and Ray >= 2.0.0.
  enableInTreeAutoscaling: true
  # autoscalerOptions is an OPTIONAL field specifying configuration overrides for the Ray autoscaler.
  # The example configuration shown below below represents the DEFAULT values.
  autoscalerOptions:
    # upscalingMode: Default
    idleTimeoutSeconds: 60
    # resources specifies optional resource request and limit overrides for the autoscaler container.
    # For large Ray clusters, we recommend monitoring container resource usage to determine if overriding the defaults is required.
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "500m"
        memory: "512Mi"
  # labels:
  #   key: value
  rayStartParams:
    dashboard-host: '0.0.0.0'
    block: 'true'
    num-cpus: '0'
  # containerEnv specifies environment variables for the Ray container,
  # Follows standard K8s container env schema.
  containerEnv: []
  # - name: EXAMPLE_ENV
  #   value: "1"
  envFrom: []
    # - secretRef:
    #     name: my-env-secret
  lifecycle:
    preStop:
      exec:
        command: ["/bin/sh","-c","ray stop"]
  # ports optionally allows specifying ports for the Ray container.
  # ports: []
  ports:
  - containerPort: 6379
    name: gcs
  - containerPort: 8265
    name: dashboard
  - containerPort: 10001
    name: client
  # resource requests and limits for the Ray head container.
  # Modify as needed for your application.
  # Note that the resources in this example are much too small for production.
  # Ray pods should be sized to take up entire K8s nodes when possible.
  resources:
    limits:
      cpu: 3
      memory: "3G"
    requests:
      cpu: 1
      memory: "1G"
  #annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  volumes:
    - name: log-volume
      emptyDir: {}
  volumeMounts:
    - mountPath: /tmp/ray
      name: log-volume
  # sidecarContainers specifies additional containers to attach to the Ray pod.
  # Follows standard K8s container spec.
  sidecarContainers: []


worker:
  # If you want to disable the default workergroup
  # uncomment the line below
  # disabled: true
  groupName: workergroup
  replicas: 1
  minReplicas: 1
  maxReplicas: 8
  type: worker
  # labels:
  #   key: value
  rayStartParams:
    block: 'true'
  initContainerImage: 'busybox:1.28'  # Enable users to specify the image for init container. Users can pull the busybox image from their private repositories.
  # containerEnv specifies environment variables for the Ray container,
  # Follows standard K8s container env schema.
  containerEnv: []
  # - name: EXAMPLE_ENV
  #   value: "1"
  envFrom: []
    # - secretRef:
    #     name: my-env-secret
  lifecycle:
    preStop:
      exec:
        command: ["/bin/sh","-c","ray stop"]
  # ports optionally allows specifying ports for the Ray container.
  # ports: []
  # resource requests and limits for the Ray head container.
  # Modify as needed for your application.
  # Note that the resources in this example are much too small for production.
  # Ray pods should be sized to take up entire K8s nodes when possible.
  resources:
    limits:
      cpu: "15"
      memory: "56000Mi"
    requests:
      cpu: "15"
      memory: "56000Mi"
  #annotations: []
  nodeSelector: {"agentpool": "raypool"}
  tolerations:
    - key: kubernetes.azure.com/scalesetpriority
      operator: "Equal"
      value: "spot"
      effect: "NoSchedule"
  affinity: {}
  volumes:
    - name: log-volume
      emptyDir: {}
  volumeMounts:
    - mountPath: /tmp/ray
      name: log-volume
  # sidecarContainers specifies additional containers to attach to the Ray pod.
  # Follows standard K8s container spec.
  sidecarContainers: []

# The map's key is used as the groupName.
# For example, key:small-group in the map below
# will be used as the groupName
additionalWorkerGroups:
  largeGroup:
    # Disabled by default
    #disabled: true
    groupName: largeworkergroup
    replicas: 0
    minReplicas: 0
    maxReplicas: 4
    type: worker
    labels: {}
    rayStartParams:
      block: 'true'
    initContainerImage: 'busybox:1.28'  # Enable users to specify the image for init container. Users can pull the busybox image from their private repositories.
  # containerEnv specifies environment variables for the Ray container,
  # Follows standard K8s container env schema.
    containerEnv: []
      # - name: EXAMPLE_ENV
      #   value: "1"
    envFrom: []
        # - secretRef:
        #     name: my-env-secret
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh","-c","ray stop"]
    # ports optionally allows specifying ports for the Ray container.
    # ports: []
    # resource requests and limits for the Ray head container.
    # Modify as needed for your application.
    # Note that the resources in this example are much too small for production.
    # Ray pods should be sized to take up entire K8s nodes when possible.
    resources:
      limits:
        cpu: "31"
        memory: "110000Mi"
      requests:
        cpu: "31"
        memory: "110000Mi"
    #annotations: []
    nodeSelector: {"agentpool": "raypoollarge"}
    tolerations:
    - key: kubernetes.azure.com/scalesetpriority
      operator: "Equal"
      value: "spot"
      effect: "NoSchedule"
    affinity: {}
    volumes:
      - name: log-volume
        emptyDir: {}
    volumeMounts:
      - mountPath: /tmp/ray
        name: log-volume
    sidecarContainers: []

service:
  type: ClusterIP

```

**Comment by ecm200** [comment]
And here is the equivalen `yaml` configuration file used with `kubectl apply` to start a cluster.

**Please note, this way of starting the cluster was successful compared to the above helm chart, which was not.**

```
# This config demonstrates KubeRay's Ray autoscaler integration.
# The resource requests and limits in this config are too small for production!
# For an example with more realistic resource configuration, see
# ray-cluster.autoscaler.large.yaml.
apiVersion: ray.io/v1alpha1
kind: RayCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    # A unique identifier for the head node and workers of this cluster.
  name: raycluster-itc
spec:
  # The version of Ray you are using. Make sure all Ray containers are running this version of Ray.
  rayVersion: '2.1.0'
  # If enableInTreeAutoscaling is true, the autoscaler sidecar will be added to the Ray head pod.
  # Ray autoscaler integration is supported only for Ray versions >= 1.11.0
  # Ray autoscaler integration is Beta with KubeRay >= 0.3.0 and Ray >= 2.0.0.
  enableInTreeAutoscaling: true
  # autoscalerOptions is an OPTIONAL field specifying configuration overrides for the Ray autoscaler.
  # The example configuration shown below below represents the DEFAULT values.
  # (You may delete autoscalerOptions if the defaults are suitable.)
  autoscalerOptions:
    # upscalingMode is "Default" or "Aggressive."
    # Conservative: Upscaling is rate-limited; the number of pending worker pods is at most the size of the Ray cluster.
    # Default: Upscaling is not rate-limited.
    # Aggressive: An alias for Default; upscaling is not rate-limited.
    upscalingMode: Default
    # idleTimeoutSeconds is the number of seconds to wait before scaling down a worker pod which is not using Ray resources.
    idleTimeoutSeconds: 60
    # image optionally overrides the autoscaler's container image.
    # If instance.spec.rayVersion is at least "2.0.0", the autoscaler will default to the same image as
    # the ray container. For older Ray versions, the autoscaler will default to using the Ray 2.0.0 image.
    ## image: "my-repo/my-custom-autoscaler-image:tag"
    # imagePullPolicy optionally overrides the autoscaler container's image pull policy.
    imagePullPolicy: Always
    # resources specifies optional resource request and limit overrides for the autoscaler container.
    # For large Ray clusters, we recommend monitoring container resource usage to determine if overriding the defaults is required.
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "500m"
        memory: "512Mi"
  ######################headGroupSpec#################################
  # head group template and specs, (perhaps 'group' is not needed in the name)
  headGroupSpec:
    # Kubernetes Service Type, valid values are 'ClusterIP', 'NodePort' and 'LoadBalancer'
    serviceType: ClusterIP
    # serviceType: LoadBalancer
    # enableIngress: true
    # serviceType: NodePort
    # the following params are used to complete the ray start: ray start --head --block ...
    rayStartParams:
      # Flag "no-monitor" will be automatically set when autoscaling is enabled.
      dashboard-host: '0.0.0.0'
      block: 'true'
      num-cpus: '0' # can be auto-completed from the limits
      # Use `resources` to optionally specify custom resource annotations for the Ray node.
      # The value of `resources` is a string-integer mapping.
      # Currently, `resources` must be provided in the specific format demonstrated below:
      # resources: '"{\"Custom1\": 1, \"Custom2\": 5}"'
    #pod template
    template:
      spec:
        containers:
        # The Ray head pod
        - name: ray-head
          image: rayclusternodes.azurecr.io/itctools-0.1.6-ray-2.1.0:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 6379
            name: gcs
          - containerPort: 8265
            name: dashboard
          - containerPort: 10001
            name: client
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","ray stop"]
          resources:
            limits:
              cpu: "3"
              memory: "3G"
            requests:
              cpu: "1"
              memory: "1G"
  
  ## DEFINE WORKER NODE GROUPS (1 TO 1 CORRESPONDANCE WITH POOLS)
  workerGroupSpecs:
  # the pod replicas in this group typed worker
  - replicas: 1
    minReplicas: 1
    maxReplicas: 8
    # logical group name, for this called small-group, also can be functional
    groupName: default-group
    # if worker pods need to be added, we can simply increment the replicas
    # if worker pods need to be removed, we decrement the replicas, and populate the podsToDelete list
    # the operator will remove pods from the list until the number of replicas is satisfied
    # when a pod is confirmed to be deleted, its name will be removed from the list below
    #scaleStrategy:
    #  workersToDelete:
    #  - raycluster-complete-worker-small-group-bdtwh
    #  - raycluster-complete-worker-small-group-hv457
    #  - raycluster-complete-worker-small-group-k8tj7
    # the following params are used to complete the ray start: ray start --block ...
    rayStartParams:
      block: 'true'
    #pod template
    template:
      metadata:
        labels:
          key: value
        # annotations for pod
        annotations:
          key: value
      spec:
        initContainers:
        # the env var $RAY_IP is set by the operator if missing, with the value of the head service name
        - name: init-myservice
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup $RAY_IP.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
        containers:
        - name: ray-itc # must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc'
          image: rayclusternodes.azurecr.io/itctools-0.1.6-ray-2.1.0:latest
          # environment variables to set in the container.Optional.
          # Refer to https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","ray stop"]
          resources:
            limits:
              cpu: "15"
              memory: "56000Mi"
            requests:
              cpu: "15"
              memory: "56000Mi"
        nodeSelector: {"agentpool": "raypool"}
        tolerations:
        - key: kubernetes.azure.com/scalesetpriority
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"

  - replicas: 0
    minReplicas: 0
    maxReplicas: 8
    # logical group name, for this called small-group, also can be functional
    groupName: small-group
    # if worker pods need to be added, we can simply increment the replicas
    # if worker pods need to be removed, we decrement the replicas, and populate the podsToDelete list
    # the operator will remove pods from the list until the number of replicas is satisfied
    # when a pod is confirmed to be deleted, its name will be removed from the list below
    #scaleStrategy:
    #  workersToDelete:
    #  - raycluster-complete-worker-small-group-bdtwh
    #  - raycluster-complete-worker-small-group-hv457
    #  - raycluster-complete-worker-small-group-k8tj7
    # the following params are used to complete the ray start: ray start --block ...
    rayStartParams:
      block: 'true'
    #pod template
    template:
      metadata:
        labels:
          key: value
        # annotations for pod
        annotations:
          key: value
      spec:
        initContainers:
        # the env var $RAY_IP is set by the operator if missing, with the value of the head service name
        - name: init-myservice
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup $RAY_IP.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
        containers:
        - name: ray-itc # must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc'
          image: rayclusternodes.azurecr.io/itctools-0.1.6-ray-2.1.0:latest
          # environment variables to set in the container.Optional.
          # Refer to https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","ray stop"]
          resources:
            limits:
              cpu: "7"
              memory: "28000Mi"
            requests:
              cpu: "7"
              memory: "28000Mi"
        nodeSelector: {"agentpool": "raypoolsmall"}
        tolerations:
        - key: kubernetes.azure.com/scalesetpriority
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"

  - replicas: 0
    minReplicas: 0
    maxReplicas: 4
    # logical group name, for this called small-group, also can be functional
    groupName: large-group
    # if worker pods need to be added, we can simply increment the replicas
    # if worker pods need to be removed, we decrement the replicas, and populate the podsToDelete list
    # the operator will remove pods from the list until the number of replicas is satisfied
    # when a pod is confirmed to be deleted, its name will be removed from the list below
    #scaleStrategy:
    #  workersToDelete:
    #  - raycluster-complete-worker-small-group-bdtwh
    #  - raycluster-complete-worker-small-group-hv457
    #  - raycluster-complete-worker-small-group-k8tj7
    # the following params are used to complete the ray start: ray start --block ...
    rayStartParams:
      block: 'true'
    #pod template
    template:
      metadata:
        labels:
          key: value
        # annotations for pod
        annotations:
          key: value
      spec:
        initContainers:
        # the env var $RAY_IP is set by the operator if missing, with the value of the head service name
        - name: init-myservice
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup $RAY_IP.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
        containers:
        - name: ray-itc # must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc'
          image: rayclusternodes.azurecr.io/itctools-0.1.6-ray-2.1.0:latest
          # environment variables to set in the container.Optional.
          # Refer to https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","ray stop"]
          resources:
            limits:
              cpu: "31"
              memory: "110000Mi"
            requests:
              cpu: "31"
              memory: "110000Mi"
        nodeSelector: {"agentpool": "raypoollarge"}
        tolerations:
        - key: kubernetes.azure.com/scalesetpriority
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: raycluster-itc-head-ingress
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - name: client
    port: 10001
    targetPort: 10001
  - name: dashboard
    port: 8265
    targetPort: 8265
  - name: api
    port: 8000
    targetPort: 8000
  selector:
    ray.io/cluster: raycluster-itc
    ray.io/identifier: raycluster-itc-head
    ray.io/node-type: head
```
