### ISSUE TITLE
[Bug] change to request and limits does not care not updated 

### ISSUE THREAD

**Issue by tekumara** [ray-project/kuberay#787]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

When I change the resource requests and limits for the head and worker groups in my raycluster CRD, the currently running head and worker pods are not updated.

### Reproduction script

_values.yaml_:
```yaml
image:
  tag: 2.0.0-py39-cpu

head:
  resources:
    limits:
      cpu: "1"
      memory: "2G"
    requests:
      cpu: "1"
      memory: "2G"

worker:
  minReplicas: 1
  maxReplicas: 10
  resources:
    limits:
      cpu: "1"
      memory: "2G"
    requests:
      cpu: "1"
      memory: "2G"
```

1. Deploy raycluster using the above _values.yaml_:
   ```
   helm upgrade --install raycluster kuberay/ray-cluster --version 0.4.0 --values values.yaml --wait --debug > /dev/null`
   ```
2. Adjust the resource requests/limits in _values.yaml_ then redeploy using the helm upgrade command above.
3. Inspect the resources and not no change:
    ```
    kubectl get pods -lapp.kubernetes.io/name=kuberay -o custom-columns=":metadata.name, :status.phase, :spec.containers[*].resources"
    ```

### Anything else

To trigger an update of the head and worker pods after changing the raycluster CRD I have to explicitly delete them, eg:
```
kubectl delete pods -lapp.kubernetes.io/name=kuberay
```

kuberay-operator nightly

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
