### ISSUE TITLE
[Bug] Cannot use repositories other than dockerhub in helm chart

### ISSUE THREAD

**Issue by tekumara** [ray-project/kuberay#847]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

Cannot use repositories other than dockerhub in helm chart

eg: _values.yaml_
```
image:
  repository: localhost:5550/ray
  tag: latest
  pullPolicy: IfNotPresent
```

Will fail:

```
    state:
      waiting:
        message: 'Failed to apply default image tag "localhost:5550/:latest": couldn''t
          parse image reference "localhost:5550/:latest": invalid reference format'
        reason: InvalidImageName
```        

### Reproduction script

Use a repository other than dockerhub in values.yaml (see example above)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!
