### ISSUE TITLE
[Feature] Helm Chart Releases in Artifact Registry

### ISSUE THREAD

**Issue by alex-treebeard** [ray-project/kuberay#862]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

I would like to be able to install kuberay via helm from an official artifact registry.

Currently I maintain [my own registry](https://github.com/orgs/treebeardtech/packages?repo_name=kuberay) based off [my kuberay fork](https://github.com/treebeardtech/kuberay/tree/alex/fixes)

This is not ideal though due to the effort required merging from upstream.

### Use case

As a kuberay user I would like to add kuberay as a helm dependency to my application charts.

I.e.

```yaml
# chart.yaml
apiVersion: v2
name: operators
type: application
version: 0.1.0
dependencies:
  - name: kuberay-apiserver
    version: 0.3.0
    repository: oci://ghcr.io/ray-project/kuberay/helm-chart
  - name: kuberay-operator
    version: 0.3.0
    repository: oci://ghcr.io/ray-project/kuberay/helm-chart
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
We have a GitHub repo [ray/kuberay-helm](https://github.com/ray-project/kuberay-helm) to host Helm charts since release 0.4.0.

I did the following experiment. 

* Step 1: Clone https://github.com/itsnashter/helm-chart-dependency
* Step 2: Create a file **database/requirements.yaml** as follows.
  ```yaml
  dependencies:
    - name: kuberay-operator
      version: 0.4.0
      repository: https://ray-project.github.io/kuberay-helm
  ```
* Step 3: Execute the following commands.
  ```sh
  helm dependency update ./service/
  helm dependency update ./service/
  helm dependency update ./application/

  helm install myapp ./application/

  # KubeRay operator has been created successfully.
  kubectl get pods | grep kuberay-operator
  # kuberay-operator-d46877b4f-ck6nn     1/1     Running            0             6m26s
  ```
