### ISSUE TITLE
[Bug] Helm CRD `RayService` workerGroup containerPort for `metrics` cannot be set

### ISSUE THREAD

**Issue by bewestphal** [ray-project/kuberay#864]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

Others

### What happened
When setting a `container.ports` name with `metrics`, the `containerPort` property is always overridden to `8080`.

This goes against the observability guide while following the kuberay docs which intends to set the port to `9001`
https://ray-project.github.io/kuberay/guidance/observability/#enable-ray-cluster-metrics

For example, this yaml:
```
containers:
    ports:
    - containerPort: 9001
      protocol: TCP
      name: metrics
    - containerPort: 80
      name: client
      protocol: TCP
```

Results with a worker pod created with this config:
```
"args": [
          "ulimit -n 65536; ray start  .....{other params}  --metrics-export-port=9001  --node-ip-address=$MY_POD_IP  --block "
        ],
        "ports": [
          {
            "name": "metrics",
            "containerPort": 8080,
            "protocol": "TCP"
          },
          {
            "name": "client",
            "containerPort": 80,
            "protocol": "TCP"
          }
        ],
```

### What you expected to happen
The pod be created with definition port with name and `containerPort` specified in the CRD `yaml`

### Consequences

Prometheus metrics will not be retrieved correctly since the port specified doesn't match the created pod.

### Current workaround. 

Set the `rayStartParams` to `metrics-export-port: "8080"`

And config to:
```
ports:
  - containerPort: 8080
    protocol: TCP
    name: metrics
```

### Reproduction script

1. The config is running on EKS
2. Kuberay v0.4.0
3. Use the default helm chart values with the port overriden
```
workerGroupSpecs:
  ...
  containers:
    .....
    ports:
      - containerPort: 9001
        protocol: TCP
        name: metrics
```
4. Created pod will have a `metrics` port with `containerPort: 8080`

### Anything else

The metrics endpoint set as the default for a reason. 
https://github.com/ray-project/kuberay/blob/87ca10adb55d90b914dc8b86a65cfd5096c8b50b/ray-operator/controllers/ray/common/constant.go#L47

I believe the fix is to either:
1. Update the kuberay observability guide to point to port `8080` instead for workers
2. Allow overrides of the `metrics` port if specified (I do not know all the implications of this change)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
