### ISSUE TITLE
[Bug] ray autoscaler keeping create and terminate worker nodes until the whole k8s cluster's resource has been occupied

### ISSUE THREAD

**Issue by Yifan122** [ray-project/kuberay#865]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

I enable the autoscaler in our kuberay, but it ends up keeping create and terminate worker nodes (especially the large cpu worker 6cpu 32Gb)until the whole k8s cluster's resource has been occupied. 

![EfXL7s4PwD](https://user-images.githubusercontent.com/30310577/212270127-0a6b2bd0-e0f3-408e-b598-0e43133568e6.jpg)

### Reproduction script

```
---
# Source: ray-cluster/templates/raycluster-service.yaml
apiVersion: v1
kind: Service
metadata:
  # labels:
  #   app.kubernetes.io/name: kuberay-metrics
  #   ray.io/cluster: ray-cluster-kuberay
  name: ray-cluster-kuberay-metrics-svc
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: kuberay
    ray.io/cluster: ray-cluster-kuberay
  type: ClusterIP
---
# Source: ray-cluster/templates/raycluster-cluster.yaml
apiVersion: ray.io/v1alpha1
kind: RayCluster
metadata:
  labels:
    app.kubernetes.io/name: kuberay
    helm.sh/chart: ray-cluster-0.3.0
    app.kubernetes.io/instance: ray-cluster
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
  name: ray-cluster-kuberay
spec:
  enableInTreeAutoscaling: true
  autoscalerOptions:
    # upscalingMode is "Default" or "Aggressive."
    # Conservative: Upscaling is rate-limited; the number of pending worker pods is at most the size of the Ray cluster.
    # Default: Upscaling is not rate-limited.
    # Aggressive: An alias for Default; upscaling is not rate-limited.
    upscalingMode: Default
    # idleTimeoutSeconds is the number of seconds to wait before scaling down a worker pod which is not using Ray resources.
    idleTimeoutSeconds: 60
    # image optionally overrides the autoscaler's container image.
    # If instance.spec.rayVersion is at least "2.0.0", the autoscaler will default to the same image as
    # the ray container. For older Ray versions, the autoscaler will default to using the Ray 2.0.0 image.
    ## image: "my-repo/my-custom-autoscaler-image:tag"
    # imagePullPolicy optionally overrides the autoscaler container's image pull policy.
    imagePullPolicy: Always
    # resources specifies optional resource request and limit overrides for the autoscaler container.
    # For large Ray clusters, we recommend monitoring container resource usage to determine if overriding the defaults is required.
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "500m"
        memory: "512Mi"

  headGroupSpec:
    serviceType: ClusterIP
    rayStartParams:
      block: "true"
      dashboard-host: "0.0.0.0"
      node-ip-address: "$MY_POD_IP"
      num-cpus: "1"
      port: "6379"
      redis-password: "LetMeInRay"
    replicas: 1
    template:
      spec:
        imagePullSecrets:
          - name: harbor-bybit
          - name: harbor-infra
        containers:
          - volumeMounts:
            - mountPath: /tmp/ray
              name: log-volume
            name: ray-head
            image: harbor.infra.ww5sawfyut0k.bitsvc.io/bigdata/ray:prod-2.0.1-py38-ai2.0
            imagePullPolicy: Always
            resources:
              limits:
                cpu: 4
                memory: 8Gi
              requests:
                cpu: 2
                memory: 2Gi
            env:
              - name: TYPE
                value: head
              - name: MY_POD_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.podIP
              - name: MLFLOW_TRACKING_URI
                value: http://mlflow.niubit.io
              - name: PLATFORM_ENV
                value: prod
              - name: HDFS_CLUSTER_NAME
                value: victoria
              - name: RAY_OVERRIDE_RESOURCES
                value: '{"CPU":0, "GPU":0}'
        volumes:
          - emptyDir: {}
            name: log-volume
        affinity:
          {}
        tolerations:
          []
        nodeSelector:
          {}
      metadata:
        annotations:
          {}
        labels:
          groupName: headgroup
          rayNodeType: head
          rayCluster: ray-cluster-kuberay
          app.kubernetes.io/name: kuberay
          helm.sh/chart: ray-cluster-0.3.0
          app.kubernetes.io/instance: ray-cluster
          app.kubernetes.io/version: "1.0"
          app.kubernetes.io/managed-by: Helm

  workerGroupSpecs:
  - rayStartParams:
      block: "true"
      node-ip-address: "$MY_POD_IP"
      redis-password: "LetMeInRay"
    replicas: 0
    minReplicas: 0
    maxReplicas: 4
    groupName: cpu-only-large-group
    template:
      spec:
        imagePullSecrets:
          - name: harbor-bybit
          - name: harbor-infra
        initContainers:
          - name: init-myservice
            image: busybox:1.28
            command: ['sh', '-c', "until nslookup $RAY_IP.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
        containers:
          - volumeMounts:
            - mountPath: /tmp/ray
              name: log-volume
            name: ray-worker
            image: harbor.infra.ww5sawfyut0k.bitsvc.io/bigdata/ray:prod-2.0.1-py38-ai2.0
            imagePullPolicy: Always
            resources:
              limits:
                cpu: 6
                memory: 32Gi
              requests:
                cpu: 1
                memory: 1Gi
            env:
              - name: TYPE
                value: worker
              - name: MY_POD_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.podIP
              - name: RAY_DISABLE_DOCKER_CPU_WARNING
                value: "1"
              - name: CPU_REQUEST
                valueFrom:
                  resourceFieldRef:
                    containerName: ray-worker
                    resource: requests.cpu
              - name: MY_POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: MLFLOW_TRACKING_URI
                value: http://mlflow.test.niubit.io
              - name: PLATFORM_ENV
                value: test
              - name: HDFS_CLUSTER_NAME
                value: testcluster
            ports:
              - containerPort: 80
                protocol: TCP
        volumes:
          - emptyDir: {}
            name: log-volume
        affinity:
          {}
        tolerations:
          []
        nodeSelector:
          {}
      metadata:
        annotations:
          key: value
        labels:
          rayNodeType: worker
          groupName: cpu-only-large-group
          rayCluster: ray-cluster-kuberay
          app.kubernetes.io/name: kuberay
          helm.sh/chart: ray-cluster-0.3.0
          app.kubernetes.io/instance: ray-cluster
          app.kubernetes.io/version: "1.0"
          app.kubernetes.io/managed-by: Helm
  - rayStartParams:
      block: "true"
      node-ip-address: "$MY_POD_IP"
      redis-password: "LetMeInRay"
    replicas: 0
    minReplicas: 0
    maxReplicas: 6
    groupName: cpu-only-medium-group
    template:
      spec:
        imagePullSecrets:
          - name: harbor-bybit
          - name: harbor-infra
        initContainers:
          - name: init-myservice
            image: busybox:1.28
            command: ['sh', '-c', "until nslookup $RAY_IP.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
        containers:
          - volumeMounts:
            - mountPath: /tmp/ray
              name: log-volume
            name: ray-worker
            image: harbor.infra.ww5sawfyut0k.bitsvc.io/bigdata/ray:prod-2.0.1-py38-ai2.0
            imagePullPolicy: Always
            resources:
              limits:
                cpu: 4
                memory: 16Gi
              requests:
                cpu: 1
                memory: 1Gi
            env:
              - name: TYPE
                value: worker
              - name: MY_POD_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.podIP
              - name: RAY_DISABLE_DOCKER_CPU_WARNING
                value: "1"
              - name: CPU_REQUEST
                valueFrom:
                  resourceFieldRef:
                    containerName: ray-worker
                    resource: requests.cpu
              - name: MY_POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: MLFLOW_TRACKING_URI
                value: http://mlflow.test.niubit.io
              - name: PLATFORM_ENV
                value: test
              - name: HDFS_CLUSTER_NAME
                value: testcluster
            ports:
              - containerPort: 80
                protocol: TCP
        volumes:
          - emptyDir: {}
            name: log-volume
        affinity:
          {}
        tolerations:
          []
        nodeSelector:
          {}
      metadata:
        annotations:
          key: value
        labels:
          rayNodeType: worker
          groupName: cpu-only-medium-group
          rayCluster: ray-cluster-kuberay
          app.kubernetes.io/name: kuberay
          helm.sh/chart: ray-cluster-0.3.0
          app.kubernetes.io/instance: ray-cluster
          app.kubernetes.io/version: "1.0"
          app.kubernetes.io/managed-by: Helm
  - rayStartParams:
      block: "true"
      node-ip-address: "$MY_POD_IP"
      redis-password: "LetMeInRay"
    replicas: 1
    minReplicas: 1
    maxReplicas: 10
    groupName: cpu-only-small-group
    template:
      spec:
        imagePullSecrets:
          - name: harbor-bybit
          - name: harbor-infra
        initContainers:
          - name: init-myservice
            image: busybox:1.28
            command: ['sh', '-c', "until nslookup $RAY_IP.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
        containers:
          - volumeMounts:
            - mountPath: /tmp/ray
              name: log-volume
            name: ray-worker
            image: harbor.infra.ww5sawfyut0k.bitsvc.io/bigdata/ray:prod-2.0.1-py38-ai2.0
            imagePullPolicy: Always
            resources:
              limits:
                cpu: 4
                memory: 8Gi
              requests:
                cpu: 1
                memory: 1Gi
            env:
              - name: TYPE
                value: worker
              - name: MY_POD_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.podIP
              - name: RAY_DISABLE_DOCKER_CPU_WARNING
                value: "1"
              - name: CPU_REQUEST
                valueFrom:
                  resourceFieldRef:
                    containerName: ray-worker
                    resource: requests.cpu
              - name: MY_POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: MLFLOW_TRACKING_URI
                value: http://mlflow.test.niubit.io
              - name: PLATFORM_ENV
                value: test
              - name: HDFS_CLUSTER_NAME
                value: testcluster
            ports:
              - containerPort: 80
                protocol: TCP
        volumes:
          - emptyDir: {}
            name: log-volume
        affinity:
          {}
        tolerations:
          []
        nodeSelector:
          {}
      metadata:
        annotations:
          key: value
        labels:
          rayNodeType: worker
          groupName: cpu-only-small-group
          rayCluster: ray-cluster-kuberay
          app.kubernetes.io/name: kuberay
          helm.sh/chart: ray-cluster-0.3.0
          app.kubernetes.io/instance: ray-cluster
          app.kubernetes.io/version: "1.0"
          app.kubernetes.io/managed-by: Helm
  - rayStartParams:
      block: "true"
      node-ip-address: "$MY_POD_IP"
      redis-password: "LetMeInRay"
    replicas: 2
    minReplicas: 2
    maxReplicas: 2
    groupName: workergroup
    template:
      spec:
        imagePullSecrets:
          - name: harbor-bybit
          - name: harbor-infra
        initContainers:
          - name: init-myservice
            image: busybox:1.28
            command: ['sh', '-c', "until nslookup $RAY_IP.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
        containers:
          - volumeMounts:
            - mountPath: /tmp/ray
              name: log-volume
            name: ray-worker
            image: harbor.infra.ww5sawfyut0k.bitsvc.io/bigdata/ray:prod-2.0.1-py38-ai2.0
            imagePullPolicy: Always
            resources:
              limits:
                cpu: 8
                memory: 30Gi
                nvidia.com/gpu: 1
              requests:
                cpu: 7
                memory: 30Gi
                nvidia.com/gpu: 1
            env:
              - name: TYPE
                value: worker
              - name: MY_POD_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.podIP
              - name: RAY_DISABLE_DOCKER_CPU_WARNING
                value: "1"
              - name: CPU_REQUEST
                valueFrom:
                  resourceFieldRef:
                    containerName: ray-worker
                    resource: requests.cpu
              - name: MY_POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: MLFLOW_TRACKING_URI
                value: http://mlflow.niubit.io
              - name: PLATFORM_ENV
                value: prod
              - name: HDFS_CLUSTER_NAME
                value: victoria
            ports:
              - containerPort: 80
                protocol: TCP
        volumes:
          - emptyDir: {}
            name: log-volume
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                - key: instancetype
                  operator: In
                  values:
                  - g4dn.2xlarge
              weight: 1
        tolerations:
          - effect: NoSchedule
            key: instancetype
            operator: Equal
            value: g4dn.2xlarge
        nodeSelector:
          {}
      metadata:
        annotations:
          key: value
        labels:
          rayNodeType: worker
          groupName: workergroup
          rayCluster: ray-cluster-kuberay
          app.kubernetes.io/name: kuberay
          helm.sh/chart: ray-cluster-0.3.0
          app.kubernetes.io/instance: ray-cluster
          app.kubernetes.io/version: "1.0"
          app.kubernetes.io/managed-by: Helm
```

### Anything else

I guess this issue may related with my autocale and worker's request and limit config.

Is it set too small so that the autoscale will request lots of worker nodes? if so what is the meaning for the requests and what is the best practices for this.

thanks a lot

autoscale
```
enableInTreeAutoscaling: true
  autoscalerOptions:
    upscalingMode: Default
   resources.
    idleTimeoutSeconds: 60
    imagePullPolicy: Always
 required.
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "500m"
        memory: "512Mi"
```

cpu-only-large-group
```
groupName: cpu-only-large-group
    template:
      spec:
        imagePullSecrets:
          - name: harbor-bybit
          - name: harbor-infra
        initContainers:
          - name: init-myservice
            image: busybox:1.28
            command: ['sh', '-c', "until nslookup $RAY_IP.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
        containers:
          - volumeMounts:
            - mountPath: /tmp/ray
              name: log-volume
            name: ray-worker
            image: harbor.infra.ww5sawfyut0k.bitsvc.io/bigdata/ray:prod-2.0.1-py38-ai2.0
            imagePullPolicy: Always
            resources:
              limits:
                cpu: 6
                memory: 32Gi
              requests:
                cpu: 1
                memory: 1Gi
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
Thank you for opening this issue! It looks like you want to upload a figure in the "What happened + What you expected to happen" section, but the upload fails. Would you mind uploading the image again?

What's the reason for workers being terminated? You can use `kubectl describe` to check the Pods, and use `kubectl logs` to check the logs for Ray cluster's Pods and the operator Pod.

**Comment by DmitriGekhtman** [comment]
What version of Ray and KubeRay are you using?

**Comment by manifest** [comment]
We are experiencing the same issue.

To reproduce:
1. Start a new Ray Cluster.
2. Trigger autoscaling by deploying Ray Jobs.

Expected behavior:
- The execution of the current Ray Jobs continues.

Observed behavior:
- A new Ray Node (a pod) is started.
- The old Ray Node gets terminated and the execution of the current Ray Jobs get terminated.
- The execution of the new Ray Node continues.

The version of the KubeRay operator's chart is `0.5.1`.

```bash
❯ ray --version
ray, version 2.4.0
```
> Ray client version.

```yaml
apiVersion: ray.io/v1alpha1
kind: RayCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: hpc-ray-cluster
spec:
  rayVersion: "2.4.0"
  # If enableInTreeAutoscaling is true, the autoscaler sidecar will be added to the Ray head pod.
  enableInTreeAutoscaling: true
  autoscalerOptions:
    # upscalingMode is "Default" or "Aggressive."
    # Conservative: Upscaling is rate-limited; the number of pending worker pods is at most the size of the Ray cluster.
    # Default: Upscaling is not rate-limited.
    # Aggressive: An alias for Default; upscaling is not rate-limited.
    upscalingMode: Conservative
    # idleTimeoutSeconds is the number of seconds to wait before scaling down a worker pod which is not using Ray resources.
    idleTimeoutSeconds: 60
    env: []
    envFrom: []
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "0.1"
        memory: "100Mi"
  # Ray head pod template.
  headGroupSpec:
    # The `rayStartParams` are used to configure the `ray start` command.
    # See https://github.com/ray-project/kuberay/blob/master/docs/guidance/rayStartParams.md for the default settings of `rayStartParams` in KubeRay.
    # See https://docs.ray.io/en/latest/cluster/cli.html#ray-start for all available options in `rayStartParams`.
    rayStartParams:
      dashboard-host: "0.0.0.0"
      num-cpus: "0"
      num-gpus: "0"
      memory: "0"
      # Use `resources` to optionally specify custom resource annotations for the Ray node.
      # The value of `resources` is a string-integer mapping.
      # Currently, `resources` must be provided in the specific format demonstrated below:
      # resources: '"{\"Custom1\": 1, \"Custom2\": 5}"'
    template:
      spec:
        containers:
        # The Ray head container
        - name: ray-head
          image: rayproject/ray:2.4.0-py310-cpu
          ports:
          - containerPort: 6379
            name: gcs
          - containerPort: 8265
            name: dashboard
          - containerPort: 10001
            name: client
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","ray stop"]
          resources:
            limits:
              cpu: "1"
              memory: "2G"
            requests:
              # For production use-cases, we recommend specifying integer CPU reqests and limits.
              # We also recommend setting requests equal to limits for both CPU and memory.
              # For this example, we use a 500m CPU request to accomodate resource-constrained local
              # Kubernetes testing environments such as KinD and minikube.
              cpu: "0.3"
              # The rest state memory usage of the Ray head node is around 1Gb. We do not
              # recommend allocating less than 2Gb memory for the Ray head pod.
              # For production use-cases, we recommend allocating at least 8Gb memory for each Ray container.
              memory: "2G"
  workerGroupSpecs:
  # the pod replicas in this group typed worker
  - replicas: 1
    minReplicas: 1
    maxReplicas: 10
    groupName: standard-group
    #scaleStrategy:
    #  workersToDelete:
    #  - raycluster-complete-worker-small-group-bdtwh
    #  - raycluster-complete-worker-small-group-hv457
    #  - raycluster-complete-worker-small-group-k8tj7
    # The `rayStartParams` are used to configure the `ray start` command.
    # See https://github.com/ray-project/kuberay/blob/master/docs/guidance/rayStartParams.md for the default settings of `rayStartParams` in KubeRay.
    # See https://docs.ray.io/en/latest/cluster/cli.html#ray-start for all available options in `rayStartParams`.
    rayStartParams:
      resources: '"{\"standard-unit\": 2}"'
    template:
      spec:
        containers:
        - name: ray-worker
          image: rayproject/ray:2.4.0-py310-cpu
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","ray stop"]
          # The limits will be automatically advertised to Ray. On the other hand the **requests will be ignored**.
          # It’s ideal to size each Ray pod to take up the **entire Kubernetes node** on which it is scheduled.
          resources:
            limits:
              # nvidia.com/gpu: "1"
              cpu: "1"
              memory: "1G"
            requests:
              # nvidia.com/gpu: "1"
              cpu: "0.1"
              memory: "100Mi"
```
> Cluster resource.


```python
import ray
import time

@ray.remote
def hello_world():
    return "hello world"

ray.init()
while True:
    print(ray.get(hello_world.remote()))
    time.sleep(1)
```
> Ray Job used in the test.


Uploading 01-ray-autoscaling-issue.mp4…

**Comment by manifest** [comment]
In the case described above, Ray Dashboard displays incorrect information:
> See the [video](https://www.dropbox.com/s/vi07a5u3vuwuexx/02-ray-autoscaling-issue.mp4?dl=0).
- The status of the terminated Ray Jobs is RUNNING even though Ray Node is correctly displayed as terminated. So are all JobSupervisor actors.
- On the logs page for the jobs, URL points out to a new Ray Node, these jobs were never run on.

![03-ray-autoscaling-issue](https://github.com/ray-project/kuberay/assets/439058/46c45fbd-5e9b-497c-8ce0-f8e7166e42c9)
![04-ray-autoscaling-issue](https://github.com/ray-project/kuberay/assets/439058/a159cdee-7a83-44d5-aa5e-1f0de2cfa546)
![05-ray-autoscaling-issue](https://github.com/ray-project/kuberay/assets/439058/e9de3590-35ef-4c59-af19-d13ca0677aa0)
![06-ray-autoscaling-issue](https://github.com/ray-project/kuberay/assets/439058/ae2d177f-512c-40a8-9138-db7b82811854)
![07-ray-autoscaling-issue](https://github.com/ray-project/kuberay/assets/439058/e3c85373-3b3f-4448-899c-1933ff7047c1)

**Comment by manifest** [comment]
The same issue can be reproduced with Ray Workflows. The KubeRay keep creating and deleting new Ray Nodes, tasks get killed and started anew.

To reproduce:
1. Start a new Ray Cluster with `idleTimeoutSeconds: 60`.
2. Trigger autoscaling by deploying Ray Workflows that execute a `2min-job`.

Expected behavior:
- The execution of the current Ray Workflows continues.

Observed behavior:
> See the [video](https://www.dropbox.com/s/3n1n016qr769asf/10-ray-autoscaling-issue.mp4?dl=0).
- A new Ray Node (a pod) is started.
- The old Ray Node gets terminated and the execution of the current Ray Workflows get terminated.
- The execution of the new Ray Node continues and Ray Workflows started again.
- The recursion continues.

```python
from ray import workflow
import ray
import time

@ray.remote(resources={"standard-unit": 1, "num_cpus": 0})
def one() -> int:
    print("++++++++++ started")
    time.sleep(120)
    print("++++++++++ stopped")
    return 1

@ray.remote(resources={"standard-unit": 0, "num_cpus": 0})
def add(a: int, b: int) -> int:
    return a + b

ray.init("ray://127.0.0.1:10001")
dag = add.bind(100, one.bind())

workflow.run_async(dag, workflow_id="701")
workflow.run_async(dag, workflow_id="702")
```
> Ray Workflow used in the test.

**Comment by manifest** [comment]
I've found the source of the issues above in my environment. It wasn't RayAutoscaler.

It was Flux CD that kept killing RayNods on every reconciliation, with the interval set to 1 minute.

**Comment by kevin85421** [comment]
Summarize my guess based on the available limitation information.

1. The value of `idleTimeoutSeconds` is set to 60 seconds. This means that an idle worker Pod will be scaled down after being inactive for 60 seconds. Worker nodes are considered idle when they have no active tasks, actors, or referenced objects (whether in-memory or spilled to disk). However, based on the screenshot, it appears that the worker Pods are being terminated even when they are younger than 60 seconds. Therefore, I speculate that the Pod terminations are not being caused by Ray Autoscaler. In my assumption, the terminations are occurring due to the cluster resources being depleted.

2. There is a significant difference between the resource limits and resource requests. In addition, KubeRay will set the `memory` parameter in `rayStartParams` to the value of the memory limit. In other words, Ray assumes that the Ray node has 32GB of memory, making it easy for the worker Pod to consume more than 1GB of memory (as specified in the resource request).

    ```yaml           
     resources:
        limits:
          cpu: 6
          memory: 32Gi
        requests:
          cpu: 1
          memory: 1Gi
    ```

3. Based on the screenshot, I noticed that some Pods are in a pending state for a few seconds. This leads me to believe that it is highly likely for the Kubernetes cluster is running out of resources. In Kubernetes, when a cluster is running out of resources, it will prioritize terminating Pods that exceed their resource requests but are still within their resource limits. In addition, the resource requests for worker Pods are extremely low, leading me to believe that nearly all worker Pods will consume resources beyond their specified resource requests.
