### ISSUE TITLE
[Bug] Missing state: ready after raycluster started

### ISSUE THREAD

**Issue by tedhtchang** [ray-project/kuberay#991]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

The raycluster status is missing the `state: ready` after raycluster started
```
status:
  availableWorkerReplicas: 1
  endpoints:
    client: "10001"
    dashboard: "8265"
    gcs-server: "6379"
  head:
    podIP: 172.30.212.140
    serviceIP: 172.21.113.139
  lastUpdateTime: "2023-03-27T06:28:23Z"
```

### Reproduction script

```
# Install Ray operator
export KUBERAY_VERSION=v0.4.0
kubectl create -k "github.com/ray-project/kuberay/manifests/cluster-scope-resources?ref=${KUBERAY_VERSION}&timeout=90s"
kubectl apply -k "github.com/ray-project/kuberay/manifests/base?ref=${KUBERAY_VERSION}&timeout=90s"

# create a raycluster
oc apply -f https://raw.githubusercontent.com/ray-project/kuberay/master/ray-operator/config/samples/ray-cluster.mini.yaml
oc get po
# NAME                         READY   STATUS    RESTARTS   AGE
# raycluster-mini-head-sgxn6   1/1     Running   0          87s

# Missing the state field
oc get raycluster raycluster-mini -o jsonpath='{.status}'
{"availableWorkerReplicas":1,"endpoints":{"client":"10001","dashboard":"8265","gcs-server":"6379"},"head":{"serviceIP":"172.21.169.149"},"lastUpdateTime":"2023-03-27T06:37:16Z"}

# Restart the kuberay operator
oc rollout restart deployment.apps/kuberay-operator -n ray-system

# status: ready
oc get raycluster raycluster-mini -o jsonpath='{.status}'
{"availableWorkerReplicas":1,"endpoints":{"client":"10001","dashboard":"8265","gcs-server":"6379"},"head":{"podIP":"172.30.212.180","serviceIP":"172.21.169.149"},"lastUpdateTime":"2023-03-27T06:46:25Z","state":"ready"}
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!
