### ISSUE TITLE
[Feature] Instructions to connect to the RayCluster using TLS authentication from outside the Ray cluster

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#992]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

As suggested by @tedhtchang's [comment](https://github.com/ray-project/kuberay/pull/989/files#r1149633695), it would be helpful to provide instructions for users to connect to the RayCluster using TLS authentication from outside the Ray cluster (e.g. A Pod for JupyterLab). 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by tedhtchang** [comment]
@kevin85421 You can assign this issue to me.

**Comment by tedhtchang** [comment]
Sure. something like:
```
apiVersion: v1
kind: Pod
metadata:
  name: ray-tls
  namespace: my-namespace
spec:
  containers:
  - name: client
    image: rayproject/ray:2.3.0
    args: [/bin/sh, -c, 'python -c "import ray; ray.init(address="ray://service-ray-head.default.svc.cluster.local:6379"); print(ray.cluster_resources())"']
    env:
    - name: RAY_USE_TLS
      value: "1"
    - name: RAY_TLS_SERVER_CERT
      value: "/etc/ray/tls/tls.crt"
    - name: RAY_TLS_SERVER_KEY
      value: "/etc/ray/tls/tls.key"
    - name: RAY_TLS_CA_CERT
      value: "/etc/ca/tls/ca.crt"
    volumeMounts:
      - mountPath: /etc/ca/tls
        name: ca-tls
        readOnly: true
      - mountPath: /etc/ray/tls
        name: ray-tls
      - mountPath: /etc/gen/tls
        name: gen-tls-script
  initContainers:
  - name: ray-client
    image: rayproject/ray:2.3.0
    command: ["/bin/sh", "-c", "cp -R /etc/ca/tls /etc/ray && /etc/gen/tls/gencert_head.sh"]
    volumeMounts:
      - mountPath: /etc/ca/tls
        name: ca-tls
        readOnly: true
      - mountPath: /etc/ray/tls
        name: ray-tls
      - mountPath: /etc/gen/tls
        name: gen-tls-script
    env:
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
  volumes:
  - name: gen-tls-script
    ConfigMap:
      name: tls
  - name: ca-tls
    secret:
      secretName: ca-tls
  - name: ray-tls
    emptyDir: {}
```
